### ISSUE TITLE
Got 'unhandled' if the requested file is missing for static route with custom root.

### ISSUE THREAD

**Issue by LoneEngineer** [ktorio/ktor#1795] opened 2020-04-14 20:54 UTC
**Ktor Version and Engine Used (client or server and name)**
Ktor (Netty) 1.3.2

**Describe the bug**
Let assume there is a following route definition ( fsCfg.uploadPath == '/tmp', also tried to use '/tmp/foo' nothing changed):
```
        static("/images") { 
            staticRootFolder = fsCfg.uploadPath.parent.toFile() // <-- resolved to '/'
            files(fsCfg.uploadPath.fileName.toString())               // <-- resolved to 'tmp'
        }

```
And client requests 2 files where 2nd doesn't exists (2nd log line):

```
2020-04-14 23:47:43.798 INFO  [DefaultDispatcher-worker-6 @request#16][][REQ-3] ktor.test - 200 OK: GET - /images/f2f90894-4840-42d4-a345-1f795855b937
2020-04-14 23:47:46.178 INFO  [DefaultDispatcher-worker-5 @request#21][][REQ-4] ktor.test - Unhandled: GET - /images/f2f90894-4840-42d4-a345-1f795855b937_150
```

As per documentation, expected behavior should be:

> If the requested content is not found, a FileNotFoundException is thrown.

Also ktor-server-core-1.3.2.jar!\io\ktor\http\content\StaticContentKt.class contains following code (which is executed in my case (I set a breakpoint here):

```
fun Route.files(folder: File) {
    val dir = staticRootFolder.combine(folder)
    get("{$pathParameterName...}") {
        val relativePath = call.parameters.getAll(pathParameterName)?.joinToString(File.separator) ?: return@get
        val file = dir.combineSafe(relativePath)
        if (file.isFile) {
            call.respond(LocalFileContent(file))
        }
    }
}
```
Seems like call.respond is not called if file not found.

**Comment by dmitrievanthony** [comment] 2020-04-15 10:53
Hi @LoneEngineer, thanks for reporting. Technically, I think the issue is in incorrect documentation. It's not technically possible in the current model to throw an exception in the place you pointed or respond in any way because there is might be another handler that will process the request. For example:

```
routing {
    static("/images") {
        staticRootFolder = File("/tmp")
        files("images")
    }
    static("/images") {
        staticRootFolder = File("/tmp")
        files("images2")
    }
}
```

If some file is not found in `/tmp/images` it still could be found in `/tmp/images2`.

I'll think of how it's possible to fix the documentation correctly.

**Comment by LoneEngineer** [comment] 2020-04-15 17:22
Hi @dmitrievanthony, thanks for response. I got your point. Perhaps it will be good to have some kind of terminal action (like 'default' file) which will result into 404 (or may be configured one) http response. What are you thinking?

**Comment by dmitrievanthony** [comment] 2020-04-28 09:05
If no one route found the corresponding 404 will be propagated automatically. I merged a fix of the documentation (https://github.com/ktorio/ktorio.github.io/pull/271).

**Closed by dmitrievanthony** 2020-04-28 09:05 UTC
Labels: bug

**Comment by LoneEngineer** [comment] 2020-04-29 14:43
Great thanks @dmitrievanthony !
