### ISSUE TITLE
Internal Compilation Error when Deconstructing in formData

### ISSUE THREAD

**Issue by danthonywalker** [ktorio/ktor#1028] opened 2019-03-19 15:35 UTC
### Ktor Version
1.1.3

### Ktor Engine Used(client or server and name)
Relevant code is `ktor-client-core`, but bug occurs in JVM using `ktor-client-okhttp`.

### JVM Version, Operating System and Relevant Context
java 11.0.2 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)

javac 11.0.2

Windows

### Feedback
Assume a variable, `val files: List<Pair<String, ByteReadPacket>> = emptyList()`.
If you do this:
```kotlin
formData {
    files.forEachIndexed { index, (first, second) ->
        append("file$index", first) { writePacket(second) }
    }
}
```

You'll get an internal compilation error:
```
e: java.lang.IllegalStateException: Backend Internal error: Exception during code generation
Cause: Back-end (JVM) Internal error: wrong code generated
org.jetbrains.kotlin.codegen.CompilationException Back-end (JVM) Internal error: Couldn't transform method node:
invoke (Lio/ktor/client/request/forms/FormBuilder;)V:
    // annotable parameter count: 1 (visible)
    // annotable parameter count: 1 (invisible)
    @Lorg/jetbrains/annotations/NotNull;() // invisible, parameter 0
   L0
    ALOAD 1
    LDC "receiver$0"
    INVOKESTATIC kotlin/jvm/internal/Intrinsics.checkParameterIsNotNull (Ljava/lang/Object;Ljava/lang/String;)V
...
```

However, if you remove the `formData`, say, do this:
```kotlin
files.forEachIndexed { index, (first, second) ->
   println("$index: $first $second")
}
```

Or if you don't deconstruct:
```kotlin
formData {
    files.forEachIndexed { index, file ->
        append("file$index", file.first) { writePacket(file.second) }
    }
}
```

No errors. I'm almost certain this is a Kotlin issue and not specifically a Ktor one, but this is the only context I have found the issue so I bring it to attention here.

**Comment by e5l** [comment] 2019-03-20 09:11
Hi @danthonywalker, thanks for the report.
Could you file YT issue in kotlin `http://youtrack.jetbrains.com`?

**Comment by oleg-larshin** [comment] 2020-08-10 15:24
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-648">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment] 2021-04-05 11:11
Can't reproduce it with Ktor 1.5.3 and Kotlin 1.4.31.

**Closed by Stexxe** 2021-04-05 11:11 UTC
