### ISSUE TITLE
Unable to stream http response - readUTF8Line returns null continuously

### ISSUE THREAD

**Issue by imanushin** [ktorio/ktor#1242] opened 2019-07-23 08:37 UTC
**Ktor Version and Engine Used (client or server and name)**
Ktor CIO 1.2.2 (no additional modules are used)

**Describe the bug**
Ktor http client is unable to download and process huge response by using the following algorithm:
```kotlin
client.call(url).use { call ->
    call.response.use { response ->
          do {
             val line = response.content.readUTF8Line()  // <--- this code returns "" continuously after several loops

             /*process line*/
             
          } while (line !== null)
    }
}
```

**To Reproduce**
1. Start *get* request with potential huge response (I'm trying to download Teamcity Logs, size is between 1 Mb and 10 Gb, however response content size does not matter).
2. Process lines in loop, described above.
3. After several attempts ```readUTF8Line``` returns empty line continuously. So application hangs here.

**Expected behavior**
```readUTF8Line``` returns:
* Next line if available
* ```null``` if stream is closed
* Exception if stream was interrupted (for example - by server)

Probably, there is related issue: #768

**Comment by cy6erGn0m** [comment] 2019-07-23 10:44
Could you please check: 
- isClosedForRead of the channel once null is returned
- rewrite it using readAvailable and check if it still happens

**Comment by imanushin** [comment] 2019-07-23 13:08
@cy6erGn0m,

> isClosedForRead of the channel once null is returned

It returns empty string, e.g. ```""```. And this line is returning continuously (response does not have such items).

> rewrite it using readAvailable and check if it still happens

Result is the same.

However I found the root cause: the problems exists if I start parallel requests with the same client, without any disposal after processing is finished.

E.g. code below hungs:

```
private val sharedClient = HttpClient(CIO){ .... }

suspend fun readLines() {
     sharedClient.call(...) { ... }
}
```

However next code works:

```
suspend fun readLines() {
     return HttpClient(CIO){ .... }.use { client ->
         client.call(...) { ... }
     }     
}
```

**Comment by imanushin** [comment] 2019-07-23 14:08
> However next code works:

Sorry, this is not correct. It just helps working without the failure for more than 100 requests.

**Comment by oleg-larshin** [comment] 2020-08-10 15:30
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-586">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment] 2021-04-05 15:04
Can't reproduce with Ktor 1.5.3. See details in the [KTOR-586](https://youtrack.jetbrains.com/issue/KTOR-586).

**Closed by Stexxe** 2021-04-05 15:04 UTC
Labels: bug
