### ISSUE TITLE
ktor-client-cio throws ConnectTimeoutException when attempting to connect to 0.0.0.0

### ISSUE THREAD

**Issue by SebastianAigner** [ktorio/ktor#1840] opened 2020-04-29 18:45 UTC
**Ktor Version and Engine Used (client or server and name)**
```
implementation("io.ktor:ktor-client-websockets:$ktor_version")
implementation("io.ktor:ktor-client-cio:$ktor_version")
```

**Describe the bug**
A program using ktor-client-cio can't connect to localhost via `0.0.0.0`. Instead, a `ConnectTimeoutException` is thrown.

**To Reproduce**
- Checkout the [0-0-0-0-cio-connection-issue](https://github.com/SebastianAigner/reproduce-ktor-client-coroutine-issue/tree/0-0-0-0-cio-connection-issue) branch of the repro project
- Run the included [`EchoServer.kt`](https://github.com/SebastianAigner/reproduce-ktor-client-coroutine-issue/blob/0-0-0-0-cio-connection-issue/src/main/kotlin/EchoServer.kt). This will start a local server that answers websocket requests on `:9090/chat` with a short text fragment.
- Run the included [`Simplified.kt`](https://github.com/SebastianAigner/reproduce-ktor-client-coroutine-issue/blob/0-0-0-0-cio-connection-issue/src/main/kotlin/Simplified.kt). This makes a webSocket request inside a `runBlocking` call in order to retrieve the text fragment from the server.
- Instead of retrieving the text snippet, an exception is thrown:
```
Exception in thread "main" io.ktor.network.sockets.ConnectTimeoutException: Connect timeout has been expired [url=ws://0.0.0.0:9090/chat, connect_timeout=unknown ms]
	at io.ktor.client.features.HttpTimeoutKt.ConnectTimeoutException(HttpTimeout.kt:157)
	at io.ktor.client.features.HttpTimeoutKt.ConnectTimeoutException$default(HttpTimeout.kt:156)
	at io.ktor.client.engine.cio.Endpoint.getTimeoutException(Endpoint.kt:213)
	at io.ktor.client.engine.cio.Endpoint.connect(Endpoint.kt:205)
	at io.ktor.client.engine.cio.Endpoint$makeDedicatedRequest$1.invokeSuspend(Endpoint.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Expected behavior**
The WebSocket should connect successfully (like it does when using `127.0.0.1` instead of `0.0.0.0`).

If you switch the websocket implementation from `ktor-client-cio` to `ktor-client-okhttp`, the client behaves as expected (ignoring my previously reported [termination issue](https://github.com/ktorio/ktor/issues/1839))

**Comment by e5l** [comment] 2020-05-12 08:37
Hi @SebastianAigner, thanks for the report. Could you tell me your OS version?

**Comment by SebastianAigner** [comment] 2020-05-12 11:20
@e5l macOS Mojave 10.14.6 (18G3020)

**Comment by oleg-larshin** [comment] 2020-08-10 15:32
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-395">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment] 2022-02-08 13:59
Can't reproduce.

**Closed by Stexxe** 2022-02-08 13:59 UTC
Labels: bug
