### ISSUE TITLE
Simple code straight from documentation returns ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by sanity** [ktorio/ktor#467] opened 2018-07-05 21:46 UTC
Using 0.9.3 (current version) I tried the following simple code from the documentation:

```
fun main(args: Array<String>) {
 val s = embeddedServer(Netty, port = 8080) {
        routing {
            get("/") {
                call.respondText("Hello World!", ContentType.Text.Plain)
            }
            get("/demo") {
                call.respondText("HELLO WORLD!")
            }
        }
    }
    s.start(wait = true)
}
```
When I run this code I see:

```
238 [main] INFO ktor.application - No ktor.deployment.watch patterns specified, automatic reload is not active
290 [main] INFO ktor.application - Responding at http://0.0.0.0:8080
```

When I visit http://localhost:8080/ in my browser I get ERR_EMPTY_RESPONSE.  Adding a println() at the beginning of the `get("/")` block reveals that it doesn't seem to be executing any of that code at all.

I'm currently using ktor in a separate project which doesn't suffer from this problem - I've got no idea what's different between one and the other.  Would appreciate any ideas.

**Comment by soywiz** [comment] 2018-07-05 22:34
Maybe you were already listening in 127.0.0.1:8080? 0.0.0.0:8080 worked but the previous one had priority for localhost? Have you tried to close the hello world server and try to do an HTTP request? If it still works you are connecting to other server. Sometimes when closing Java it takes sometime to release the port. Also other programs could bind to that port.

Other possible reason could be a ServiceWorker installed handling requests. Or localhost bound to other IP or not IP bound to localhost and a proxy doing stuff?

You can try changing the port too

**Comment by sanity** [comment] 2018-07-05 22:49
Thanks for the suggestions @soywiz 

I tried changing the port a few times to random ports but unfortunately that didn't fix it.  Something is happening because when I kill my server process and refresh I get a "refused to connect" instead of the empty response error.

So weird, I've copied this code directly from the documentation, do you have nay other suggestions I could try?

**Comment by zumi000** [comment] 2018-08-01 23:38
try this

val s = embeddedServer(Netty, 8080, "127.0.0.1") {
....
}

**Comment by venkaDaria** [comment] 2018-08-16 13:55
I had the same problem while using mavenCentral() instead of jcenter().

**Comment by sanity** [comment] 2018-08-17 14:34
Just FYI - my workaround was to use Jetty instead of Netty.

**Comment by cy6erGn0m** [comment] 2018-08-30 09:01
We need more information to investigate it: have you tried `curl`?  error `ERR_EMPTY_RESPONSE` is not clear enough.

**Comment by dmitryaleksandrov** [comment] 2018-08-30 14:13
I have the same issue on Windows. If I run curl it prints:
curl: (52) Empty reply from server

**Comment by dmitryaleksandrov** [comment] 2018-08-31 07:11
Seems that issue can be solved by invalidating caches (IntelliJ IDEA: File -> Invalidate Caches / Restart -> Invalidate and Restart).

**Comment by ddeya** [comment] 2018-10-04 17:53
I'm having the same problem with ktor 0.9.5 using Netty as embedded server. I'm running on a Windows PC. None of the solutions work for me. Please fix this.

`fun main(args: Array<String>) {
    embeddedServer(Netty, port = 8080, host = "localhost") {
        install(DefaultHeaders)
        install(CallLogging){
            level = Level.TRACE
        }
        routing {
            get(path = "/") {
                call.respondText("Hello World!!", ContentType.Text.Plain)
            }
        }
    }.start()
}`

**Comment by victorbjorn** [comment] 2018-12-21 01:37
I'm going through Ktor getting started guide and having the same issue. Actually it works if I open 127.0.0.1:8989 (replaced 8080 by 8989 cause I have installed Tomcat) but it displays the error above.

**Comment by MarcinMoskala** [comment] 2019-03-01 10:34
Just created Ktor project from the template from the plugin and facing the same problem.

**Comment by oleg-larshin** [comment] 2020-08-10 15:23
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-769">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment] 2020-09-02 15:17
I cannot reproduce it with `1.4.0`. Could anyone tell is it reproducible using the latest released version of Ktor?

**Comment by aoben10** [comment] 2020-10-24 01:16
I can reproduce it on the latest version of ktor. I used the ktor plugin to create my project. Tried both netty and jetty, but still have the same problem

**Comment by cy6erGn0m** [comment] 2020-10-24 07:16
Could it be some kind of software like firewall/security/antivirus/scanner?

**Comment by FlatMapIO** [comment] 2021-01-21 03:32
I have the same problem. Changing the host to `host=127.0.0.1` will work fine

**Comment by e5l** [comment] 2021-03-30 08:44
Can't reproduce

**Closed by e5l** 2021-03-30 08:44 UTC
