### ISSUE TITLE
No response after 16k requests using siege

### ISSUE THREAD

**Issue by enchantinggg4** [ktorio/ktor#1057] opened 2019-04-03 11:37 UTC
### Ktor Version
1.1.3

### Ktor Engine Used(client or server and name)
Netty
### JVM Version, Operating System and Relevant Context
1.8 MacOS 10.13.6
Intel i5
16gb RAM
### Feedback
If i siege single endpoint on ktor, e.g. from ktor generator
```

        get("/json/jackson") {
            call.respond(mapOf("hello" to "world"))
        }
```
netty(i think its netty's problem not ktor tbh) stops responding after ~16k requests using siege

**Comment by melodi-c** [comment] 2019-04-03 13:45
I try this with Jetty engine. Same result. "siege" and "ab" stalled after 16k requests

**Comment by cy6erGn0m** [comment] 2019-04-03 17:36
This could be regression. Also note that macos has some rate-limit that prevents from opening too much connections so frequently.

**Comment by cy6erGn0m** [comment] 2019-04-03 17:45
As a workaround you could try to use http keep alive to avoid reopening sockets

**Comment by bhurlow** [comment] 2019-04-15 21:34
I'm having the same issue with netty, anyone found anything on this?

**Comment by oleg-larshin** [comment] 2020-08-10 15:25
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-634">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment] 2021-07-15 10:36
Cannot reproduce with Ktor 1.6.1.

**Closed by Stexxe** 2021-07-15 10:36 UTC
