### ISSUE TITLE
Ktor client catch ConnectException without printing stacktrace

### ISSUE THREAD

**Issue by Tammo0987** [ktorio/ktor#1006] opened 2019-03-10 20:14 UTC
### Ktor Version 
1.1.3

### Ktor Engine Used
Apache Client

### JVM Version, Operating System and Relevant Context
Java 11, Runtime Environment 18.9 (build 11+28), Windows 10

I want to catch the java.net.ConnectException, when i send a http request without printing the stacktrace. Actually i can catch it, but the stacktrace though is printed. How can i prevent it?

**Comment by e5l** [comment] 2019-03-21 09:52
Hi @Tammo0987, thanks for the report.
Could you reproduce it with `1.2.0-alpha-1`?

**Comment by Tammo0987** [comment] 2019-03-21 14:39
Yes, also in the 1.2.0-alpha-1 version is the caught exception printed. Also in the 1.2.0-alpha-2 version.

**Comment by oleg-larshin** [comment] 2020-08-10 15:26
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-655">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment] 2021-04-05 11:00
Cannot reproduce it with Ktor 1.5.3

**Closed by Stexxe** 2021-04-05 11:00 UTC
Labels: ux
