### ISSUE TITLE
Endian order issue with websockets and CIO

### ISSUE THREAD

**Issue by sksamuel** [ktorio/ktor#1278] opened 2019-08-11 23:47 UTC
**Ktor Version and Engine Used (client or server and name)**
ktor client 1.2.3

**Describe the bug**
java.lang.IllegalArgumentException: Buffer order should be BIG_ENDIAN but it is LITTLE_ENDIAN

	at io.ktor.http.cio.websocket.FrameParser.frame(FrameParser.kt:58)
	at io.ktor.http.cio.websocket.WebSocketReader.parseLoop(WebSocketReader.kt:78)
	at io.ktor.http.cio.websocket.WebSocketReader.readLoop(WebSocketReader.kt:69)
	at io.ktor.http.cio.websocket.WebSocketReader$readLoop$1.invokeSuspend(WebSocketReader.kt)
	at |b|b|b(Coroutine boundary.|b(|b)
	at io.ktor.http.cio.websocket.DefaultWebSocketSessionImpl$runIncomingProcessor$1.invokeSuspend(DefaultWebSocketSessionImpl.kt:226)

**Comment by e5l** [comment] 2019-08-12 06:45
Hi @sksamuel, thank for the report. 

Could you provide the case or snippet to reproduce?

**Comment by sksamuel** [comment] 2019-08-13 04:15
I can't provide a snippet to reproduce because the server side is proprietary. 
The client code is open source and you can find it here:
https://github.com/Landoop/lenses-jdbc/blob/wip/3.0/src/main/kotlin/com/landoop/jdbc4/client/LensesClient.kt

**Comment by sksamuel** [comment] 2019-08-21 17:37
Maybe this stack trace helps:

ava.lang.IllegalArgumentException: Buffer order should be BIG_ENDIAN but it is LITTLE_ENDIAN

	at io.ktor.http.cio.websocket.FrameParser.frame(FrameParser.kt:58)
	at io.ktor.http.cio.websocket.WebSocketReader.parseLoop(WebSocketReader.kt:78)
	at io.ktor.http.cio.websocket.WebSocketReader.readLoop(WebSocketReader.kt:69)
	at io.ktor.http.cio.websocket.WebSocketReader$readLoop$1.invokeSuspend(WebSocketReader.kt)
	at |b|b|b(Coroutine boundary.|b(|b)
	at io.ktor.http.cio.websocket.DefaultWebSocketSessionImpl$runIncomingProcessor$1.invokeSuspend(DefaultWebSocketSessionImpl.kt:226)
	at com.landoop.jdbc4.client.LensesClient.execute(LensesClient.kt:149)
	at com.landoop.jdbc4.statements.LStatement$executeQuery$1.invokeSuspend(LStatement.kt:31)
Caused by: java.lang.IllegalArgumentException: Buffer order should be BIG_ENDIAN but it is LITTLE_ENDIAN
	at io.ktor.http.cio.websocket.FrameParser.frame(FrameParser.kt:58)
	at io.ktor.http.cio.websocket.WebSocketReader.parseLoop(WebSocketReader.kt:78)
	at io.ktor.http.cio.websocket.WebSocketReader.readLoop(WebSocketReader.kt:69)
	at io.ktor.http.cio.websocket.WebSocketReader$readLoop$1.invokeSuspend(WebSocketReader.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.IllegalArgumentException: Buffer order should be BIG_ENDIAN but it is LITTLE_ENDIAN
		at io.ktor.http.cio.websocket.FrameParser.frame(FrameParser.kt:58)
		at io.ktor.http.cio.websocket.WebSocketReader.parseLoop(WebSocketReader.kt:78)
		at io.ktor.http.cio.websocket.WebSocketReader.readLoop(WebSocketReader.kt:69)
		at io.ktor.http.cio.websocket.WebSocketReader$readLoop$1.invokeSuspend(WebSocketReader.kt)
		at |b|b|b(Coroutine boundary.|b(|b)
		at io.ktor.http.cio.websocket.DefaultWebSocketSessionImpl$runIncomingProcessor$1.invokeSuspend(DefaultWebSocketSessionImpl.kt:226)
	[CIRCULAR REFERENCE:java.lang.IllegalArgumentException: Buffer order should be BIG_ENDIAN but it is LITTLE_ENDIAN]

**Comment by dmitrievanthony** [comment] 2020-03-24 11:57
Hi @sksamuel , 

Could you please update the link to the client code because it's not valid anymore? Also, may I ask you to clarify what kind of server you use? Is it a ktor server or some other?

**Comment by dmitrievanthony** [comment] 2020-03-24 15:28
I spent some time on investigation. Looks like a byte buffer allocated via `ByteBuffer.allocate()` returns a buffer with `LITTLE_ENDIAN` byte order while the specification said that:

> The order of
     * a newly-created byte buffer is always {@link ByteOrder#BIG_ENDIAN
     * BIG_ENDIAN}.

Could you please tell me what kind of JDK/JVM you use? Could you also try to execute `ByteBuffer.allocate().order()` command and tell which order is it?

**Comment by sksamuel** [comment] 2020-03-24 17:01
I no longer work at the company where I had this issue.
My best guess is JDK8.

**Comment by dmitrievanthony** [comment] 2020-03-25 12:03
Well, as I said it looks like the root cause is the byte order of newly allocated buffers. It seems not possible to figure out details not knowing the JDK and OS so let me close this issue so far. 

Feel free to reopen it if you have such details or could provide a reproducer.

**Closed by dmitrievanthony** 2020-03-25 12:03 UTC
Labels: bug
