### ISSUE TITLE
iOS client, "Unable to add 'toKotlin:' method to NSBlock class"

### ISSUE THREAD

**Issue by hitherejoe** [ktorio/ktor#1786] opened 2020-04-12 10:56 UTC
Hitting this error when trying to make a simple post request in my project. I've checked this against other projects that have similar configurations and it feels like this might be a bug. If i'm missing something, let me know 👍

**Ktor Version and Engine Used (client or server and name)**
version: 1.3.2
client: iOS

**Describe the bug**
When trying to make a post request, the following error is being thrown:

```
HttpClient: REQUEST: https://identitytoolkit.googleapis.com/signUp
HttpClient: METHOD: HttpMethod(value=POST)
HttpClient: COMMON HEADERS
HttpClient: -> Accept: application/json
HttpClient: -> Accept-Charset: UTF-8
HttpClient: CONTENT HEADERS
/Users/teamcity/buildAgent/work/4d622a065c544371/runtime/src/main/cpp/ObjCExport.mm:345: runtime assert: Unable to add 'toKotlin:' method to NSBlock class

```

**To Reproduce**
I have a branch here: https://github.com/hitherejoe/minimise/tree/task/fix-ios-network-requests

1. Launch the app
2. Hit the "Sign up" / "Sign in" button

**Expected behavior**
The post request should complete and return the expected response

**Comment by e5l** [comment] 2020-04-15 09:13
@SvyatoslavScherbina could you take a look?

**Comment by SvyatoslavScherbina** [comment] 2020-04-15 09:55
Can't reproduce.
Please clean build directories, ensure `shared/SharedCommon/build` is removed, clean Xcode project and try again.

**Comment by oleg-larshin** [comment] 2020-08-10 15:31
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-417">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment] 2021-04-05 15:16
Can't reproduce

**Closed by e5l** 2021-04-05 15:16 UTC
Labels: bug
