### ISSUE TITLE
multiple authenticate fail to redirect

### ISSUE THREAD

**Issue by PinkieSwirl** [ktorio/ktor#1007] opened 2019-03-11 02:40 UTC
### Ktor Version

1.1.3

### Ktor Engine Used(client or server and name)

netty

### JVM Version, Operating System and Relevant Context

jdk 11, windows 10

### Feedback

From my understanding the following code should redirect to the `/login` route, however nothing happens:
```
fun main(args: Array<String>): Unit = io.ktor.server.netty.EngineMain.main(args)

@Suppress("unused") // Referenced in application.conf
@kotlin.jvm.JvmOverloads
fun Application.module(testing: Boolean = false) {
    install(Authentication) {
        form {
            challenge = FormAuthChallenge.Redirect { "/login" }
        }
    }

    routing {
        get("/login") {
            call.respondText("LOGIN")
        }
        authenticate(optional = true) {
            static("/") {
                resources("static")
            }
        }

        authenticate {
            get("/") {
                call.respondText("HELLO WORLD!", contentType = ContentType.Text.Plain)
            }
        }
    }
}
```
The problem seems to be that static (`static("/")`) has the same root path as get (` get("/")`) in conjunction with `authenticate(optional = true) `.

The redirect works again, if the paths are different or/and `optional = false`.

If I activate call logging I get: `INFO  Application - Unhandled: GET - /`

**Comment by oleg-larshin** [comment] 2020-08-10 15:24
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-654">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment] 2021-06-30 12:06
Cannot reproduce it using Ktor 1.6.0 with the following modification:
```kt
install(Authentication) {
    form {
        challenge {
            call.respondRedirect("/login")
        }
    }
}
```

**Closed by Stexxe** 2021-06-30 12:06 UTC
