### ISSUE TITLE
ApplicationCall.push fails under HTTP/1.1

### ISSUE THREAD

**Issue by elizarov** [ktorio/ktor#349] opened 2018-03-07 11:45 UTC
The problem reproduces with `http2-push` from https://github.com/ktorio/ktor-samples

1. Run `./gradlew :http2-push:run`
2. Navigate to http://localhost:8080

Resulting exception:

```
2018-03-07 14:44:55.948 [nettyCallPool-4-1] ERROR Application - Unhandled: GET - /
java.lang.IllegalArgumentException: ParametersBuilder can only build a single Parameters instance
        at io.ktor.http.ParametersBuilder.build(Parameters.kt:26)
        at io.ktor.http.URLBuilder.appendTo(URLBuilder.kt:46)
        at io.ktor.http.URLBuilder.buildString(URLBuilder.kt:62)
        at io.ktor.server.engine.BaseApplicationResponse.push(BaseApplicationResponse.kt:188)
        at io.ktor.routing.RoutingApplicationResponse.push(RoutingApplicationCall.kt)
        at io.ktor.http.PushKt.push(Push.kt:26)
        at io.ktor.http.PushKt.push(Push.kt:13)
        at io.ktor.http.PushKt.push(Push.kt:9)
```

**Comment by thumannw** [comment] 2020-01-11 18:07
I cannot reproduce the problem as described anymore. Most probably already fixed in the meantime.

Can this issue be closed?

**Comment by Stexxe** [comment] 2020-06-27 09:48
I cannot reproduce the error by making GET request to http://localhost:8080. I only get the `javax.net.ssl.SSLHandshakeException` exception, when I try to get **http**://localhost:8443.

**Comment by oleg-larshin** [comment] 2020-08-10 15:22
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-801">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2021-03-30 08:33 UTC
Labels: bug
