### ISSUE TITLE
Error on call.

### ISSUE THREAD

**Issue by bobcat4848** [ktorio/ktor#850] opened 2019-01-05 18:40 UTC
### Ktor Version
Version: 1.1.1

### Ktor Engine Used(client or server and name)
Server and am following this here:
https://ktor.io/servers/calls/responses.html

### JVM Version, Operating System and Relevant Context
JVM: 1.8
OS: Windows 10
Working in IntelliJ Ultimate 2018.1 within a gradle project
The whole project builds, but this line continues to be an error while coding.

Below is a picture of what is happening:
https://i.imgur.com/GE8n7oX.jpg

A picture of my project hierarchy:
https://i.imgur.com/jKngO0i.jpg

All the code from my main class named, "App.kt":
```
import com.jcabi.ssh.Shell
import com.jcabi.ssh.Ssh
import java.io.File
import org.apache.commons.io.FileUtils
import io.ktor.application.*
import io.ktor.features.*
import io.ktor.http.*
import io.ktor.response.*
import io.ktor.routing.*
import io.ktor.server.engine.*
import io.ktor.server.netty.*
import io.ktor.application.*

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun Application.module() {
    routing {
        get("/") {
            call.respondText("Hehe")
        }
    }
}

fun main(args: Array<String>) {
    embeddedServer(Netty, 8080, watchPaths = listOf("AppKt"), module = Application::module).start()
}
```
### Feedback

I really would like to use Ktor for what I am going to make and if this can be fixed, that would be amazing. Thanks in advance.

**Comment by oleg-larshin** [comment] 2020-08-10 15:24
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-701">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment] 2021-07-19 15:00
Cannot reproduce with Ktor 1.6.1 and IntelliJ IDEA 2021.1.3.

**Closed by Stexxe** 2021-07-19 15:00 UTC
