### ISSUE TITLE
Netty warning: Failed to find a usable hardware address

### ISSUE THREAD

**Issue by alexbezhan** [ktorio/ktor#564] opened 2018-09-06 11:37 UTC
I experience `netty` issue when running last `ktor` version `0.9.4` on `Debian 8.1.1`:
```
14:28:36.230 [main] WARN io.netty.util.internal.MacAddressUtil - Failed to find a usable hardware address from the network interfaces; using random bytes: 9b:18:8e:b6:89:5f:d7:98
```

I've created sample hello-world project for easy reproduction: https://github.com/alexbezhan/ktor-helloworld

**Comment by soywiz** [comment] 2018-09-13 13:53
I tried this:

`gradle shadowJar`

`Dockerfile`
```
FROM smartentry/debian:8.1-0.4.1
RUN echo "deb http://http.debian.net/debian jessie-backports main" >> /etc/apt/sources.list
RUN apt-get update && apt-get install -t jessie-backports -y openjdk-8-jdk
VOLUME ["/app"]
```

```
docker build . -t debian-java-demo
```

`./run.sh`
```
BASEDIR="$( cd "$(dirname "$0")" ; pwd -P )"
docker run -v$BASEDIR/build/libs:/app -p 9090:8082 -it debian-java-demo java -jar /app/ktor-helloworld-1.0.0-SNAPSHOT.jar
```

```
wget http://127.0.0.1:9090
```

Works fine.

Was not able to reproduce your problem. I'm afraid that might be a problem with the configuration of your machine. And sadly I can't help there.

I'm closing the issue. Feel free to reopen it if you are able to reproduce it with a VM or something so I can reproduce it.

PS this is the output I get:
```
smartentry> running main program(UID=0 GID=0 USER=root)
13:52:37.904 [main] DEBUG io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
13:52:37.909 [main] DEBUG io.netty.channel.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 8
13:52:37.942 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
13:52:37.943 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
13:52:37.958 [main] DEBUG io.netty.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
13:52:37.958 [main] DEBUG io.netty.util.internal.PlatformDependent0 - Java version: 8
13:52:37.960 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
13:52:37.961 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
13:52:37.962 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
13:52:37.963 [main] DEBUG io.netty.util.internal.PlatformDependent0 - direct buffer constructor: available
13:52:37.964 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
13:52:37.964 [main] DEBUG io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable prior to Java9
13:52:37.964 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): available
13:52:37.964 [main] DEBUG io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: available
13:52:37.965 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
13:52:37.965 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
13:52:37.966 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
13:52:37.966 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: 466092032 bytes
13:52:37.967 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
13:52:37.967 [main] DEBUG io.netty.util.internal.CleanerJava6 - java.nio.ByteBuffer.cleaner(): available
13:52:37.970 [main] DEBUG io.netty.util.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available
13:52:37.993 [main] INFO Application - No ktor.deployment.watch patterns specified, automatic reload is not active
13:52:38.292 [main] INFO Application - Responding at http://0.0.0.0:8082
13:52:38.304 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.processId: 19 (auto-detected)
13:52:38.306 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv4Stack: false
13:52:38.306 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv6Addresses: false
13:52:38.307 [main] DEBUG io.netty.util.NetUtil - Loopback interface: lo (lo, 127.0.0.1)
13:52:38.308 [main] DEBUG io.netty.util.NetUtil - /proc/sys/net/core/somaxconn: 128
13:52:38.310 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.machineId: 02:42:ac:ff:fe:11:00:02 (auto-detected)
13:52:38.313 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
13:52:38.313 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
13:52:38.317 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
13:52:38.317 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.targetRecords: 4
13:52:38.335 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numHeapArenas: 4
13:52:38.335 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numDirectArenas: 4
13:52:38.335 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.pageSize: 8192
13:52:38.335 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxOrder: 11
13:52:38.336 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 16777216
13:52:38.336 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.tinyCacheSize: 512
13:52:38.336 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256
13:52:38.336 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64
13:52:38.336 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
13:52:38.336 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
13:52:38.337 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.useCacheForAllThreads: true
13:52:38.344 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: pooled
13:52:38.344 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 0
13:52:38.345 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
```

**Closed by soywiz** 2018-09-13 13:53 UTC
