### ISSUE TITLE
io.ktor.http.cio.ParserException: Character with code 59 is not allowed in header names,

### ISSUE THREAD

**Issue by superbgv** [ktorio/ktor#1556] opened 2020-01-10 10:46 UTC
**Ktor Version and Engine Used (client or server and name)**
version, client/server, additional ktor modules included
    implementation 'io.ktor:ktor-server-netty:1.2.6'
    implementation 'io.ktor:ktor-server-core:1.2.6'
    implementation 'com.googlecode.ez-vcard:ez-vcard:0.10.5'

**Describe the bug**
Using Ktor to host a server, from client passing Vcard in multipart/form-data. Getting an exception saying "System.err: io.ktor.http.cio.ParserException: Character with code 59 is not allowed in header names, "

StackTrace::
====================

01-10 16:06:40.925  9831 10021 W System.err: io.ktor.http.cio.ParserException: Character with code 59 is not allowed in header names, 
01-10 16:06:40.925  9831 10021 W System.err: Content-Disposition: form-data; name="contacts|vcard246.vcf"Content-Transfer-Encoding: binaryContent-Type: multipart/form-data; charset=utf-8Content-Length: 156GIN:VCARDVERSION:3.0N;CHARSET=UTF-8: ;xxx.yyy.zzz.www; ; ; 
01-10 16:06:40.926  9831 10021 W System.err: 	at io.ktor.http.cio.HttpParserKt.characterIsNotAllowed(HttpParser.kt:275)
01-10 16:06:40.926  9831 10021 W System.err: 	at io.ktor.http.cio.HttpParserKt.parseHeaderNameFailed(HttpParser.kt:234)
01-10 16:06:40.926  9831 10021 W System.err: 	at io.ktor.http.cio.HttpParserKt.parseHeaderName(HttpParser.kt:220)
01-10 16:06:40.926  9831 10021 W System.err: 	at io.ktor.http.cio.HttpParserKt.parseHeaders(HttpParser.kt:111)
01-10 16:06:40.926  9831 10021 W System.err: 	at io.ktor.http.cio.HttpParserKt$parseHeaders$2.invokeSuspend(Unknown Source:10)
01-10 16:06:40.926  9831 10021 W System.err: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
01-10 16:06:40.927  9831 10021 W System.err: 	at kotlinx.coroutines.DispatchedContinuation.resumeWith(DispatchedContinuation.kt:171)
01-10 16:06:40.927  9831 10021 W System.err: 	at kotlinx.coroutines.io.internal.CancellableReusableContinuation.resumeWith(CancellableReusableContinuation.kt:93)
01-10 16:06:40.927  9831 10021 W System.err: 	at kotlinx.coroutines.io.ByteBufferChannel.resumeReadOp(ByteBufferChannel.kt:2211)
01-10 16:06:40.927  9831 10021 W System.err: 	at kotlinx.coroutines.io.ByteBufferChannel.flushImpl(ByteBufferChannel.kt:156)
01-10 16:06:40.927  9831 10021 W System.err: 	at kotlinx.coroutines.io.ByteBufferChannel.flush(ByteBufferChannel.kt:162)
01-10 16:06:40.927  9831 10021 W System.err: 	at kotlinx.coroutines.io.ByteBufferChannel.writeAsMuchAsPossible(ByteBufferChannel.kt:2719)
01-10 16:06:40.927  9831 10021 W System.err: 	at kotlinx.coroutines.io.ByteBufferChannel.writeFully(ByteBufferChannel.kt:1169)
01-10 16:06:40.927  9831 10021 W System.err: 	at io.ktor.server.netty.cio.RequestBodyHandler.copy(RequestBodyHandler.kt:133)
01-10 16:06:40.927  9831 10021 W System.err: 	at io.ktor.server.netty.cio.RequestBodyHandler.processContent(RequestBodyHandler.kt:95)
01-10 16:06:40.928  9831 10021 W System.err: 	at io.ktor.server.netty.cio.RequestBodyHandler$job$1.invokeSuspend(RequestBodyHandler.kt:38)
01-10 16:06:40.928  9831 10021 W System.err: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
01-10 16:06:40.928  9831 10021 W System.err: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
01-10 16:06:40.928  9831 10021 W System.err: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
01-10 16:06:40.928  9831 10021 W System.err: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
01-10 16:06:40.928  9831 10021 W System.err: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
01-10 16:06:40.928  9831 10021 W System.err: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
01-10 16:06:40.928  9831 10021 W System.err: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
01-10 16:06:40.928  9831 10021 W System.err: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

**Comment by oleg-larshin** [comment] 2020-08-10 15:31
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-494">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment] 2021-07-01 09:57
Cannot reproduce with Ktor 1.6.1.

**Closed by Stexxe** 2021-07-01 09:57 UTC
Labels: bug
