### ISSUE TITLE
Challenge not executed when no JWT token given

### ISSUE THREAD

**Issue by Monchi** [ktorio/ktor#1503] opened 2019-12-16 18:42 UTC
**Ktor Version and Engine Used (client or server and name)**
server 1.2.6, auth-jwt feature

**Describe the bug**
With jwt authentication, the challenge called when the token is invalid, but not called when no token given.

**To Reproduce**

```kotlin
install(Authentication) {
    jwt {
        verifier(verifier)
        validate { credential ->
            if (credential.payload.audience.contains(jwtAudience)) JWTPrincipal(credential.payload) else null
        }
        challenge { _, _ ->
            this.context.authentication.errors["JWTAuth"]?.let {
                // AuthenticationFailedCause.InvalidCredentials passed when set broken token in header
                // But AuthenticationFailedCause.NoCredentials never passed when no token in header
            }
        }
    }
}
```

**Expected behavior**
All AuthenticationFailedCause passed to challenge including one generated here:
https://github.com/ktorio/ktor/blob/41d9b4802d8381298ab84addac48ed6168828ffb/ktor-features/ktor-auth-jwt/jvm/src/io/ktor/auth/jwt/JWTAuth.kt#L174

**Comment by cy6erGn0m** [comment] 2019-12-24 16:20
Could you please try it with 1.3.0-rc? I can't reproduce it

**Comment by Monchi** [comment] 2019-12-25 11:06
Not resolved with 1.3.0-rc. Still challenge does not be executed.

**Comment by cy6erGn0m** [comment] 2020-01-28 15:43
Still no clue how do I reproduce it. I have added exactly the same in tests and it works

**Comment by oleg-larshin** [comment] 2020-08-10 15:30
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-508">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment] 2021-04-05 13:02
Can't reproduce

**Closed by e5l** 2021-04-05 13:02 UTC
Labels: bug
