### ISSUE TITLE
Chained slow calls break application

### ISSUE THREAD

**Issue by wem** [ktorio/ktor#863] opened 2019-01-10 20:02 UTC
[project.zip](https://github.com/ktorio/ktor/files/2746900/project.zip)
### Ktor Version
1.1.1

### Ktor Engine Used(client or server and name)
CIO / Netty

### JVM Version, Operating System and Relevant Context
jdk8u172-b11

### Feedback

I have an application with a call stack (Browser -> [Ktor server -> Ktor client] -> external backend).
One resource on the external backend is really slow from time to time (3 minutes +). In that case, it looks like the Ktor client runs in a timeout and the whole application is no more accessible. Means, following requests fails instantly with the same exception.

Attached you will find the project.

Stacktrace:
```
 kotlinx.coroutines.JobCancellationException: Parent job is Cancelling
Caused by: kotlinx.coroutines.channels.ClosedReceiveChannelException: Channel was closed
	at kotlinx.coroutines.channels.Closed.getReceiveException(AbstractChannel.kt:1081) ~[kotlinx-coroutines-core-1.1.0.jar:?]
	at kotlinx.coroutines.channels.AbstractChannel$ReceiveElement.resumeReceiveClosed(AbstractChannel.kt:913) ~[kotlinx-coroutines-core-1.1.0.jar:?]
	at kotlinx.coroutines.channels.AbstractSendChannel.helpClose(AbstractChannel.kt:323) ~[kotlinx-coroutines-core-1.1.0.jar:?]
	at kotlinx.coroutines.channels.AbstractSendChannel.close(AbstractChannel.kt:262) ~[kotlinx-coroutines-core-1.1.0.jar:?]
	at kotlinx.coroutines.channels.ChannelCoroutine.close(ChannelCoroutine.kt) ~[kotlinx-coroutines-core-1.1.0.jar:?]
	at kotlinx.coroutines.channels.SendChannel$DefaultImpls.close$default(Channel.kt:94) ~[kotlinx-coroutines-core-1.1.0.jar:?]
	at io.ktor.network.tls.TLSClientHandshake$input$1.invokeSuspend(TLSClientHandshake.kt:98) ~[ktor-network-tls-1.1.1.jar:1.1.1]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32) ~[kotlin-stdlib-1.3.11.jar:1.3.11-release-273 (1.3.11)]
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233) ~[kotlinx-coroutines-core-1.1.0.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594) ~[kotlinx-coroutines-core-1.1.0.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60) ~[kotlinx-coroutines-core-1.1.0.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742) ~[kotlinx-coroutines-core-1.1.0.jar:?]
```

**Comment by cy6erGn0m** [comment] 2019-01-10 20:53
Need to be investigated if it was fixed as per #838. Could be also related to #806 and other friends

**Comment by e5l** [comment] 2019-01-11 05:14
Hi @wem, thanks for the report.

Could you provide the request perform sample with server?

**Comment by e5l** [comment] 2019-02-18 09:17
Can't reproduce with current `develop`, could you check it with `1.1.2`?

**Comment by psartini** [comment] 2019-02-24 18:22
I had the same (or similar) error with `1.1.3` and the CIO HttpClient.

We receive messages from a broker. Inside the message handler we POST the result to another server. HttpClient is called inside a runBlocking { } code block. Requests to the endpoint normally take about one second. Timeout is set to 3 sec.

After switching to Apache engine the error was gone.

Maybe of interest: I could not reproduce the error on my developer machine with tons of resources. Error occured only on a more restricted environment with only 2 vcores and ~2 gig of free RAM.

**Comment by serebit** [comment] 2019-03-09 23:57
Same issue for me, on `1.1.3` and `CIO`.

**Comment by e5l** [comment] 2019-05-27 08:11
We eliminate the `https` problem with freeze in `1.2.0`. Could you recheck it?

**Comment by serebit** [comment] 2019-06-02 19:26
Tested with `ktor-client-cio` version `1.2.1`, and this appears to be fixed in my case.

**Comment by e5l** [comment] 2019-06-05 06:27
Thanks. Closed

**Closed by e5l** 2019-06-05 06:27 UTC
Labels: bug
