### ISSUE TITLE
[ktor-android-client] java.lang.IllegalArgumentException: Bad position

### ISSUE THREAD

**Issue by gabin8** [ktorio/ktor#1718] opened 2020-03-12 15:28 UTC
**Ktor Version and Engine Used (client or server and name)**
Ktor 1.3.2
ktor-client-android

**Describe the bug**
I have android client with enabled response validator. From time to time I get crashes **IllegalArgumentException: Bad position 68/67** when I'm trying to get a content of error response body. The crash happens randomly, but I'm confident that string that comes from backend is always the same. Stacktrace:
```json
2020-03-12 16:54:26.633 19132-19132/com.testapp.android W/System.err: java.lang.IllegalArgumentException: Bad position 68/67
2020-03-12 16:54:26.633 19132-19132/com.testapp.android W/System.err:     at java.nio.Buffer.position(Buffer.java:259)
2020-03-12 16:54:26.633 19132-19132/com.testapp.android W/System.err:     at io.ktor.utils.io.charsets.UTFKt.decodeUTF8Line_array(UTF.kt:661)
2020-03-12 16:54:26.633 19132-19132/com.testapp.android W/System.err:     at io.ktor.utils.io.charsets.UTFKt.decodeUTF8Line(UTF.kt:36)
2020-03-12 16:54:26.633 19132-19132/com.testapp.android W/System.err:     at io.ktor.utils.io.ByteBufferChannel$readUTF8LineToUtf8Suspend$2.invokeSuspend(ByteBufferChannel.kt:2120)
2020-03-12 16:54:26.633 19132-19132/com.testapp.android W/System.err:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2020-03-12 16:54:26.633 19132-19132/com.testapp.android W/System.err:     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
2020-03-12 16:54:26.633 19132-19132/com.testapp.android W/System.err:     at android.os.Handler.handleCallback(Handler.java:873)
2020-03-12 16:54:26.633 19132-19132/com.testapp.android W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2020-03-12 16:54:26.633 19132-19132/com.testapp.android W/System.err:     at android.os.Looper.loop(Looper.java:207)
2020-03-12 16:54:26.634 19132-19132/com.testapp.android W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6878)
2020-03-12 16:54:26.634 19132-19132/com.testapp.android W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-03-12 16:54:26.634 19132-19132/com.testapp.android W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
2020-03-12 16:54:26.634 19132-19132/com.testapp.android W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
```
Client configuration:
```kotlin
private val client by lazy {
        HttpClient(Android) {
            engine {
                connectTimeout = 60_000
                socketTimeout = 40_000
            }
            install(Logging) {
                logger = Logger.SIMPLE
                level = LogLevel.ALL
            }
            install(JsonFeature) {
                serializer = KotlinxSerializer(Json(JsonConfiguration(ignoreUnknownKeys = true)))
            }
            HttpResponseValidator {
                validateResponse { response ->
                    when (val statusCode = response.status.value) {
                        in 400..499 -> {
                            val errorStr = response.content.readUTF8Line()
                            if (!errorStr.isNullOrBlank()) {
                            	val errorDTO = Json.parse(ErrorDTO.serializer(), errorStr) 	
                            	throw ErrorDTOException(errorDTO)
                            } 
                        }
                    }
                }
            }
        }
    }
```

**Expected behavior**
Please make it not crash

**Comment by dmitrievanthony** [comment] 2020-03-13 12:01
Hi @gabin8,

Thanks for reporting! It looks like the problem occurs rarely and only on Android but not in a regular Java. Anyway, I managed to reproduce it and will continue the investigation.

**Comment by dmitrievanthony** [comment] 2020-03-16 07:40
Hi @gabin8, I've just merged the fix, so the next release will include it. Feel free to reopen the issue if you have any additional comments or questions.

**Closed by dmitrievanthony** 2020-03-16 07:40 UTC
Labels: bug
