### ISSUE TITLE
Headers use encoding different from other major HTTP clients (engine-default vs. UTF-8)

### ISSUE THREAD

**Issue by fluidsonic** [ktorio/ktor#1180] opened 2019-06-10 19:05 UTC
The following URL causes a redirect:
https://www.facebook.com/pg/253802271688277/

In **Chrome** and when using **curl** the redirect URL is decoded like this:
`https://www.facebook.com/GRAÇA-77-253802271688277/`

**Ktor client** interprets it differently. There the value of the `Location` header looks like this:
`https://www.facebook.com/GRAÃA-77-253802271688277/`

And after passing it to `Url(…)` like this:
`https://www.facebook.com/GRA%C3%83%C2%87A-77-253802271688277/`

I'd expect it to be interpreted just like by the other clients.

The URL sent by Facebook is **UTF-8** encoded. However the Apache client by default simply converts every single `byte` to `char` without further decoding.

The following configuration makes the redirect work properly.
Maybe it can be considered a good default for a more predictable behavior.
```
HttpClient(Apache) {
   engine {
      customizeClient {
         setDefaultConnectionConfig(ConnectionConfig.custom().setCharset(Charsets.UTF_8).build())
      }
   }
}
```

### Ktor Version
1.2.0

### Ktor Engine Used(client or server and name)
Apache client

### JVM Version, Operating System and Relevant Context
JDK 1.8.0.191, macOS

Somewhat related to #607.

**Comment by oleg-larshin** [comment] 2020-08-10 15:30
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-609">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment] 2021-07-22 10:58
Cannot reproduce it using Ktor 1.6.1.

**Closed by Stexxe** 2021-07-22 10:58 UTC
Labels: bug
