### ISSUE TITLE
ktor-network - client socket close throws exception on server that, even if caught, prints stack trace in console

### ISSUE THREAD

**Issue by nlbuescher** [ktorio/ktor#1686] opened 2020-02-28 21:59 UTC
**Ktor Version and Engine Used (client or server and name)**
ktor-network 1.3.1

**Describe the bug**
Using the slightly modified Socket Echo Server sample code from the [ktor docs](https://ktor.io/servers/raw-sockets.html):

```kotlin
fun main() {
    runBlocking {
        val server = aSocket(ActorSelectorManager(Dispatchers.IO)).tcp().bind(InetSocketAddress("127.0.0.1", 2323))
        println("Started echo telnet server at ${server.localAddress}")

        while (true) {
            val socket = server.accept()

            launch {
                println("Socket accepted: ${socket.remoteAddress}")

                val input = socket.openReadChannel()
                val output = socket.openWriteChannel(autoFlush = true)

                try {
                    while (true) {
                        val line = input.readUTF8Line()

                        println("${socket.remoteAddress}: $line")
                        output.write("$line\r\n")
                    }
                } catch (e: Exception) {
                    // don't print stack trace so we can differentiate
                    //e.printStacktrace()
                    println("caught exception: ${e.message}")
                    socket.dispose()
                }
            }
        }
    }
}
```

If a client connects and at some point the connection is closed by the client, an `IOException` is thrown, and caught, but the stacktrace is still printed in the console. It's important to note that the echo server **continues running** and still accepts new connections.

This does not seem to be a coroutines issue since the following code catches the exception, but no extra stack trace is printed in the console:

```kotlin
fun main() {
    runBlocking {
        launch {
            try {
                throw IOException("test")
            } catch (e: Exception) {
                println("caught exception: ${e.message}")
            }
        }
    }
}
```

**To Reproduce**
Using the above server code:
1. start the server
2. connect to it (eg `telnet localhost 2323`)
3. close the connection (eg close the terminal window)

**Expected behavior**
Since the exception is caught, it is expected that the stack trace is not printed, since printing the stack trace is not configured anywhere explicitly.

**Screenshots**
Echo server output:
<img width="808" alt="Снимок экрана 2020-02-28 в 4 49 45 PM" src="https://user-images.githubusercontent.com/2711898/75590106-8c87a100-5a4a-11ea-8bbe-d6805a8e3f66.png">

Coroutine only output:
<img width="248" alt="Снимок экрана 2020-02-28 в 4 56 43 PM" src="https://user-images.githubusercontent.com/2711898/75590430-4ed74800-5a4b-11ea-93fe-7430abb3b4b4.png">

**Comment by oleg-larshin** [comment] 2020-08-10 15:31
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-459">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment] 2021-07-05 10:42
Cannot reproduce with Ktor 1.6.1.

**Closed by Stexxe** 2021-07-05 10:42 UTC
Labels: bug
