### ISSUE TITLE
application.conf isn't being found with multiplatform plugin

### ISSUE THREAD

**Issue by ScottPierce** [ktorio/ktor#840] opened 2018-12-29 01:33 UTC
### Ktor Version
1.1.1

### Ktor Engine Used(client or server and name)
Server

### JVM Version, Operating System and Relevant Context
```
IntelliJ IDEA 2018.3.2 (Ultimate Edition)
Build #IU-183.4886.37, built on December 17, 2018
JRE: 1.8.0_152-release-1343-b26 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6
```

### Feedback
My `application.conf` appears to not be found. I'm using the multiplatform plugin with a single jvm target. I'm doing this because I'm exposing server models to android and iOS clients, and using multiplatform across all modules seemed like the easiest way to handle this. Please correct me if there is a better way to do this.

**Code from `Main.kt`:**
```Kotlin
object EdgeApplication {
    @JvmStatic fun main(args: Array<String>) {
        embeddedServer(Netty,
            port = 8080,
            watchPaths = listOf(
                "controller",
                "data",
                "edge",
                "model",
                "persist"
            ),
            module = Application::authModule
        ).start(wait = true)
    }
}

fun Application.authModule() {
    val issuer = environment.config.property("jwt.domain").getString()
    val audience = environment.config.property("jwt.audience").getString()
    val realm = environment.config.property("jwt.realm").getString()
    // ...
}
```

**application.conf:**
```
jwt {
    domain = "https://jwt-provider-domain/"
    audience = "jwt-audience"
    realm = "ktor sample app"
}
```

**Stacktrace:**
```
/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/bin/java "-javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=56173:/Applications/IntelliJ IDEA.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath /Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/lib/tools.jar:/Users/scott.pierce/workspace/WMBA/check-in/checkin-server/edge/build/classes/kotlin/jvm/main:/Users/scott.pierce/workspace/WMBA/check-in/checkin-server/controller/build/classes/kotlin/jvm/main:/Users/scott.pierce/workspace/WMBA/check-in/checkin-server/model/build/classes/kotlin/jvm/main:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.3.11/dd9bff00d6cfca58b6c1fe89be8e0678e35cf35f/kotlin-stdlib-jdk8-1.3.11.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/io.ktor/ktor-server-netty/1.1.1/4ecadba38fd5f053268563f374c3970b9c5b90f7/ktor-server-netty-1.1.1.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/io.ktor/ktor-auth-jwt/1.1.1/cd4ebaa19bdaf929ed11c82f05484e7d7a8c3b52/ktor-auth-jwt-1.1.1.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/io.ktor/ktor-locations/1.1.1/a0c31f0493438032e4b3966231b2e0766047a6a8/ktor-locations-1.1.1.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/io.ktor/ktor-jackson/1.1.1/b65c7a4d75400949fc64edd5d377e2f6c5017a3d/ktor-jackson-1.1.1.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.datatype/jackson-datatype-jsr310/2.9.2/e1653d338703d8233cc1ac18c6722510bdaceb4f/jackson-datatype-jsr310-2.9.2.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.3.11/4cbc5922a54376018307a731162ccaf3ef851a39/kotlin-stdlib-1.3.11.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.3.11/4839661cf6ce3c14b65ed7dcf5b9249b44ecca16/kotlin-stdlib-jdk7-1.3.11.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.3.11/aae7b33412715e9ed441934c4ffaad1bb80e9d36/kotlin-reflect-1.3.11.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/atomicfu/0.12.0/121e5983b99875b8c56ce57b31c915a251ab4ec0/atomicfu-0.12.0.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/1.7.25/da76ca59f6a57ee3102f8f9bd9cee742973efa8a/slf4j-api-1.7.25.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/com.typesafe/config/1.3.1/2cf7a6cc79732e3bdf1647d7404279900ca63eb0/config-1.3.1.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-coroutines-jdk8/1.1.0/c4985f08c92832fd4e8b975395e4431a258f0174/kotlinx-coroutines-jdk8-1.1.0.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-io-jvm/0.1.3/17b417c64bbce4361514c3a70133d7cc12531f98/kotlinx-io-jvm-0.1.3.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-coroutines-io-jvm/0.1.3/6103667250c1d9a27e96ad49d8ccce988f94006d/kotlinx-coroutines-io-jvm-0.1.3.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/io.ktor/ktor-server-host-common/1.1.1/25f4c2c8c5827a544f710bf8ba0dc6892902b50b/ktor-server-host-common-1.1.1.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/io.netty/netty-codec-http2/4.1.24.Final/c0c0d9d20402e4493083447052b59d5680e88b2e/netty-codec-http2-4.1.24.Final.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/org.eclipse.jetty.alpn/alpn-api/1.1.3.v20160715/a1bf3a937f91b4c953acd13e8c9552347adc2198/alpn-api-1.1.3.v20160715.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/io.ktor/ktor-auth/1.1.1/8b814227032b5c1cf0e2b8874bf1e8ab8b62f29d/ktor-auth-1.1.1.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/com.auth0/java-jwt/3.4.0/e7ce62e0e190ed86c6edca4c0562dd03b432a141/java-jwt-3.4.0.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/com.auth0/jwks-rsa/0.5.0/db7f14bb8e88b28edbd7c0e7de9ebc67004d5114/jwks-rsa-0.5.0.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.module/jackson-module-kotlin/2.9.2/a9cf72ae68a641ade45c400b6cec2d363818f11b/jackson-module-kotlin-2.9.2.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.3.11/d8b8e746e279f1c4f5e08bc14a96b82e6bb1de02/kotlin-stdlib-common-1.3.11.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/org.jetbrains/annotations/13.0/919f0dfe192fb4e063e7dacadee7f8bb9a2672a9/annotations-13.0.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-coroutines-core/1.1.0/20274ba816d8938fdb4d7a3806719691db60fa1e/kotlinx-coroutines-core-1.1.0.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/atomicfu-common/0.12.0/85d8f3e41940024524c45f9143e5e9866f7a6543/atomicfu-common-0.12.0.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-io/0.1.3/f3df9e1d097a0140b93c6874a756e22b7520144f/kotlinx-io-0.1.3.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-coroutines-io/0.1.3/448395d0e62f1047025ccdc1a5238337460af399/kotlinx-coroutines-io-0.1.3.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/io.ktor/ktor-server-core/1.1.1/24c2f13ac14e8bd503ed7a30176f54653dc2e61/ktor-server-core-1.1.1.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/io.ktor/ktor-http-cio/1.1.1/60a047876b54fc6f830b20e2d76c9e2a788a02bd/ktor-http-cio-1.1.1.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/io.netty/netty-codec-http/4.1.24.Final/8f20009953b2c7c3d860cef928007bc01aa58ac/netty-codec-http-4.1.24.Final.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/io.netty/netty-handler/4.1.24.Final/bad56e7da211c5ebe031ae155cb648b1065c7bb6/netty-handler-4.1.24.Final.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/io.ktor/ktor-client-core-jvm/1.1.1/9306af36f11ea6ed14705f4b15cdda308599ab60/ktor-client-core-jvm-1.1.1.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/com.googlecode.json-simple/json-simple/1.1.1/c9ad4a0850ab676c5c64461a05ca524cdfff59f1/json-simple-1.1.1.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-databind/2.9.6/cfa4f316351a91bfd95cb0644c6a2c95f52db1fc/jackson-databind-2.9.6.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/commons-codec/commons-codec/1.11/3acb4705652e16236558f0f4f2192cc33c3bd189/commons-codec-1.11.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/commons-io/commons-io/2.6/815893df5f31da2ece4040fe0a12fd44b577afaf/commons-io-2.6.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/19.0/6ce200f6b23222af3d8abb6b6459e6c44f4bb0e9/guava-19.0.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-coroutines-core-common/1.1.0/d81cc72afd6e49f5270db24bae935f9bfcfd859e/kotlinx-coroutines-core-common-1.1.0.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/io.ktor/ktor-utils-jvm/1.1.1/e1efbfe2409e41b4695cdbb4fa938db602b1d5d0/ktor-utils-jvm-1.1.1.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/io.ktor/ktor-http-jvm/1.1.1/fe0a7e2daf1761eda32d1c8e19d5c711932b3af9/ktor-http-jvm-1.1.1.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/io.ktor/ktor-network/1.1.1/bacc1b44c6d45202a926da9488881a6373d2be73/ktor-network-1.1.1.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/io.netty/netty-codec/4.1.24.Final/290857e5103956bbda11836e33245f2439226b77/netty-codec-4.1.24.Final.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/junit/junit/4.10/e4f1766ce7404a08f45d859fb9c226fc9e41a861/junit-4.10.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-annotations/2.9.0/7c10d545325e3a6e72e06381afe469fd40eb701/jackson-annotations-2.9.0.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-core/2.9.6/4e393793c37c77e042ccc7be5a914ae39251b365/jackson-core-2.9.6.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/io.netty/netty-transport/4.1.24.Final/d37292c94d3a4cba48d9b6cfb6e8e55282035d0d/netty-transport-4.1.24.Final.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/org.hamcrest/hamcrest-core/1.1/860340562250678d1a344907ac75754e259cdb14/hamcrest-core-1.1.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/io.netty/netty-buffer/4.1.24.Final/e354bed2e60b568307138e403f55ba241c1c16d2/netty-buffer-4.1.24.Final.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/io.netty/netty-resolver/4.1.24.Final/dbc1e5b50d31aed883ea3beeb6489e1977d0687f/netty-resolver-4.1.24.Final.jar:/Users/scott.pierce/.gradle/caches/modules-2/files-2.1/io.netty/netty-common/4.1.24.Final/7eeecd7906543214c3c1c984d275d3c6de10b99d/netty-common-4.1.24.Final.jar com.wmba.checkin.edge.EdgeApplication
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:71)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Static.call(CallerImpl.kt:80)
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:106)
	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflect_api(KCallableImpl.kt:152)
	at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:110)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.callFunctionWithInjection(ApplicationEngineEnvironmentReloading.kt:347)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.executeModuleFunction(ApplicationEngineEnvironmentReloading.kt:297)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.instantiateAndConfigureApplication(ApplicationEngineEnvironmentReloading.kt:273)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.createApplication(ApplicationEngineEnvironmentReloading.kt:126)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.start(ApplicationEngineEnvironmentReloading.kt:245)
	at io.ktor.server.netty.NettyApplicationEngine.start(NettyApplicationEngine.kt:106)
	at com.wmba.checkin.edge.EdgeApplication.main(Main.kt:45)
Caused by: io.ktor.config.ApplicationConfigurationException: Property jwt.domain not found.
	at io.ktor.config.MapApplicationConfig.property(MapApplicationConfig.kt:48)
	at com.wmba.checkin.edge.MainKt.authModule(Main.kt:50)
	... 16 more
```

**build.gradle:**
```Groovy
apply plugin: 'org.jetbrains.kotlin.multiplatform'

kotlin {
    targets {
        fromPreset(presets.jvm, 'jvm')
    }

    sourceSets {
        jvmMain {
            dependencies {
                implementation deps.kotlin.stdlib.jvm
                
                implementation project(':controller')
                api project(':model')
                
                implementation deps.ktor.server.netty
                implementation deps.ktor.server.jwt
                implementation deps.ktor.server.locations
                implementation deps.ktor.server.jackson
                implementation deps.ktor.server.jackson_jsr310
                
                implementation deps.kotlinx.coroutines.jvm
            }
        }

        jvmTest {
            dependencies {
                implementation deps.kotlin.test.jvm
                implementation deps.kotlin.test.jvm_junit
            }
        }
    }
}
```

**Folder Layout:**
<img width="352" alt="screen shot 2018-12-28 at 8 30 05 pm" src="https://user-images.githubusercontent.com/871169/50531926-6af5f700-0adf-11e9-8633-c16d17413ced.png">

I'm starting the application using an IntelliJ `Application` configuration:
<img width="1183" alt="screen shot 2018-12-28 at 8 35 46 pm" src="https://user-images.githubusercontent.com/871169/50531986-320a5200-0ae0-11e9-855f-90bb78cea42b.png">

**Comment by oleg-larshin** [comment] 2020-08-10 15:22
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-704">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment] 2021-07-07 10:10
Cannot reproduce with Ktor 1.6.1.

**Closed by Stexxe** 2021-07-07 10:10 UTC
