### ISSUE TITLE
OkHttp Websocket's incoming channel never terminates when server gracefully closes connection

### ISSUE THREAD

**Issue by matejdro** [ktorio/ktor#1262] opened 2019-08-03 08:43 UTC
**To Reproduce**
1. Get [example project](https://github.com/ktorio/ktor/files/3463541/sockets.zip)
1. Install web socket library with  `pip install aiohttp==3.5.4`
2. Run `python server.py` from the attached project folder. This starts up basic websocket server that waits for the `close` text message. When it receives, it just closes the socket gracefully and then shuts down itself. 
3. Run the main() function of the attached kotlin program

**Expected behavior**
`incoming` channel on the socket should immediately terminate since the socket is not open anymore and even worse, server is not reachable at all 

**Actual behavior**
WebSocket seems to get stuck. incoming is never finished.

Might be related to #1226

**Comment by dmitrievanthony** [comment] 2020-01-17 11:43
Hi @matejdro, thanks for reporting. I reproduced this issue and found out that the root cause is the absence of `onClosing()` handler in our web socket listener.

I prepared a fix, it currently on the review (see https://github.com/ktorio/ktor/pull/1571).

**Comment by dmitrievanthony** [comment] 2020-01-20 14:06
Hi @matejdro, I've just merged the fixes so the current master and next release will contain a fixed version.

**Closed** 2020-03-24 09:21 UTC
Labels: bug
