### ISSUE TITLE
Deserialize a list of generics inside a data class with kotlinx.serialization

### ISSUE THREAD

**Issue by lamba92** [ktorio/ktor#1783] opened 2020-04-10 11:41 UTC
Say you have:
```kotlin
@Serializable
data class PagedData<T>(val data: T, val page: Int, val totalPages: Int, val pageSize: Int)
```
Where you know for sure that `T` is a class that has the annotations `@Serializable` or a list of a type that is annotated with `@Serializable`. 

Why the serialization runtime is not able to infer what to use? It would be kind of pointless to explicitly build a serializer before every response as [such](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/runtime_usage.md#obtaining-serializers).

[Cross reference on kotlin.serialization issue board](https://github.com/Kotlin/kotlinx.serialization/issues/795)

**Comment by e5l** [comment] 2020-04-15 09:14
Hi, @lamba92. I reproduced the problem on the server, it will be fixed in the next minor release.

**Comment by lamba92** [comment] 2020-07-02 14:03
Any ETA for the next minor release?

**Comment by oleg-larshin** [comment] 2020-08-10 15:28
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-418">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by monxalo** [comment] 2020-10-21 17:24
Don't know if this is new or not but with a combination of [Plugin generated generic serializer](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#plugin-generated-generic-serializer) with [Contextual Serialization](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#contextual-serialization) this is possible.

```kotlin
@Serializable
data class Item(val entry: String)

@Serializable
data class PagedData<T>(@Contextual val data: T, val page: Int, val totalPages: Int, val pageSize: Int)

// in Application.module()

json(json = Json {
    serializersModule = SerializersModule {
        contextual(PageResponse.serializer(Item.serializer()))
    }
})
```

With these changes on your response in ktor you no longer need to serialize the object in `call.response()` method

**Comment by graycatdeveloper** [comment] 2020-10-22 14:53
@monxalo after set `contextual(PagedData.serializer(Item.serializer()))`
```
Exception in thread "main" java.lang.NoSuchMethodError: kotlinx.serialization.modules.SerializersModuleBuilder.build()Lkotlinx/serialization/modules/SerializersModule;
```
![image](https://user-images.githubusercontent.com/28825326/96889655-7de57280-148f-11eb-9ee1-498021922c8c.png)

**Comment by graycatdeveloper** [comment] 2020-10-22 15:27
@monxalo 
how do you apply your solution to an array?
```
contextual(PagedData.serializer(List<Item>.serializer())) ???
```

**Comment by monxalo** [comment] 2020-10-22 15:40
@graycatdeveloper 

If you are using a list might better define it in the `PagedData` class like so:

```kotlin
@Serializable
data class PagedData<T>(val data: List<T>, val page: Int, val totalPages: Int, val pageSize: Int)
```

**Comment by monxalo** [comment] 2020-10-22 15:44
Drawback of this approach is that `SerializationModule` only allows one serializer for each type. So you if do: 

```kotlin
contextual(PagedData.serializer(Item.serializer()))
contextual(PagedData.serializer(SubItem.serializer()))
```

It will crash at runtime with `SerializerAlreadyRegistered`.

**Comment by graycatdeveloper** [comment] 2020-10-22 15:47
@monxalo 
No! 
![image](https://user-images.githubusercontent.com/28825326/96896717-84c3b380-1496-11eb-89a6-12b6e6ac3200.png)

I am trying to create a serializer. Can you help
```
class ArrayListSerializer<T>(
    private val serializer: KSerializer<T>
) : KSerializer<ArrayList<T>> {

    override val descriptor: SerialDescriptor = serializer.descriptor

    override fun serialize(encoder: Encoder, value: ArrayList<T>) {
        encoder.encodeSerializableValue<ArrayList<T>>(ListSerializer<T>(serializer), value)
    }

    override fun deserialize(decoder: Decoder): ArrayList<T> {
        return decoder.decodeSerializableValue<List<T>>(ListSerializer<T>(serializer)).toList() as ArrayList<T>
    }
}

serializersModule = SerializersModule {
    //contextual(ApiResponse.serializer(StoreProductDao.Entity.serializer()))
    contextual(ApiResponse.serializer(ArrayListSerializer(StoreProductDao.Entity.serializer())))
}
```
But doesn't work
```
Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlinx.serialization.internal.LinkedHashMapSerializer.collectionSize, parameter $this$collectionSize
```

**Comment by graycatdeveloper** [comment] 2020-10-22 15:53
I have a class like this
![image](https://user-images.githubusercontent.com/28825326/96897656-804bca80-1497-11eb-85b3-8591b1ee81f8.png)
The data is always different. Or object or array of objects or primitive. 
I am trying to implement something that works well with Gson. But with this everything is complicated :(

**Comment by graycatdeveloper** [comment] 2020-10-22 16:02
> Drawback of this approach is that `SerializersModule` only allows one serializer for each type. So you if do:
> 
> ```kotlin
> contextual(PagedData.serializer(Item.serializer()))
> contextual(PagedData.serializer(SubItem.serializer()))
> ```
> 
> It will crash at runtime with `SerializerAlreadyRegistered`.

How can this problem be solved? Any other way? I'm already tired of looking for answers (

**Comment by monxalo** [comment] 2020-10-22 16:17
I did not find any other way, i ended up using `ApplicationCall` extensions like so:
```kotlin
suspend inline fun <reified T> ApplicationCall.respondWithPaged(message: PagedData<T>) {
    response.pipeline.execute(this, Json.encodeToString(message))
}
```

**Comment by kutoman** [comment] 2020-11-15 22:10
@monxalo an improvement in order to respond with the proper content type (JSON)
```kotlin
suspend inline fun <reified T> ApplicationCall.respondWithPaged(message: PagedData<T>) {
    val encoded = Json.encodeToString(message)
    val status = HttpStatusCode.OK
    response.pipeline.execute(this, TextContent(encoded, ContentType.Application.Json, status))
}
```

**Comment by Stexxe** [comment] 2021-07-02 11:19
Cannot reproduce with Ktor 1.6.1.

**Closed by Stexxe** 2021-07-02 11:19 UTC
Labels: feature
