### ISSUE TITLE
websocket doesn't fail gracefully on TCP FIN packet

### ISSUE THREAD

**Issue by nailgilaziev** [ktorio/ktor#1188] opened 2019-06-13 11:23 UTC
#### Project:
Ktor Version - 1.2.1
Kotlin Version - 1.3.31
Ktor Engine Used - Netty
java.runtime.version=1.8

#### Server sources
test app sources when reporting this issue
https://github.com/nailgilaziev/wsserver/tree/tcp_fin_issue
App hosted on HEROKU

#### Client sources
Crossplatform flutter: https://github.com/nailgilaziev/wsclient
[it not depends on client, soon will attach android native client src]

#### My machine
macOS Mojave 10.14.5 
java --version
openjdk 11.0.1 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)
JVM Version - , Operating System and Relevant Context

#### IDE
IntelliJ IDEA 2019.1.3 (Ultimate Edition)
Build #IU-191.7479.19, built on May 28, 2019
JRE: 1.8.0_202-release-1483-b58 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

### Feedback
Ktor App with websocket doesn't respond correctly on connection close event from client.(TCP FIN,ACK packet). No event in programmer side. Coroutine and internal mechanisms isn't stopped. This cause exception in internal pinger send mechanism, because exception throws only when the ping time comes.
<details><summary>show exception</summary>

```
Exception in thread "nettyWorkerPool-3-2" io.ktor.util.cio.ChannelWriteException: Cannot write to a channel
at io.ktor.server.netty.cio.NettyResponsePipeline.processCallFailed(NettyResponsePipeline.kt:144)
at io.ktor.server.netty.cio.NettyResponsePipeline.access$processCallFailed(NettyResponsePipeline.kt:26)
at io.ktor.server.netty.cio.NettyResponsePipeline.processJobs(NettyResponsePipeline.kt:447)
at io.ktor.server.netty.cio.NettyResponsePipeline$processJobs$1.invokeSuspend(NettyResponsePipeline.kt)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.channels.ClosedChannelException
at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
Exception in thread "nettyWorkerPool-3-2" io.ktor.util.cio.ChannelWriteException: Cannot write to a channel
at io.ktor.server.netty.cio.NettyResponsePipeline.processCallFailed(NettyResponsePipeline.kt:144)
at io.ktor.server.netty.cio.NettyResponsePipeline.access$processCallFailed(NettyResponsePipeline.kt:26)
at io.ktor.server.netty.cio.NettyResponsePipeline.processJobs(NettyResponsePipeline.kt:447)
at io.ktor.server.netty.cio.NettyResponsePipeline$processJobs$1.invokeSuspend(NettyResponsePipeline.kt)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.channels.ClosedChannelException
at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
```
</details>

#### Test Environment
Ws ktor server hosted on heroku and app logs listened
Client app connected to network that transfer packets via wireshark

#### Test Scenario
ps sorry, it's not extremely minimal, it contains unnecessary steps, but it's not so overwhelmed

1 client connects to ws server
2 client receive "welcome..." text message from ws server after 2 sec
3 client respond to server with text message just to show, that all works fine
4 client wait for ping frame from server by looking to wireshark and when it happens send to server text message again. Just for timing in server logs
5 client kill the app by swiping app from app manager (android & ios)
6 immediately in heroku logs occur row from heroku hoster that something change in url (heroku see that connection closed, but our app not)
7 after ~pingPeriod exception occurs in our ws app (my guess is internal pinger try to write to socket but it's close)

#### Guess problem 
the application does not see that the socket is closed and does not stop the internal pinger mechanism that is trying to write to the closed socket.

#### Details 
[download server.log txt](https://github.com/ktorio/ktor/files/3285521/server.log)
Logs screenshot from server with steps mark 
![Screenshot 2019-06-13 at 12 09 49](https://user-images.githubusercontent.com/2749021/59426574-2afea400-8de1-11e9-9163-70c5f8bd25ed.png)

[download client_side_dump.pcapng.zip](https://github.com/ktorio/ktor/files/3285598/client_side_dump.pcapng.zip)
wireshark dump screenshot with step marks 
![Screenshot 2019-06-13 at 13 45 01](https://user-images.githubusercontent.com/2749021/59427146-9e54e580-8de2-11e9-946f-0fb528059dec.png)

**Comment by nailgilaziev** [comment] 2019-11-22 14:03
Hi, @e5l !
Any updates on this?

**Comment by r4dx** [comment] 2019-12-20 13:23
Hi all,
@nailgilaziev - we've switched to Jetty in similar situation and it worked.
@e5l - this is how we've reproduced the issue during one of load tests (the environment was much more complex but we've nailed it to the case below):

1. Run the WebSocket server with Netty underneath - the most simplest implementation is okay (e.g. just log on each request, then close & terminate immediatelly)
1. Spam it with requests
1. Start netstat on the server instance and see how number of CLOSE_WAIT connections is growing
1. You'll run out of file descriptors after a while
1. Switch to Jetty and repeat the same steps - issue goes away.

I think socket connections are leaking on Netty implementation because some step is missing when closing socket (CLOSE_WAIT means server received the FIN but haven't responded with FIN-ACK).

**Comment by e5l** [comment] 2020-02-29 06:39
@dmitrievanthony, could you take a look? It looks like the problem you're fixing right now

**Comment by dmitrievanthony** [comment] 2020-03-26 09:21
Hi @r4dx, 

I'm investigating this issue and I reproduced it on the Netty server and Jetty server too. Are you sure that you don't have connections in the `CLOSE_WAIT` state using Jetty?

**Comment by dmitrievanthony** [comment] 2020-03-26 14:24
Well, I double-checked it on the master and it looks like we have already fixed this problem. Feel free to reopen it if you face this problem again.

**Closed by dmitrievanthony** 2020-03-26 14:24 UTC
Labels: problem
