### ISSUE TITLE
ERR_EMPTY_RESPONSE from web browser

### ISSUE THREAD

**Issue by Jaquarh** [ktorio/ktor#1072] opened 2019-04-16 11:42 UTC
### Ktor Version

1.1.3

### Ktor Engine Used(client or server and name)

ItelliJ - Gradle, Google Chrome

### JVM Version, Operating System and Relevant Context

1.8 JVM, Windows 10

### Feedback

After running the the "Hello World" Quick Start inside my Server, the server starts up fine and I receive the following output with no errors:

```koltin
[12:06:11.215 INFO ] application          | No ktor.deployment.watch patterns specified, automatic reload is not active
[12:06:11.340 INFO ] application          | Responding at http://0.0.0.0:8080
```

When I head over to `http://127.0.0.1:8080/demo` I receive `ERR_EMPTY_RESPONSE` and error code 52 with a CURL request. I get no errors at all other than the webpage returning no response.

My full code looks like this:

```koltin
override fun bindNet(server: Server, world: World) {
        val server = embeddedServer(Netty, port = 8080) {
            routing {
                get("/") {
                    call.respondText("Hello World!", ContentType.Text.Plain)
                }
                get("/demo") {
                    call.respondText("HELLO WORLD!")
                }
            }
        }
        server.start(wait = true)
    }
```

I am using Netty to bind other ports in my application which may be conflicting on the IP, I have tried to change the port to a different port but no success and also add the local address 127.0.0.1 to the host with no success.

**Comment by oleg-larshin** [comment] 2020-08-10 15:25
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-632">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment] 2021-06-28 14:09
Cannot reproduce it.

**Closed by Stexxe** 2021-06-28 14:09 UTC
