### ISSUE TITLE
socket.isClosed remains `false` after socket.close() call

### ISSUE THREAD

**Issue by revintec** [ktorio/ktor#833] opened 2018-12-26 12:23 UTC
Hi, I'm using `io.ktor:ktor-network-tls:1.0.1`[1], running JDK8 on MacOSX 10.10.5
The minimal working example to reproduce the problem is as follows:
```Kotlin
import io.ktor.network.selector.ActorSelectorManager
import io.ktor.network.sockets.aSocket
import io.ktor.network.sockets.isClosed
import io.ktor.network.sockets.openReadChannel
import io.ktor.network.sockets.openWriteChannel
import kotlinx.coroutines.Dispatchers.Unconfined
import kotlinx.coroutines.newSingleThreadContext
import kotlinx.coroutines.runBlocking

/** Created by revin(caoyunbin@baidu.com) on 2018-12-26. */
fun main(args:Array<String>)=runBlocking(Unconfined){
    val tcp=aSocket(ActorSelectorManager(newSingleThreadContext("httpIO"))).tcp()
    val socket=tcp.connect("www.baidu.com",80)
    socket.openReadChannel();socket.openWriteChannel()
    socket.close();println(socket.isClosed)
}
```
The result expected from the above code is `true` but instead I got `false`

![image](https://user-images.githubusercontent.com/8952734/50445740-a95aad00-094b-11e9-9ac6-e5a4798f6edc.png)
---
1) I can't use `io.ktor:ktor-network-tls:1.1.0`, which is the latest version as of writing. The following error shows up when trying to build the project. So I'm using an earlier version to report the problem
```
CONFIGURE FAILED in 7s
Could not find org.jetbrains.kotlinx:atomicfu:0.12.0.
Searched in the following locations:
    https://repo1.maven.org/maven2/org/jetbrains/kotlinx/atomicfu/0.12.0/atomicfu-0.12.0.pom
    https://repo1.maven.org/maven2/org/jetbrains/kotlinx/atomicfu/0.12.0/atomicfu-0.12.0.jar
Required by:
    project :jvm > io.ktor:ktor-network-tls:1.1.0
    project :jvm > io.ktor:ktor-network-tls:1.1.0 > org.jetbrains.kotlinx:kotlinx-io-jvm:0.1.2
    project :jvm > io.ktor:ktor-network-tls:1.1.0 > org.jetbrains.kotlinx:kotlinx-coroutines-io-jvm:0.1.2
    project :jvm > io.ktor:ktor-network-tls:1.1.0 > io.ktor:ktor-network:1.1.0
```
2) According to maven(https://mvnrepository.com/artifact/io.ktor/ktor-network-tls/1.1.0), ktor-network-tls relies on ktor-http-cio-native, is that intentional?

**Comment by revintec** [comment] 2018-12-28 17:54
@cy6erGn0m thanks for the info
Is there a reliable way to tell if the socket has been closed?

**Comment by cy6erGn0m** [comment] 2019-01-09 22:37
It depends on what are you trying to achieve. Why do you need to check it? 

Perhaps `isClosed` need to be deprecated to avoid confusion.

**Comment by revintec** [comment] 2019-01-10 10:13
@cy6erGn0m I'm implementing a connection pool. When there was an IOException thrown, I close the underlying socket before rethrowing, thus mark it unsuitable for recycling and also make it fall-fast -- any attempt to reuse that socket again will result in an exception to be thrown immediately.

I don't want a `isBroken` or `isSuitableForRecycling` flag since there's already one -- `isClosed`.

**Comment by oleg-larshin** [comment] 2020-08-10 15:24
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-706">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment] 2021-07-07 09:57
Cannot reproduce with Ktor 1.6.1.

**Closed by Stexxe** 2021-07-07 09:57 UTC
