### ISSUE TITLE
SerializationConverter

### ISSUE THREAD

**Issue by andreas-mausch** [ktorio/ktor#1858] opened 2020-05-12 23:16 UTC
ktor Server, kotlinx serialization

Let's say I have a `User` class, and a self-written `UserSerializer : KSerializer<User>`.

On a SerialModule I can register a contextual serializer (see SerializersModuleBuilder#contextual).

For example:

```kotlin
val myModule = SerializersModule {
  contextual(User::class, UserSerializer)
}
```

I can then pass this module to kotlinx.serialization.json.Json(), and the UserSerializer is used:

```kotlin
val json = Json(JsonConfiguration.Stable, myModule)
val stringify = json.toJson(user)
```

However, when I try to register myModule in ktor:

```kotlin
install(ContentNegotiation) { json(module = myModule) }
```

The UserSerializer is not used, and I get:

```
kotlinx.serialization.SerializationException: Can't locate argument-less serializer for class User. For generic classes, such as lists, please provide serializer explicitly.
	at kotlinx.serialization.PlatformUtilsKt.serializer(PlatformUtils.kt:21)
	at io.ktor.serialization.SerializerLookupKt.serializerForSending(SerializerLookup.kt:69)
	at io.ktor.serialization.SerializationConverter.convertForSend(SerializationConverter.kt:114)
```

It does work when I annotate my User class with `@Serializable(with = UserSerializer::class)`, but I'd rather avoid that.

From my understanding it should use my custom serializer. Do you agree?

**Comment by oleg-larshin** [comment] 2020-08-10 15:27
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-386">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment] 2021-06-15 12:22
Could you please share a complete code sample to reproduce the `SerializationException`?

**Comment by Stexxe** [comment] 2022-02-08 13:57
Can't reproduce.

**Closed by Stexxe** 2022-02-08 13:57 UTC
Labels: feature
