### ISSUE TITLE
Ktor Response readText() already received exception

### ISSUE THREAD

**Issue by q-litzler** [ktorio/ktor#1038] opened 2019-03-22 21:04 UTC
### Ktor Version

1.2.0-alpha-2

### Ktor Engine Used(client or server and name)

Client OkHttp

### JVM Version, Operating System and Relevant Context

JVM 1.8

### Feedback

readText() on a response that failed used to work, but doesn't anymore.
readBytes() still works which makes me think that this is an undesirable behaviour.

If it is the desired behaviour, I'd love the rationale behind it as well as the best way to transform the response body into a `String`.

```kotlin
val client = HttpClient(MockEngine { MockHttpResponse(it.call, HttpStatusCode.BadRequest) })

try {
    client.get<String>("www.google.com")
} catch (exception: ResponseException) {
    // io.ktor.client.call.DoubleReceiveException: Response already received: io.ktor.client.call.HttpClientCall@27ce24aa
    exception.response.readText()
    // This is fine
    String(exception.response.readBytes())
}
```

Stacktrace

```
io.ktor.client.call.DoubleReceiveException: Response already received: io.ktor.client.call.HttpClientCall@27ce24aa

	at io.ktor.client.call.HttpClientCall.receive(HttpClientCall.kt:57)
	at io.ktor.client.response.HttpResponseKt.readText(HttpResponse.kt:80)
	at io.ktor.client.response.HttpResponseKt.readText$default(HttpResponse.kt:74)
	at suite.TestSuiteMultiCluster$stuff$1.invokeSuspend(TestSuiteMultiCluster.kt:84)
```

**Comment by e5l** [comment] 2019-05-27 07:29
Fixed in `1.2.0`

**Comment by nectar1** [comment] 2019-06-13 08:24
I have the same issue in 1.2.1. 
`context.response.readText()` produce exeption `DoubleReceiveException`

**Comment by drampelt** [comment] 2019-08-02 15:14
Also having this problem on 1.2.2, `readBytes` works fine but `readText` or `receive` do not.

**Comment by opensource21** [comment] 2019-08-21 11:34
@e5l Can we reopen this issue? I have the same problem with 1.2.3

**Comment by nectar1** [comment] 2019-09-18 09:32
At 1.2.4 `readBytes()` returns only 4088 bytes.. It is critical. Please fix it

**Comment by aleks-zhigar** [comment] 2019-10-25 13:46
1.2.5 no changes

**Comment by ojaynico** [comment] 2019-12-02 23:18
Have you tried closing your connection after the request?
I modified my code as below. Called the readText() function on the request and after closed the connection. The exception seems to be gone to me with this implementation.
![Screen Shot 2019-12-03 at 2 15 01 AM](https://user-images.githubusercontent.com/10561216/70003066-1242a000-1573-11ea-92f6-e7d5a0d8e56b.png)

**Comment by gabin8** [comment] 2020-03-13 14:48
still present in 1.3.2 . Reproduced on Android client as well

**Comment by minogin** [comment] 2020-05-14 17:27
Same issue for me. When I call LinkedIn API and it returns 409 I want to parse the response to get the LinkedIn error message:
```
HttpResponseValidator {
  validateResponse { response ->
    if (response.status.value !in 200..299) {
      val error = jacksonObjectMapper().readValue<LinkedinErrorResponseDTO>(response.readText())
      throw LinkedinException(error.message)
    }
  }
}
```

`readText()` fails with `io.ktor.client.call.DoubleReceiveException: Response already received`

How should I parse the error response then?

**Comment by mobiletoly** [comment] 2020-05-30 19:22
@minogin While `response.readText()` throws an exception, you should still be able to use `response.readBytes()` call and convert it to text or deserialize to JSON response.

**Comment by oleg-larshin** [comment] 2020-08-10 15:27
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-643">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment] 2021-04-05 09:01
Fixed since `1.4.3`

**Closed by e5l** 2021-04-05 09:01 UTC
Labels: bug, triaged

**Comment by lucasleon2107** [comment] 2022-03-11 02:21
Hi everyone, I'm having this issue but when validating 200 responses with an error code

**Comment by yukai18** [comment] 2022-03-11 14:47
Same here, I'm getting already receive exception when using `it.receive()`.
I tried `json.parseToJsonElement(String(it.readBytes()))` as well but I'm getting below error
> Expected start of the object '{', but had 'EOF' instead

i tried printing `String(it.readBytes())` out, it contains a valid JSON through an online validator. not sure what went wrong >_<

I'm using version 1.6.7
