### ISSUE TITLE
When i check opened server port i got Exception (CIO)

### ISSUE THREAD

**Issue by JajaComp** [ktorio/ktor#1469] opened 2019-12-02 15:04 UTC
ktor 1.2.6
server is io.ktor:ktor-server-cio

I have exception if try check open server port over nmap

Steps:
1) Start server
2) Scan server use nmap... "nmap -P0 DEVICE_IP -p 8999"

2019-12-02 17:55:34.917 9591-9669/? E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-3
    Process: org.jajaz.wearreader, PID: 9591
    java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:419)
        at kotlinx.io.nio.ChannelsKt.read(Channels.kt:117)
        at io.ktor.network.sockets.CIOReaderKt$attachForReadingDirectImpl$1$1.invokeSuspend(CIOReader.kt:75)
        at io.ktor.network.sockets.CIOReaderKt$attachForReadingDirectImpl$1$1.invoke(Unknown Source:10)
        at kotlinx.coroutines.io.ByteBufferChannel.writeSuspendSession(ByteBufferChannel.kt:1931)
        at io.ktor.network.sockets.CIOReaderKt$attachForReadingDirectImpl$1.invokeSuspend(CIOReader.kt:65)
        at io.ktor.network.sockets.CIOReaderKt$attachForReadingDirectImpl$1.invoke(Unknown Source:10)
        at kotlinx.coroutines.io.CoroutinesKt$launchChannel$job$1.invokeSuspend(Coroutines.kt:123)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedKt.resumeCancellable(Dispatched.kt:457)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:154)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
        at kotlinx.coroutines.io.CoroutinesKt.launchChannel(Coroutines.kt:118)
        at kotlinx.coroutines.io.CoroutinesKt.writer(Coroutines.kt:76)
        at io.ktor.network.sockets.CIOReaderKt.attachForReadingDirectImpl(CIOReader.kt:61)
        at io.ktor.network.sockets.NIOSocketImpl$attachForReading$1.invoke(NIOSocket.kt:45)
        at io.ktor.network.sockets.NIOSocketImpl$attachForReading$1.invoke(NIOSocket.kt:18)
        at io.ktor.network.sockets.NIOSocketImpl.attachFor(NIOSocket.kt:80)
        at io.ktor.network.sockets.NIOSocketImpl.attachForReading(NIOSocket.kt:41)
        at io.ktor.network.sockets.SocketsKt.openReadChannel(Sockets.kt:111)
        at io.ktor.server.cio.HttpServerKt$httpServer$acceptJob$1.invokeSuspend(HttpServer.kt:109)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)

**Comment by oleg-larshin** [comment] 2020-08-10 15:30
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-517">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment] 2021-07-26 13:37
Cannot reproduce using Ktor 1.6.1.

**Closed by Stexxe** 2021-07-26 13:37 UTC
Labels: bug
