### ISSUE TITLE
Ktor rawsoket crash application after disconnecting

### ISSUE THREAD

**Issue by indrih17** [ktorio/ktor#1436] opened 2019-11-12 20:51 UTC
**Ktor-network version**
1.2.5, 1.3.0-beta-1

**Describe the bug**
After sending some request to the server, if the connection is interrupted at the time of processing, it will throw a few exceptions. Moreover, these exceptions are unchecked and are not processed in the try-catch.

**To Reproduce**
Code: https://gist.github.com/indrih17/bfdc64256b1b428acf5072a47b18a82d
Stack trace: https://gist.github.com/indrih17/7b80681751b05cf62605f7fa6b1be01b

**Comment by dmitrievanthony** [comment] 2020-03-02 09:34
Hi, @indrih17,

Firstly, the stack trace is not accessible now. If the issue is still valid, could you update it?

Secondly, I tried to reproduce the issue. Your example is not full and contains some external code, so I prepared an equal example:

```
suspend fun main() {
    try {
        withTimeout(1000) {
            aSocket(ActorSelectorManager(Dispatchers.IO))
                .tcp()
                .connect(InetSocketAddress("www.google.com", 80))
                .use { socket ->
                    val input = socket.openReadChannel()
                    val output = socket.openWriteChannel()

                    output.write("GET / HTTP/1.1\n")
                    output.write("Host: www.google.com\n")
                    output.write("\n")
                    output.flush()

                    while (true) {
                        println("Reading...")
                        input.readByte()
                        println("OK")
                    }
                }
        }
    } catch (e: Exception) {
        println("Exception [$e]")
    }
}
```

And using it I cannot reproduce the problem. Could you test this piece of code in your environment and share the result? And if it works could you provide a reproducible/executable example?

**Comment by oleg-larshin** [comment] 2020-08-10 15:30
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-529">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment] 2021-04-05 12:21
Can't reproduce with ktor 1.5.0

**Closed by e5l** 2021-04-05 12:21 UTC
Labels: bug
