### ISSUE TITLE
Content-Type in a request headers

### ISSUE THREAD

**Issue by mister11** [ktorio/ktor#1127] opened 2019-05-14 14:14 UTC
### Ktor Version
1.1.4

### Ktor Engine Used(client or server and name)
Apache

### JVM Version, Operating System and Relevant Context
1.8, macOS Mojave and Linux Mint, IDEA 2019.1.2 CE

### Feedback

I'm accessing and API that requires me to set `Content-Type` for all requests, but I'm getting `io.ktor.http.UnsafeHeaderException: Header Content-Type is controlled by the engine and cannot be set explicitly`

Current implementation:

```kotlin
val client = HttpClient(Apache) {
        install(JsonFeature) {
            serializer = GsonSerializer()
        }
        install(Logging) {
            level = LogLevel.HEADERS
        }
        defaultRequest {
            header("Content-Type", "application/vnd.api+json")
        }
    }
```

```kotlin
get("/test") {
            client.get<String>("url...") {
                headers {
                    // other headers
                }
            }
        }
```

**Comment by mister11** [comment] 2019-05-14 22:48
As an additional information, I can solve this issue using `OkHttp` with a network interceptor, but I'm curious how to do the same thing using Apache client

**Comment by e5l** [comment] 2019-05-27 08:05
Hi @mister11, thanks for the report.
We introduced `acceptContentTypes` in `JsonFeature` since `1.2.0`.  It provides you possibility to set custom `Accept` and `Content-Type` headers automatically.

Could you check and report if it solves your problem?

**Comment by mister11** [comment] 2019-05-27 15:05
Not sure if I'm doing something wrong, but this is not working:

```kotlin
val client = HttpClient(Apache) {
        install(JsonFeature) {
            serializer = GsonSerializer()
            acceptContentTypes = acceptContentTypes + listOf(ContentType.parse("application/vnd.api+json; ext=bulk"))
        }
    }
```

This just sets `Accept` header and I need `Content-Type` header for requests.

To make it more clear, here is a working version of OkHttp interceptor implementation:

```kotlin
fun provideHeadersInterceptor() = Interceptor { chain ->
    val requestBuilder = chain.request().newBuilder()
        .addHeader("Content-Type", "application/vnd.api+json")

    chain.proceed(requestBuilder.build())
}
```

```kotlin
fun provideOkHttpClient(): HttpClient = HttpClient(OkHttp) {
    engine {
        addNetworkInterceptor(provideHeadersInterceptor())
    }
}
```

**Comment by sh1nen** [comment] 2019-08-01 20:07
any solutions? I am in the same situation, but for me even interceptior does not seem to work as I would expected and I'm getting
`Exception in thread "main" java.lang.ClassCastException: class shared.model.ProductUpdateDto cannot be cast to class io.ktor.client.call.HttpClientCall (shared.model.ProductUpdateDto and io.ktor.client.call.HttpClientCall are in unnamed module of loader 'app')
`

**Comment by sannysoft** [comment] 2020-01-17 09:04
I can't use Ktor client just because I'm unable to set Content-Type. Even your examples doesn't work:
val message = client.post<HelloWorld> {
            url("http://127.0.0.1:8080/")
            contentType(ContentType.Application.Json)
            body = HelloWorld(hello = "world")
        }

**Comment by Andromedids** [comment] 2020-01-29 15:45
@sannysoft , the same doesn't work for me neither. But I found this post - and I can admit, this workaround works. But... it's a workaround :( (https://github.com/ktorio/ktor/issues/635)
```
val response = client.call(url) {
   method = HttpMethod.Post
   body = TextContent(json.writeValueAsString(userData), contentType = ContentType.Application.Json)
}.response
```

**Comment by njasm** [comment] 2020-02-04 16:30
I'm having the same problem, i cant make a post request with content-type `application/json.`
The suggested workaround #635 is not working for me.
```kotlin
val response = client.call(url) {
   method = HttpMethod.Post
   body = TextContent(json.writeValueAsString(userData), contentType = ContentType.Application.Json)
}.response
```
the POST request happens but there's no body/payload sent (?!)

this is my code:
```kotlin
HttpClient().use {
    it.call(url) {
        method = HttpMethod.Post
        body = TextContent("[{\"a\": \"b\"}]", contentType = ContentType.Application.Json)
    }.response.use {
        // ...
    }
}
```

**Comment by wfxr** [comment] 2020-03-03 09:29
Ali-OSS also encountered this problem. We need the ability to manually control any headers including `Content-Type`.

**Comment by pish11010** [comment] 2020-05-07 07:03
Any update? Zendesk Api needs `Content-Type`.
I try to use `contentType(ContentType.Application.Json)` but not working. 
```
    HttpClient: COMMON HEADERS
    HttpClient: -> User-Agent: Android/LGE - LM-G710N
    HttpClient: -> Accept: application/json
    HttpClient: -> Accept-Charset: UTF-8
    HttpClient: CONTENT HEADERS
```

**Comment by aajtodd** [comment] 2020-05-13 14:52
Why can't clients control `Content-Type` header? I'm not sure I understand why the engine "has" to. 

It's also confusing since the public API of `HttpMessageBuilder` includes a [setter](https://github.com/ktorio/ktor/blob/master/ktor-http/common/src/io/ktor/http/HttpMessageProperties.kt#L14)

Agreed we need the ability to manually control this header for a number of reasons.

**Comment by dbof10** [comment] 2020-05-27 16:09
any solutions guys?

**Comment by oleg-larshin** [comment] 2020-08-10 15:26
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-620">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by LoAlex** [comment] 2020-09-22 08:06
any solutions guys?

**Comment by Firerrd** [comment] 2021-04-26 16:07
Ran into the same problem. Found out that I was use `HttpMethod.Get` and `append("Content-Type", "application/json")` at the same time. It is total fine for `HttpMethod.Post` request. Seems like this is the reason cause the problem.
The error message is useless in the case.

**Comment by kalgecin** [comment] 2021-06-29 10:04
I'm also facing this issue. The api I'm calling REQUIRES Content-Type header in a GET request (yes I know why?), otherwise it returns error. I'm currently using another http library, but would like to move my library to Multiplatform and Ktor seems to be a good option. Is content-type blocked in Ktor GET for a reason? Are there any plans to allow it?

**Comment by dphans** [comment] 2021-07-12 10:23
I think this is a very basic limitation...
Not all endpoints accept content-type application/json, there are some endpoints used to upload documents (such as multipart formdata), how can I change the content-type in some specific cases?

**Comment by minxylynx** [comment] 2022-01-13 23:51
bump on this. I'm facing the same issue, where the get requires the content-type be specified

**Comment by adamwaite** [comment] 2022-02-03 08:02
Also blocked by this. Isn't this a normal thing to do? Why isn't it allowed...

**Comment by sud007** [comment] 2022-03-25 12:45
Oh dear, I am blocked on my PUT request on KMM Android Project! Any resolution guys?

**Comment by typfel** [comment] 2022-03-25 22:33
I've solved this problem by registering my custom content types using the ContentNegotiation plugin in fairly simple way at least for binary content. I think the ktor documentation should contain an example like this since this a fairly common use case.

example: https://github.com/wireapp/kalium/pull/324

**Comment by Kosert** [comment] 2022-07-22 06:11
On YouTrack this is marked as fixed, but I was still unable to set Content-Type header to GET request using ktor 2.0.3.
Eventually I came up with this relatively simple workaround:

```kotlin
class EmptyContentWithContentType(
    override val contentType: ContentType
) : OutgoingContent.NoContent() {

    override val contentLength: Long = 0

    override fun toString(): String = "EmptyContent(contentType='$contentType')"
}
```
And then in request builder:
```kotlin
setBody(EmptyContentWithContentType("application/definitely.not.json"))
```

**Closed** 2022-11-28 12:53 UTC
Labels: ux

**Comment by flaringapp** [comment] 2023-03-17 20:14
Still no solution?

**Comment by sud007** [comment] 2023-03-28 13:38
Yep no solution we need a `content-type = application/x-www-form-urlencoded` sadly, this has yet not worked for us!

**Comment by e5l** [comment] 2023-03-28 13:40
@rsinukov could you check if we can do something?

**Comment by flaringapp** [comment] 2023-03-28 13:52
Having conducted some investigation, I realized that ktor erases the `Content-Type` header in `ContentNegotiation` plugin, namely in `io.ktor.client.plugins.contentnegotiation.ContentNegotiation.convertRequest()`:
```
...
request.headers.remove(HttpHeaders.ContentType)
...
```
Nevertheless, this header is appended to the request when **ktor** request is being converted to the **engine** request. E.g., in _OkHttp_ it's done using `io.ktor.client.engine.mergeHeaders()` method used in file `io.ktor.client.engine.okhttp.OkHttpEngine.kt`, method `convertToOkHttpRequest()`.
The most interesting part is inside `io.ktor.client.engine.mergeHeaders()` method. Indeed, it tries to resolve content type and length, and append `Content-Type` header:
```
...
val type = content.contentType?.toString()
    ?: content.headers[HttpHeaders.ContentType]
    ?: requestHeaders[HttpHeaders.ContentType]

val length = content.contentLength?.toString()
    ?: content.headers[HttpHeaders.ContentLength]
    ?: requestHeaders[HttpHeaders.ContentLength]

type?.let { block(HttpHeaders.ContentType, it) }
length?.let { block(HttpHeaders.ContentLength, it) }
```

In the end, I believe `Content-Type` header shouldn't be erased in the first place, but at least it'll be nice to provide explanation stated directly in content negotiation plugin documentation.

**Comment by rsinukov** [comment] 2023-03-28 14:50
@sud007 Can you please elaborate on what doesn't work? This test passes:
```

    @Test
    fun testEmptyBodyWithContentTypeAndGet() = testSuspend {
        val client = HttpClient(MockEngine) {
            engine {
                addHandler { request ->
                    assertEquals("application/protobuf", request.headers[HttpHeaders.ContentType])
                    respond("OK")
                }
            }
        }

        client.get("/") {
            header(HttpHeaders.ContentType, ContentType.Application.ProtoBuf)
        }
    }
```

**Comment by flaringapp** [comment] 2023-03-29 18:42
@rsinukov Please try adding content negotiation plugin
```
install(ContentNegotiation) {
    json()
}
```

And sending post request with any `@Serializable` object:
```
client.post("/") {
    header(HttpHeaders.ContentType, ContentType.Application.Json)
    setBody(
        SomeJonObject("Hello", "Ktor")
    )
}
```

The test you've provided will fail

**Comment by rsinukov** [comment] 2023-03-30 11:05
@flaringapp But isn't it only relevant for `MockEngine`, because it doesn't merge headers? In the real request `Content-Type` header will be present.

**Comment by kalgecin** [comment] 2023-03-30 11:13
real question is what is the reason of removing the header if it was set by the user?

**Comment by flaringapp** [comment] 2023-03-30 11:14
@rsinukov Yes, you are right. In the real request in will be present. I just don't want to say that the issue is explicitly with the `MockEngine`. 
Going back to content negotiation plugin which erases `Content-Type` header: it operates on `HttpRequestPipeline.Transform` phase, and the real request is being transformed and executed on `HttpRequestPipeline.Send` phase. Meaning, anywhere in between these two phases we won't be able to access the header no matter what engine we use.

**Comment by flaringapp** [comment] 2023-03-30 11:16
Another question is why to completely delegate header appending to an engine. Is it feasible to keep the header by default, and let any engine override/remove it if necessary?

**Comment by rsinukov** [comment] 2023-03-30 14:29
@flaringapp
> Meaning, anywhere in between these two phases we won't be able to access the header no matter what engine we use.

You are able to access it through `content.contentType`, the same way as `mergeHeaders` does.

@kalgecin @flaringapp Can you elaborate on what problems it causes?

**Comment by flaringapp** [comment] 2023-03-30 14:32
@rsinukov in my case, a test with MockEngine that verifies Content-Type header was failing. As you stated.

**Comment by rsinukov** [comment] 2023-03-30 19:55
@kalgecin Can you show me a reproducer where the client doesn't send header to a server, please? I fail to create one.

**Comment by rellikt** [comment] 2023-09-09 13:53
@rsinukov 
```

        private val client = HttpClient(CIO)
        
        client
        .post("http://0.0.0.0:8080/doSomethink") {
//without body it works
//            setBody(ByteArray(0))
            contentType(ContentType.Application.ProtoBuf)
        }
        .also { println("${it.call.request.headers}") }
```

**Comment by grassehh** [comment] 2024-04-04 08:36
@rsinukov it works but I am questioning a behavior. 
Why does the [defaultTransformers](https://github.com/ktorio/ktor/blob/e789b015bd5169505df1c59ced0d2690026af523/ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/DefaultTransform.kt#L55) remove the `Content-Type` header? 
This is relatively quite unintuitive as this can lead to issues like this one: [https://github.com/zalando/logbook/issues/1627](https://github.com/zalando/logbook/issues/1627) where the Monitor plugin expects to have such header in the `context.headers` instead of `OutgoingContent`.

**Comment by jafaircl** [comment] 2024-08-05 21:42
So there is no way to send the (extremely common) `Content-Type` header no matter how we attempt to append it without using a third party library to intercept requests? That seems... not great
