### ISSUE TITLE
Multipart form file send writeFully fails with "java.net.ProtocolException: unexpected end of stream"

### ISSUE THREAD

**Issue by theromis** [ktorio/ktor#1829] opened 2020-04-27 20:32 UTC
```
ktorVersion = 1.3.2
implementation "io.ktor:ktor-client-core:$ktorVersion"
implementation "io.ktor:ktor-client-okhttp:$ktorVersion"
implementation "com.squareup.okhttp3:logging-interceptor:4.5.0"
```

sending file in form, code below works (file fitting the `buff`)
```
        val retMessage =  client.request<Message> {
            method = HttpMethod.Patch
            url("https://myhost/rest/v1/message/image-upload/aa")

            header("X-Client-Locale", settings.locale)
            header("Authorization", "Bearer ${settings.jwt}")
            userAgent(settings.userAgent)

            body = MultiPartFormDataContent(
                formData {
                    val filename = reader.open()
                    val buff = ByteArray(102400)
                    val sz = reader.read(buff)
                    if (sz > 0) {
                        append(
                            "picture",
                            filename,
                            ContentType.parse(reader.contentType),
                            size = reader.size
                        ) {
                            writeFully(buff, 0, sz)
                        }
                    }
                    reader.close()
                }
            )
        }
```
when I move `reader.read` into `BytePacketBuilder`
```
val buff = ByteArray(102400)
                    append(
                        "picture",
                        filename,
                        ContentType.parse(reader.contentType),
                        size = reader.size
                    ) {
                        val sz = reader.read(buff)
                        if (sz > 0) {
                            writeFully(buff, 0, sz)
                        }
                    }
```

getting:
```
    ---3e33c4c9bf0fe2451394e9a-21e8f6434bf41b1b-3454ee4d-35548052-6fcbb83a7a--
    --> END PATCH (26800-byte body)
D/OkHttp: <-- HTTP FAILED: java.net.ProtocolException: unexpected end of stream
E/LonjeShared: Rest.request(/rest/v1/message/image-upload/aa): java.net.ProtocolException: unexpected end of stream
```

same issue happens with `InputProvider`
```
                    val filename = reader.open()
                    val inp = reader.input
                    if (inp != null) {
                        append(
                            "picture",
                            InputProvider(reader.size) {
                                return@InputProvider inp
                            }
                        )
                    }
```
it shows appropriate HTTP PATCH content in OkHttp log

please help me find an issue, I hope I'm doing something wrong. But it can be a serious `ktor` issue.

PS: on serverside I'm getting:
```
ERRO multipart: NextPart: stream error: stream ID 7; CANCEL
INFO Mon, 27 Apr 2020 21:00:03 UTC 76.77.185.144   400 PATCH https://myhost/rest/v1/message/image-upload/aa HTTP/2.0   33B in 1.351711ms
```
what shows HTTP2 stream exception

**Comment by hikkidev** [comment] 2020-04-28 05:31
Try something like this:
```kotlin
val context: Context = ...
val uri: Uri = ...
val size = uri.getFileSize()

client.put<SomeResponse> {
        apiUrl("image/upload")
        body = MultiPartFormDataContent(
            formData {
                appendInput(
                    key = "upload-image",
                    headers = Headers.build {
                        append(HttpHeaders.ContentLength, "$size")
                        append(HttpHeaders.ContentDisposition, "filename=image.jpg")
                    },
                    size = size
                ) {
                    buildPacket {
                        context.contentResolver.openInputStream(uri)!!.use {
                            writeFully(it.readBytes())
                        }
                    }
                }
            }
        )
```

![изображение](https://user-images.githubusercontent.com/52655010/80450528-e70a8400-894b-11ea-8ba6-96558ff61420.png)

**Comment by theromis** [comment] 2020-04-28 06:00
@hikkidev thank you for quick reply, I definitely can't use JVM specific `openInputStream` because this is `multiplatofrm` project this is why I'm using `reader.open/read/close`
but I'm doing exactly what you recommend adding `reader` code
```
actual class StreamReader {
    var uri: Uri? = null
    var cr: ContentResolver? = null
    var stream: BufferedInputStream? = null
    private var _type: String = ""
    private var _size: Long = 0
    private var _input: Input? = null

    actual val contentType: String
        get() = _type

    actual val size: Long
        get() = _size

    actual val input: Input?
        get() = _input

    actual fun readAll(): ByteArray? {
        return _input?.readBytes()
    }

    actual fun read(buff: ByteArray): Int {
        val size = stream?.read(buff)
        if (size != null)
            return size
        return -1
    }

    actual fun open(): String {
        var path = "filename"
        val address = uri ?: return path
        val inStreamReader = cr?.openInputStream(address)
        _input = inStreamReader?.asInput()
        _type = cr?.getType(address) ?: ""
        stream = inStreamReader?.buffered()
        _size = stream?.available()?.toLong() ?: 0

        return path
    }
}
```

and this code get's this error but with bufferedstream,

does the `it.readBytes()` reading whole file? what if I'm uploading terabyte size image?

**Comment by hikkidev** [comment] 2020-05-04 05:56
Yeah it.readBytes() reading whole file.
> what if I'm uploading terabyte size image? - OutOfMemory. If you want to upload large files, you need to be sure that your server supports streaming(partial transfers).

https://ktor.io/servers/uploads.html

**Comment by theromis** [comment] 2020-05-04 13:58
@hikkidev server supports it, problem in client only.

**Comment by oleg-larshin** [comment] 2020-08-10 15:31
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-402">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by evertsmits** [comment] 2021-01-07 22:02
@theromis Did you happen to find a solution for this?

**Comment by theromis** [comment] 2021-01-08 01:07
@evertsmits my current solution just read whole file before sending and just feed byte array in `send` function

**Comment by charleston10** [comment] 2021-01-13 20:39
@theromis can you set an example?
I've same the problem

**Comment by Stexxe** [comment] 2021-07-02 11:05
@theromis could you please tell me where the `reader` variable is defined?

**Comment by Stexxe** [comment] 2021-07-02 11:33
Cannot reproduce with Ktor 1.6.1.

**Closed by Stexxe** 2021-07-02 11:33 UTC
Labels: bug
