### ISSUE TITLE
javax.net.ssl.SSLHandshakeException is not referencing my code

### ISSUE THREAD

**Issue by gabin8** [ktorio/ktor#1872] opened 2020-05-15 14:13 UTC
**Ktor Version and Engine Used (client or server and name)**
version: 1.3.2
client: io.ktor:ktor-client-android

**Describe the bug**
```
2020-05-15 16:47:44.384 20692-20692/com.testproject.android W/System.err: javax.net.ssl.SSLHandshakeException: SSL handshake aborted: ssl=0x7c275ca088: I/O error during system call, Connection reset by peer
2020-05-15 16:47:44.385 20692-20692/com.testproject.android W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
2020-05-15 16:47:44.385 20692-20692/com.testproject.android W/System.err:     at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:375)
2020-05-15 16:47:44.385 20692-20692/com.testproject.android W/System.err:     at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:224)
2020-05-15 16:47:44.385 20692-20692/com.testproject.android W/System.err:     at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:192)
2020-05-15 16:47:44.385 20692-20692/com.testproject.android W/System.err:     at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
2020-05-15 16:47:44.385 20692-20692/com.testproject.android W/System.err:     at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
2020-05-15 16:47:44.385 20692-20692/com.testproject.android W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
2020-05-15 16:47:44.385 20692-20692/com.testproject.android W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
2020-05-15 16:47:44.386 20692-20692/com.testproject.android W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
2020-05-15 16:47:44.386 20692-20692/com.testproject.android W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
2020-05-15 16:47:44.386 20692-20692/com.testproject.android W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
2020-05-15 16:47:44.386 20692-20692/com.testproject.android W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
2020-05-15 16:47:44.386 20692-20692/com.testproject.android W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
2020-05-15 16:47:44.386 20692-20692/com.testproject.android W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
2020-05-15 16:47:44.386 20692-20692/com.testproject.android W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:26)
2020-05-15 16:47:44.386 20692-20692/com.testproject.android W/System.err:     at io.ktor.client.engine.android.AndroidURLConnectionUtilsKt.timeoutAwareConnect(AndroidURLConnectionUtils.kt:51)
2020-05-15 16:47:44.386 20692-20692/com.testproject.android W/System.err:     at io.ktor.client.engine.android.AndroidClientEngine.execute(AndroidClientEngine.kt:83)
2020-05-15 16:47:44.387 20692-20692/com.testproject.android W/System.err:     at io.ktor.client.engine.HttpClientEngine$executeWithinCallContext$2.invokeSuspend(HttpClientEngine.kt:83)
2020-05-15 16:47:44.387 20692-20692/com.testproject.android W/System.err:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2020-05-15 16:47:44.387 20692-20692/com.testproject.android W/System.err:     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
2020-05-15 16:47:44.387 20692-20692/com.testproject.android W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
2020-05-15 16:47:44.387 20692-20692/com.testproject.android W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
2020-05-15 16:47:44.387 20692-20692/com.testproject.android W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
2020-05-15 16:47:44.387 20692-20692/com.testproject.android W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**To Reproduce**
Probably request a server that can perform ssl handshake abort

**Expected behavior**
Point to the line of code that caused an exception

**Comment by oleg-larshin** [comment] 2020-08-10 15:32
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-375">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment] 2021-07-28 11:49
If this issue is still relevant, please share a sample code snippet to reproduce it.

**Comment by Stexxe** [comment] 2022-02-08 13:52
Can't reproduce.

**Closed by Stexxe** 2022-02-08 13:52 UTC
Labels: bug
