### ISSUE TITLE
CachingHeaders puts duplicate headers

### ISSUE THREAD

**Issue by TWiStErRob** [ktorio/ktor#1687] opened 2020-02-29 13:03 UTC
**Ktor Version and Engine Used (client or server and name)**
CachingHeaders 1.3.1

**Describe the bug**
The documentation for `io.ktor.features.CachingHeaders.optionsProviders` explicitly states "use first non null caching options". This is not true, and can be broken with a really simple setup.

**To Reproduce**
1. Run this app:
```kotlin
import io.ktor.application.call
import io.ktor.application.install
import io.ktor.features.CachingHeaders
import io.ktor.http.content.CachingOptions
import io.ktor.http.content.caching
import io.ktor.response.respondText
import io.ktor.routing.get
import io.ktor.routing.routing
import io.ktor.server.engine.embeddedServer
import io.ktor.server.netty.Netty
import java.time.ZonedDateTime

fun main() {
	embeddedServer(Netty, 8080) {
		install(CachingHeaders) {
			options { it.caching }
		}
		routing {
			get("/") {
				call.respondText("Hello") {
					caching = CachingOptions(
						expires = ZonedDateTime.now().plusSeconds(60)
					)
				}
			}
		}
	}.start(wait = true)
}
```
2. Invoke using browser/curl/etc.
3. Observe headers returned by the server

**Expected behavior**
```
HTTP/1.1 200 OK
Expires: Sat, 29 Feb 2020 12:49:30 GMT
Content-Length: 5
Content-Type: text/plain; charset=UTF-8
Connection: keep-alive
```

**Actual behavior**
```
HTTP/1.1 200 OK
Expires: Sat, 29 Feb 2020 12:49:30 GMT
Expires: Sat, 29 Feb 2020 12:49:30 GMT
Content-Length: 5
Content-Type: text/plain; charset=UTF-8
Connection: keep-alive
```

**Notes**
 1. Putting more `options { it.caching }` into `install` will duplicate the header even more.
 1. The [documentation](https://ktor.io/servers/features/caching-headers.html) says:
    > The basic feature is installed just like many others, but for it to do something, you **have to** define options blocks

    so it's very easy to end up with this, it should rather mention that the default behavior without any setup (`install(CachingHeaders);`) is:
    ```kotlin
    install(CachingHeaders) {
        options { it.caching }
    }
    ```
 1. it looks to me that to satisfy "use first non null caching options" we need:
    ```kotlin
    fun optionsFor(content: OutgoingContent): CachingOptions? =
        optionsProviders.asSequence().mapNotNull { it(content) }.firstOrNull()
    ```

**Comment by TWiStErRob** [comment] 2020-02-29 13:09
Hmm...
> If you have several options, that would append several Cache-Control headers per each matching option. -- [docs](https://github.com/ktorio/ktorio.github.io/blame/master/servers/features/caching-headers.md#L54)

**Comment by TWiStErRob** [comment] 2020-02-29 13:10
Hmm...
> If you have several options, that would append several Cache-Control headers per each matching option. -- [docs](https://github.com/ktorio/ktorio.github.io/blame/master/servers/features/caching-headers.md#L54)
/cc @soywiz

**Comment by oleg-larshin** [comment] 2020-08-10 15:31
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-458">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment] 2021-07-05 10:35
Cannot reproduce with Ktor 1.6.1.

**Closed by Stexxe** 2021-07-05 10:35 UTC
Labels: bug
