### ISSUE TITLE
MalformedInputException: Input length = 1, when uploading an image multipart

### ISSUE THREAD

**Issue by filbabic** [ktorio/ktor#1766] opened 2020-04-01 18:25 UTC
**Ktor Version and Engine Used (client or server and name)**
Ktor 1.3.2, Kotlin 1.3.70, Netty server, ContentNegotiation, Jackson parser, Exposed.

I simply used the Ktor project generator for Gradle, and checked a few boxes for modules as mentioned above. After which I managed to connect a database & a few endpoints, but my core endpoint for uploading images doesn't work.

**Describe the bug**
When trying to upload a simple image using Retrofit & Multipart support in Android, I get a MalformedInputException on my server.

Retrofit/Android code:

```
@Multipart
@POST("/api/upload")
suspend fun uploadImages(@Part("image") imageFile: RequestBody): UploadResponse
```

Upload code:

```
val requestBody: RequestBody = MultipartBody.Builder()
        .setType(MultipartBody.FORM)
        .addFormDataPart("title", "Image Upload")
        .addFormDataPart(
            "image", // part name
            file.path.split("/").last(), // file name
            file.asRequestBody("image/jpg".toMediaType()) // Content-Type: image/jpg
        )
        .build()

    return apiService.uploadImages(requestBody)
```

Using the new way of creating RequestBody objects in OkHttp. I followed the documentation to receive the multipart data, and I've formed a MalformedInputException.

**To Reproduce**
1. Use Retrofit to Upload an image to a Ktor server.
2. call `receiveMultipart()` to receive MP on the Ktor side.
3. See error

**Expected behavior**
Multipart data should be received correctly.

Stack trace:
```
[nioEventLoopGroup-4-1] ERROR Application - Unhandled: POST - /api/upload
io.ktor.utils.io.charsets.MalformedInputException: Input length = 1
	at io.ktor.utils.io.charsets.CharsetJVMKt.throwExceptionWrapped(CharsetJVM.kt:323)
	at io.ktor.utils.io.charsets.CharsetJVMKt.decodeImplSlow(CharsetJVM.kt:289)
	at io.ktor.utils.io.charsets.CharsetJVMKt.decodeExactBytes(CharsetJVM.kt:254)
	at io.ktor.utils.io.core.StringsKt.readTextExactBytes(Strings.kt:293)
	at io.ktor.utils.io.core.StringsKt.readTextExactBytes$default(Strings.kt:292)
	at io.ktor.utils.io.core.AbstractInput.readText(AbstractInput.kt:468)
	at io.ktor.utils.io.core.AbstractInput.readText$default(AbstractInput.kt:465)
	at io.ktor.http.cio.CIOMultipartDataBase.partToData(CIOMultipartData.kt:127)
	at io.ktor.http.cio.CIOMultipartDataBase$partToData$1.invokeSuspend(CIOMultipartData.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by fluidsonic** [comment] 2020-04-02 12:57
Same for me with different stack trace (logging feature).
In my case disabling the logging feature is a suitable workaround.

```stacktrace
io.ktor.utils.io.charsets.MalformedInputException: Input length = 1
    at io.ktor.utils.io.charsets.CharsetJVMKt.throwExceptionWrapped(CharsetJVM.kt:323)
    at io.ktor.utils.io.charsets.CharsetJVMKt.decode(CharsetJVM.kt:199)
    at io.ktor.utils.io.charsets.EncodingKt.decode(Encoding.kt:101)
    at io.ktor.utils.io.core.StringsKt.readText(Strings.kt:251)
    at io.ktor.utils.io.core.StringsKt.readText$default(Strings.kt:250)
    at io.ktor.client.features.logging.Logging$logRequestBody$2$1.invokeSuspend(Logging.kt:111)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
    at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:69)
    at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:184)
    at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:108)
    at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:307)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:317)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:249)
    at io.ktor.utils.io.ByteBufferChannel.resumeWriteOp(ByteBufferChannel.kt:2210)
    at io.ktor.utils.io.ByteBufferChannel.bytesRead(ByteBufferChannel.kt:930)
    at io.ktor.utils.io.ByteBufferChannel.readAsMuchAsPossible(ByteBufferChannel.kt:544)
    at io.ktor.utils.io.ByteBufferChannel.readAvailable$suspendImpl(ByteBufferChannel.kt:606)
    at io.ktor.utils.io.ByteBufferChannel.readAvailable(Unknown Source:0)
    at io.ktor.utils.io.jvm.javaio.WritingKt.copyTo(Writing.kt:21)
    at io.ktor.utils.io.jvm.javaio.WritingKt.copyTo$default(Writing.kt:12)
    at io.ktor.client.engine.android.AndroidClientEngineKt.writeTo(AndroidClientEngine.kt:112)
    at io.ktor.client.engine.android.AndroidClientEngine.execute(AndroidClientEngine.kt:79)
    at io.ktor.client.engine.HttpClientEngine$executeWithinCallContext$2.invokeSuspend(HttpClientEngine.kt:83)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)```

**Comment by namig-accenture** [comment] 2020-05-02 15:13
I can confirm that disabling logging feature is a workaround for this issue.

**Comment by namig-accenture** [comment] 2020-05-04 10:46
Also in Ktor 1.3.1 logging does not work properly, for example, I am not able to see post request body in the logs, it only shows these lines.

```
METHOD: HttpMethod(value=POST)
COMMON HEADERS
-> User-Agent: android
-> Accept: application/json
-> Accept-Charset: UTF-8
CONTENT HEADERS
BODY Content-Type: application/json
BODY Content-Type: application/json; charset=UTF-8
BODY START
-
BODY END
```

But for Ktor 1.2.6 I used to be seeing them.

**Comment by oleg-larshin** [comment] 2020-08-10 15:31
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-425">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by rsinukov** [comment] 2020-09-14 13:04
fixed in https://github.com/ktorio/ktor/pull/2064

**Closed by rsinukov** 2020-09-14 13:04 UTC
Labels: bug

**Comment by AlexShniperson-INO** [comment] 2021-12-02 13:53
error i still here

kotlin version: 1.6.0
ktor version: 1.6.4

try to upload image and got that
```
io.ktor.utils.io.charsets.MalformedInputException: Input length = 1
	at io.ktor.utils.io.charsets.CharsetJVMKt.throwExceptionWrapped(CharsetJVM.kt:325)
	at io.ktor.utils.io.charsets.CharsetJVMKt.decodeImplSlow(CharsetJVM.kt:289)
	at io.ktor.utils.io.charsets.CharsetJVMKt.decodeExactBytes(CharsetJVM.kt:254)
	at io.ktor.utils.io.core.StringsKt.readTextExactBytes(Strings.kt:301)
	at io.ktor.utils.io.core.StringsKt.readTextExactBytes$default(Strings.kt:300)
	at io.ktor.utils.io.core.AbstractInput.readText(AbstractInput.kt:479)
	at io.ktor.utils.io.core.AbstractInput.readText$default(AbstractInput.kt:476)
	at io.ktor.http.cio.CIOMultipartDataBase.partToData(CIOMultipartDataBase.kt:77)
	at io.ktor.http.cio.CIOMultipartDataBase.access$partToData(CIOMultipartDataBase.kt:21)
	at io.ktor.http.cio.CIOMultipartDataBase$partToData$1.invokeSuspend(CIOMultipartDataBase.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.ktor.server.netty.EventLoopGroupProxy$Companion.create$lambda-1$lambda-0(NettyApplicationEngine.kt:251)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

the request with omitted binary data
```
POST http://192.168.0.101:8443/media HTTP/1.1
user-agent: Dart/2.14 (dart:io)
content-type: multipart/form-data; boundary=--dio-boundary-2352542239
accept-encoding: gzip
content-length: 371972
host: 192.168.0.101:8443
```

**Comment by Stexxe** [comment] 2021-12-03 08:21
@AlexShniperson-INO I cannot reproduce it by sending an image to a server. Could you please share your code for a server?

**Comment by AlexShniperson-INO** [comment] 2021-12-03 08:25
In the course of researching the problem, I saw that if the boundary body does not contain the name of the `filename`, then this error occurs.
after adding unique filename to boundary body the problem went away

**Comment by ulrikandersen** [comment] 2023-11-27 10:32
> In the course of researching the problem, I saw that if the boundary body does not contain the name of the `filename`, then this error occurs. after adding unique filename to boundary body the problem went away

Were you able to get to to bottom of this issue? If I try to upload a file without a `filename` in the boundary ktor fails with 

```
io.ktor.utils.io.charsets.MalformedInputException: Input length = 1
	at io.ktor.utils.io.charsets.CharsetJVMKt.throwExceptionWrapped(CharsetJVM.kt:370)
	at io.ktor.utils.io.charsets.CharsetJVMKt.decodeImplSlow(CharsetJVM.kt:334)
	at io.ktor.utils.io.charsets.CharsetJVMKt.decodeExactBytes(CharsetJVM.kt:297)
	at io.ktor.utils.io.core.StringsKt.readTextExactBytes(Strings.kt:297)
	at io.ktor.utils.io.core.StringsKt.readTextExactBytes$default(Strings.kt:296)
	at io.ktor.utils.io.core.Input.readText(Input.kt:414)
	at io.ktor.utils.io.core.Input.readText$default(Input.kt:411)
	at io.ktor.http.cio.CIOMultipartDataBase.partToData(CIOMultipartDataBase.kt:81)
	at io.ktor.http.cio.CIOMultipartDataBase.access$partToData(CIOMultipartDataBase.kt:25)
	at io.ktor.http.cio.CIOMultipartDataBase$partToData$1.invokeSuspend(CIOMultipartDataBase.kt)
```

**Comment by ulrikandersen** [comment] 2023-11-27 10:33
> In the course of researching the problem, I saw that if the boundary body does not contain the name of the `filename`, then this error occurs. after adding unique filename to boundary body the problem went away

@AlexShniperson-INO Were you able to get to to bottom of this issue? If I try to upload a file without a `filename` in the boundary ktor fails with 

```
io.ktor.utils.io.charsets.MalformedInputException: Input length = 1
	at io.ktor.utils.io.charsets.CharsetJVMKt.throwExceptionWrapped(CharsetJVM.kt:370)
	at io.ktor.utils.io.charsets.CharsetJVMKt.decodeImplSlow(CharsetJVM.kt:334)
	at io.ktor.utils.io.charsets.CharsetJVMKt.decodeExactBytes(CharsetJVM.kt:297)
	at io.ktor.utils.io.core.StringsKt.readTextExactBytes(Strings.kt:297)
	at io.ktor.utils.io.core.StringsKt.readTextExactBytes$default(Strings.kt:296)
	at io.ktor.utils.io.core.Input.readText(Input.kt:414)
	at io.ktor.utils.io.core.Input.readText$default(Input.kt:411)
	at io.ktor.http.cio.CIOMultipartDataBase.partToData(CIOMultipartDataBase.kt:81)
	at io.ktor.http.cio.CIOMultipartDataBase.access$partToData(CIOMultipartDataBase.kt:25)
	at io.ktor.http.cio.CIOMultipartDataBase$partToData$1.invokeSuspend(CIOMultipartDataBase.kt)
```

**Comment by gandrewstone** [comment] 2024-08-19 20:41
Replicated the missing filename problem.  On the client side, using ktor you MUST NOT use the default of no headers.  Instead use something like:
val response: HttpResponse = client.submitFormWithBinaryData(
        url = dest,
        formData = formData {
            append("file", yourFile.readBytes(), Headers.build {
                append(HttpHeaders.ContentType, ContentType.Application.OctetStream)
                append(HttpHeaders.ContentDisposition, """filename="${yourFile.name}"""")
            })
        })
