### ISSUE TITLE
Android client requires packagingOptions

### ISSUE THREAD

**Issue by baruchn** [ktorio/ktor#1461] opened 2019-11-26 15:05 UTC
**Ktor Version and Engine Used (client or server and name)**
Android client, version 1.2.4

**Describe the bug**
When using the android client in a library inside an Android application, the build fails with the error:
>More than one file was found with OS independent path 'META-INF/kotlinx-io.kotlin_module'

The workaround is to add
``` groovy
packagingOptions {
    exclude 'META-INF/*.kotlin_module'
 }
```
to the applications `build.gradle`. 

The problem is that I'm the distributor of the library and not the applications and trying to migrate from Retrofit to Ktor. Therefore, I can't ask the applications to do that.

**Comment by e5l** [comment] 2019-11-27 06:48
Hi @baruchn, thanks for the report. We'll fix it in the next minor release.

**Comment by axelfontaine** [comment] 2020-05-11 20:54
This is still present in `1.3.2-1.4-M1-2` for
- `ktor-client-core`, `ktor-client-json`, `ktor-http`, `ktor-http-cio`, `ktor-io` and `ktor-utils`
- `kotlinx-serialization-runtime`

**Comment by oleg-larshin** [comment] 2020-08-10 15:30
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-519">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment] 2021-07-20 09:59
Cannot reproduce with Ktor 1.6.1.

**Closed by Stexxe** 2021-07-20 09:59 UTC
Labels: bug
