### ISSUE TITLE
Nonce.kt leaks a coroutine

### ISSUE THREAD

**Issue by kimble** [ktorio/ktor#1291] opened 2019-08-20 19:44 UTC
**Ktor Version and Engine Used (client or server and name)** 
OkHttp Client 1.2.3

**Describe the bug**
I expect resources to be cleaned up after calling close on the client instance, but Nonce.kt leaves a suspended coroutine in the global scope: https://github.com/ktorio/ktor/blob/master/ktor-utils/jvm/src/io/ktor/util/Nonce.kt#L29

**To Reproduce**
I attached a test to a stackoverflow question
https://stackoverflow.com/questions/57580222/how-can-i-make-sure-all-kotlin-coroutines-created-by-a-ktor-websocket-client-are

**Expected behavior**
I expect resources to be freed after calling close on the client.

**Comment by cy6erGn0m** [comment] 2019-08-23 13:31
This is by design: a single nonce generation coroutine is always running in the global scope (usually it is sleeping) and no resources actually wasted including threads except for a small amount of memory.

**Comment by cy6erGn0m** [comment] 2019-08-23 13:32
So is it a problem or just a questionable decision?

**Comment by kimble** [comment] 2019-08-26 07:47
I'd say more of a questionable decision then a real problem, but it makes it harder to detect real coroutine leaks (especially if more libraries start doing this). I would not like libraries leaving threads around after being "closed" and feel the same about coroutines.

**Comment by oleg-larshin** [comment] 2020-08-10 15:25
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-571">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2022-06-20 12:14 UTC
Labels: design
