### ISSUE TITLE
Multiplatform: Ktor can't find file from distributions folder in a child module

### ISSUE THREAD

**Issue by ivakub** [ktorio/ktor#1698] opened 2020-03-03 09:42 UTC
Initial report — https://youtrack.jetbrains.com/issue/KT-36659

**Ktor Version and Engine Used (client or server and name)**
Ktor 1.3.1 JS/JVM (Netty)

**Describe the bug**
In a multiplatform project, Ktor can't find a resource file (`module-name/build/distributions/module-name.js`) in a child module.

**To Reproduce**
1. Open the attached file
2. Run `./gradlew run`
3. Ktor can't find the resource file

**Expected behavior**
Ktor should find the file and process it.

**Screenshots**
<img width="636" alt="Screen Shot 2020-03-03 at 12 34 31 PM" src="https://user-images.githubusercontent.com/24901892/75762278-75e39180-5d4b-11ea-8496-25940f8a4593.png">
[KT-36659.zip](https://github.com/ktorio/ktor/files/4280405/KT-36659.zip)

**Comment by oleg-larshin** [comment] 2020-08-10 15:31
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-451">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment] 2021-07-27 10:13
Cannot reproduce it using Ktor 1.6.1 and multiplatform plugin 1.5.20 with a following line:
```groovy
from(new File(jsBrowserWebpack.entry.name, jsBrowserWebpack.outputPath))
```
replaced with:

```groovy
from("$buildDir/distributions/second.js")
```

Working as expected sample project is attached in [KTOR-451](https://youtrack.jetbrains.com/issue/KTOR-451).

**Closed by Stexxe** 2021-07-27 10:13 UTC
Labels: bug
