### ISSUE TITLE
You-kube sample doesn't refresh list of videos after uploading

### ISSUE THREAD

**Issue by orangy** [ktorio/ktor#22] opened 2016-05-26 14:14 UTC

**Comment by cy6erGn0m** [comment] 2016-05-26 17:07
The reason is wrong cache control header specified for the page.

**Comment by soywiz** [comment] 2018-03-09 15:02
I suppose I should update the one in the ktor-samples repo, right? ( https://github.com/ktorio/ktor-samples/tree/master/app/youkube )

**Comment by orangy** [comment] 2018-03-09 15:04
@soywiz yes, please, after @elizarov finishes with migration.

**Comment by soywiz** [comment] 2018-04-12 11:14
Can't reproduce it, at least on master it seems to work fine. I have just tried it, and the only relevant header for this is ETag. That changes on content changes:

```
Connection: keep-alive
Content-Encoding: gzip
Content-Type: text/html; charset=UTF-8
Date: Thu, 12 Apr 2018 11:08:10 GMT
ETag: 1027539052-3506402
Server: ktor-server-core/0.9.2-alpha-5 ktor-server-core/0.9.2-alpha-5
transfer-encoding: chunked
```

I upload a video, then press the WATCH links that points to `/`, and the new video appears there without any issues. Both with the logged session or with an incognito session just by refreshing the page.

**Comment by soywiz** [comment] 2018-09-02 22:02
I'm closing this, since can't reproduce. Probably this is something that was fixed at some point :)

**Closed by soywiz** 2018-09-02 22:02 UTC
Labels: bug
