### ISSUE TITLE
java.net.BindException: Address already in use (Windows 10)

### ISSUE THREAD

**Issue by bitkid** [ktorio/ktor#1309] opened 2019-08-31 13:13 UTC
**Ktor Version and Engine Used (client or server and name)**
1.2.3

**Describe the bug**
I get this exception when i try to do a lot of request concurrently. Same code works with the Apache Client.

**To Reproduce**
```
HttpClient(CIO).use { client ->
            metadata.keys.forEach {
                val meta = jackson.writeValueAsString(metadata.getValue(it))
                client.call {
                    url("$baseUrl/api/matrices/create")
                    method = HttpMethod.Post
                    body = TextContent("""{"name": "$it", "repository":"GE_VIENNA", "rows":10, "metaData": $meta}""", ContentType.Application.Json)
                }.close()
            }
        }
```

**Expected behavior**
No exception

**Comment by cy6erGn0m** [comment] 2019-09-02 12:43
@e5l  We actually have similar failures on Windows TC agents, see `AndroidMultithreadedTest.numberTest`: https://teamcity.jetbrains.com/viewLog.html?buildId=2510065&buildTypeId=KotlinTools_Ktor_BuildGradleWindows

**Comment by Dimezis** [comment] 2020-05-17 12:09
I'm also experiencing this on Ktor 1.3.2 with CIO.
Hard to say exactly how many concurrent requests I have, I was just writing a dumb load test for a game server, generating ~5000 HttpClients, and pretty fast I ran into this error.
Each HttpClient makes requests sequentially though.

Let me know if you need any other info

**Comment by oleg-larshin** [comment] 2020-08-10 15:30
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-563">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment] 2021-07-29 16:00
Cannot reproduce using Ktor 1.6.1 and CIO engine under Windows 10.

**Closed by Stexxe** 2021-07-29 16:00 UTC
Labels: bug

**Comment by gigitalz** [comment] 2021-08-10 17:56
This is still happening in 1.6.2.
To reproduce it's not too difficult, you have to generate a lot of requests concurrently and then it'll happen quite often, althogh not always, even if the http requests are not generated in the same process.
There could be a completely different application making loads of http requests and you would get this error sporadically also on other apps using CIO.

To give you the idea of how many requests I am generating, these are my current stats:

HTTP Req/s = 264.0
Req RTT: 1535.0ms
Traffic: 1.52 Mb/s

HTTP Req/s = 241.0
Req RTT: 1274.0ms
Traffic: 1.22 Mb/s

Sporadically I get:

`java.net.BindException: Address already in use: no further information`

It is indeed strange though that one app conflicts with another one to bind the random client ports, the OS should take care of this and make sure they don't overlap. Is CIO trying to bind to specific ports? Seems to be one of those low probability cases but if you push hard enough it will happen, rest assured.

Unless the error is totally misleading us.

**Comment by gigitalz** [comment] 2021-08-10 18:01
> I'm also experiencing this on Ktor 1.3.2 with CIO.
> Hard to say exactly how many concurrent requests I have, I was just writing a dumb load test for a game server, generating ~5000 HttpClients, and pretty fast I ran into this error.
> Each HttpClient makes requests sequentially though.
> With Apache client I get:
> `java.net.SocketException: No buffer space available (maximum connections reached?): connect`
> So the error could be totally legit, just needs a better error message?
> 
> Let me know if you need any other info.
> 
> **EDIT:**
> Actually, I got the same error using a single HttpClient but with multiple concurrent requests

I don't think the error you get from Apache is related, I also use Apache for 500+ concurrent req/s, never a single issue.

**Comment by plinyar** [comment] 2023-05-08 00:20
Facing the same error in ktor 2.3.0 with Jetty on server
