### ISSUE TITLE
'followRedirects' not respected on iOS

### ISSUE THREAD

**Issue by appmagnetics** [ktorio/ktor#1167] opened 2019-06-03 11:12 UTC
### Ktor Version

1.1.5

### Ktor Engine Used(client or server and name)

Default

### JVM Version, Operating System and Relevant Context

Android JDK 1.7,    
ext.kotlin_version = '1.3.30'
 ext.coroutines_version = '1.2.0'
Kotlin MPP (Android, iOS) 

### Feedback

I'm configuring my client in Multiplatform common code to _not_ using redirects.

`    protected val client: HttpClient = HttpClient(){
        followRedirects = false
    }`

It works when run on Android/JVM, but I can see in logs that calling same code on iOS causes redirects following (I'm getting HTTP Code 200 and final HTML page instead of 302)

As stated by Leonid Stashevsky in Kotlin Slack channel, this is the issue which should be handled by Ktor.

**Comment by soundbites** [comment] 2019-07-25 13:16
We're also running into this issue, is this still on the roadmap?

**Comment by e5l** [comment] 2019-07-25 13:20
Yep. The issue is fixed here: https://github.com/ktorio/ktor/commit/d4d247f2f9b6298e057e9549ff63182665d9915a

**Comment by e5l** [comment] 2019-08-15 08:57
Merged.

**Closed by e5l** 2019-08-15 08:57 UTC
Labels: bug
