### ISSUE TITLE
OkHttp WebSocket terminates with a delay

### ISSUE THREAD

**Issue by matejdro** [ktorio/ktor#1226] opened 2019-07-07 19:05 UTC
**Ktor Version and Engine Used (client or server and name)**
```
implementation "io.ktor:ktor-client-core:1.2.2"
implementation "io.ktor:ktor-client-websockets:1.2.2"
implementation "io.ktor:ktor-client-okhttp:1.2.2"
```

**Describe the bug**
Calling `WebSocketSession.terminate()` on OkHttp WebSocket session takes a while to terminate. Even worse, OkHttp keeps non-daemon thread alive for this, which prevents program from stopping in that period. 

**To Reproduce**
Run following code:

```kotlin
fun main() = runBlocking {
    val client = HttpClient {
        install(WebSockets)
    }

    val session = client.webSocketSession {
        url("ws://some-websocket-API")
    }

    session.terminate()
}
```

**Expected behavior**

Documentation states that 

> Initiate connection termination **immediately.** Termination may complete asynchronously.

So I assume that above example code should execute and then terminate immediately, but it takes a while to do so.

**Comment by cy6erGn0m** [comment] 2019-07-08 14:03
A ktor client should be closed explicitly. I've added a test and the session termination works properly with OkHttp. However, I discovered that it doesn't with CIO. Thanks for pointing me out :)

**Comment by matejdro** [comment] 2019-07-08 17:02
You mean just adding `client.close()` call? It does not make any difference to me, connection still dangles for  quite some time.

**Comment by cy6erGn0m** [comment] 2019-07-08 17:53
`client.close` is REQUIRED. I am not able to reproduce it. What server is it?

**Comment by matejdro** [comment] 2019-07-08 18:12
It is [Home Assistant's Websocket API](https://github.com/home-assistant/home-assistant/tree/dev/homeassistant/components/websocket_api) which appears to use [python's aiohttp](https://aiohttp.readthedocs.io/en/v0.18.2/client_websockets.html) under the hood.

**Comment by matejdro** [comment] 2019-07-08 18:12
Regardless of the server, shouldn't closing the client forcefully terminate all connections?

**Comment by oleg-larshin** [comment] 2020-08-10 15:30
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-593">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment] 2021-07-23 09:27
Cannot reproduce this problem with `session.cancel()` (`WebSocketSession.terminate` is deprecated) call followed by `client.close()` using Ktor 1.6.1.

**Closed by Stexxe** 2021-07-23 09:27 UTC
Labels: bug
