### ISSUE TITLE
CIO probably leaking file descriptors on linux

### ISSUE THREAD

**Issue by Melodeiro** [ktorio/ktor#1986] opened 2020-07-01 00:45 UTC
**Ktor Version and Engine Used (client or server and name)**
1.3.2, client, CIO

**Describe the bug**
Every 3 seconds im creating and closing `HttpClient(CIO)`, and getting leaked file descriptors (+200 every 3 seconds). When i changing to Apache engine, everything is fine.

**To Reproduce**
1. Write the following
```kotlin
class SomeService() : CoroutineScope {
    private val supervisorJob = SupervisorJob()
    override val coroutineContext by lazy {
        supervisorJob + Executors.newSingleThreadExecutor().asCoroutineDispatcher()
    }

    fun start() {
        launch {
            while(isActive) {
                HttpClient(CIO).use {
                    try {
                        val result = it.post<String>("http://xxx.xxx.xxx.xxx:xxxx/path") {
                            body = "sometext"
                        }
                    } catch (t: Throwable) { }
                }
                delay(3000)
            }
        }
    }
}

fun Application.main() {
    SomeService().start()
}
```
2. Run with SomeService().start()
3. Wait 10-20 seconds for descriptors leaking

**Comment by oleg-larshin** [comment] 2020-08-10 15:32
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-318">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by lfmunoz** [comment] 2020-11-07 00:00
Tried your application, I don't see the problem.  

When I click perform GC, it collects everything.

When I look at file descriptors it is constant 


![no_leak](https://user-images.githubusercontent.com/1304440/98425153-b40f1e80-2059-11eb-8c2d-bcf42f02bbf4.png)

➜ ls -la /proc/29988/fd | wc -l
85
➜ ls -la /proc/29988/fd | wc -l
85
➜ ls -la /proc/29988/fd | wc -l
85
➜ ls -la /proc/29988/fd | wc -l
85
➜ ls -la /proc/29988/fd | wc -l
85
➜ ls -la /proc/29988/fd | wc -l
85

```
ktor_version = 1.3.2
   implementation("io.ktor:ktor-client-cio:$ktor_version")
```



```

import io.ktor.client.*
import io.ktor.client.engine.cio.*
import io.ktor.client.request.*
import kotlinx.coroutines.*
import java.util.concurrent.Executors

class SomeService() : CoroutineScope {
    private val supervisorJob = SupervisorJob()
    override val coroutineContext by lazy {
        supervisorJob + Executors.newSingleThreadExecutor().asCoroutineDispatcher()
    }

    fun start() {
        launch {
            while(isActive) {
                HttpClient(CIO).use {
                    try {
                        val result = it.post<String>("http://xxx.xxx.xxx.xxx:xxxx/path") {
                            body = "sometext"
                        }
                    } catch (t: Throwable) { }
                }
                delay(3000)
            }
        }
    }
}

fun main() {

    SomeService().start()

}
```

**Comment by Melodeiro** [comment] 2020-11-07 00:18
> Tried your application, I don't see the problem.

Maybe server is also important, since i started it from Application, as you can see from code. I also have

```implementation("io.ktor:ktor-server-netty:$ktorVersion")```

**Comment by e5l** [comment] 2021-04-05 15:57
Can't reproduce

**Closed by e5l** 2021-04-05 15:57 UTC
Labels: bug
