### ISSUE TITLE
0 sized binary respose

### ISSUE THREAD

**Issue by cromefire** [ktorio/ktor#1777] opened 2020-04-08 15:09 UTC
**Ktor Version and Engine Used (client or server and name)**

version: 1.3.2
type: server
engine: netty
modules:
 - routing
 - static

**Describe the bug**
When hitting a directory (`/` in this case) you get this:
![image](https://user-images.githubusercontent.com/26320625/78800226-7f4fc180-79bb-11ea-9cd0-1be122b7d19d.png)

**To Reproduce**
https://github.com/cromefire/ktor-repro

Run `:runShadow` - it doesn't work
Run `:run` - it works

**Expected behavior**
It serves a 404

**Screenshots**
See above

**Comment by dmitrievanthony** [comment] 2020-04-10 07:58
Hi @cromefire, thanks for reporting.

I found the root cause of this issue and prepared the fix (#1782). It's on the review so far.

**Comment by dmitrievanthony** [comment] 2020-04-14 11:25
I merged correspondent PR, so the fix will be available in the next release. Feel free to reopen the issue in case of any additional questions.

**Closed by dmitrievanthony** 2020-04-14 11:25 UTC
Labels: bug

**Comment by cromefire** [comment] 2020-04-14 11:26
How often do you release normally?

**Comment by dmitrievanthony** [comment] 2020-04-14 11:31
> How often do you release normally?

@e5l, can you let us know the expected release date?
