### ISSUE TITLE
Getting crash "Trust anchor for certification path not found"

### ISSUE THREAD

**Issue by gabin8** [ktorio/ktor#1029] opened 2019-03-19 21:43 UTC
### Ktor Version
1.1.3
### Ktor Engine Used(client or server and name)
ktor-client-cio
### JVM Version, Operating System and Relevant Context
Android 4.2.2
### Feedback
Getting crash that is not passed to the higher level. I think its related to TLS support on old android versions.
```
03-19 23:36:30.471 26546-26546/com.example.android.kotlincoroutines E/AndroidRuntime: FATAL EXCEPTION: main
    java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkTrusted(TrustManagerImpl.java)
        at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java)
        at io.ktor.network.tls.TLSClientHandshake.handleCertificatesAndKeys(TLSClientHandshake.kt:207)
        at io.ktor.network.tls.TLSClientHandshake.negotiate(TLSClientHandshake.kt:146)
        at io.ktor.network.tls.TLSClientHandshake$negotiate$1.invokeSuspend(TLSClientHandshake.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
```

**Comment by e5l** [comment] 2019-03-20 09:10
Hi @gabin8, thanks for the report.
It looks like the exception from the `CIO` engine. Could you provide your dependency section and `HttpClient` construction?

**Comment by gabin8** [comment] 2019-03-20 09:21
Sorry, my apologizes. The client is `CIO`

**Comment by e5l** [comment] 2019-03-20 09:22
`CIO + tls` works only with jdk8 for now.

**Comment by gabin8** [comment] 2019-03-20 09:27
okhttp crashes with following exception:
```
03-20 11:26:25.181 14921-14921/? E/AndroidRuntime: FATAL EXCEPTION: main
    javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java)
        at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:318)
        at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:282)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:167)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java)
        at java.lang.Thread.run(Thread.java)```

**Comment by e5l** [comment] 2019-03-20 09:28
Could you provide the request sample?

**Comment by gabin8** [comment] 2019-03-20 09:40
sure
```
private val client by lazy { HttpClient()}

val htmlContent = client.get<String>("https://kinokrad.co")
```

**Comment by oleg-larshin** [comment] 2020-08-10 15:24
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-647">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment] 2021-07-21 09:11
I cannot reproduce it.

**Closed by Stexxe** 2021-07-21 09:11 UTC
