### ISSUE TITLE
Exception in thread "nettyWorkerPool-3-2" java.lang.ClassCastException: kotlin.Unit cannot be cast to java.base/java.lang.Boolean

### ISSUE THREAD

**Issue by sanity** [ktorio/ktor#461] opened 2018-07-04 22:59 UTC
I'm getting this exception with ktor 0.9.3

```
Exception in thread "nettyWorkerPool-3-2" java.lang.ClassCastException: kotlin.Unit cannot be cast to java.base/java.lang.Boolean
	at io.ktor.server.netty.cio.NettyResponsePipeline$processBodyFlusher$2.doResume(NettyResponsePipeline.kt:269)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:41)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:41)
	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:162)
	at kotlinx.coroutines.experimental.AbstractContinuation.run(AbstractContinuation.kt:31)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by cy6erGn0m** [comment] 2018-08-30 09:06
Looks like something wrong with the classpath. Some incompatible binaries may be...

**Comment by oleg-larshin** [comment] 2020-08-10 15:23
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-771">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment] 2021-03-30 08:44
Can't reproduce

**Closed by e5l** 2021-03-30 08:44 UTC
