### ISSUE TITLE
Clarify behavior of get<Unit> with appropriate error/warning message

### ISSUE THREAD

**Issue by Ribesg** [ktorio/ktor#1735] opened 2020-03-18 10:57 UTC
**Ktor Version and Engine Used (client or server and name)**
1.3.2, client, `ResponseObserver`

**Describe the bug**
When using `ResponseObserver` and a request like `get<Unit>(…)` to an endpoint which actually returns a body (which we would want to ignore in this case), the `response` passed to the observer has a cancelled `content: ByteReadChannel`, preventing logging of the body which was returned.

**Expected behavior**
It would be nice if there was a way to indicate why the body isn't available in this case to the developer

**Comment by dmitrievanthony** [comment] 2020-03-23 08:15
Hi @Ribesg, 

Could you clarify the exact reproducer of the issue and the desired behaviour?

I used the following code to reproduce:

```
suspend fun main() {
    HttpClient(CIO) {
        install(Logging) {
            logger = Logger.DEFAULT
            level = LogLevel.ALL
        }
    }.use { client ->
        val res = client.get<Unit>("http://localhost:4567/test")
        println("Result: $res")
    }
}
```

And got the following output:

```
[main] INFO io.ktor.client.HttpClient - REQUEST: http://localhost:4567/test
[main] INFO io.ktor.client.HttpClient - METHOD: HttpMethod(value=GET)
[main] INFO io.ktor.client.HttpClient - COMMON HEADERS
[main] INFO io.ktor.client.HttpClient - -> Accept-Charset: UTF-8
[main] INFO io.ktor.client.HttpClient - -> Accept: */*
[main] INFO io.ktor.client.HttpClient - CONTENT HEADERS
[main] INFO io.ktor.client.HttpClient - BODY Content-Type: null
[main] INFO io.ktor.client.HttpClient - BODY START
[main] INFO io.ktor.client.HttpClient - 
[main] INFO io.ktor.client.HttpClient - BODY END
[DefaultDispatcher-worker-1] INFO io.ktor.client.HttpClient - BODY Content-Type: text/plain; charset=UTF-8
[DefaultDispatcher-worker-1] INFO io.ktor.client.HttpClient - BODY START
[DefaultDispatcher-worker-1] INFO io.ktor.client.HttpClient - Hello, world!
[DefaultDispatcher-worker-1] INFO io.ktor.client.HttpClient - BODY END
[ktor-cio-dispatcher-worker-1] INFO io.ktor.client.HttpClient - RESPONSE: 200 OK
[ktor-cio-dispatcher-worker-1] INFO io.ktor.client.HttpClient - METHOD: HttpMethod(value=GET)
[ktor-cio-dispatcher-worker-1] INFO io.ktor.client.HttpClient - FROM: http://localhost:4567/test
[ktor-cio-dispatcher-worker-1] INFO io.ktor.client.HttpClient - COMMON HEADERS
[ktor-cio-dispatcher-worker-1] INFO io.ktor.client.HttpClient - -> Content-Length: 13
[ktor-cio-dispatcher-worker-1] INFO io.ktor.client.HttpClient - -> Content-Type: text/plain; charset=UTF-8
Result: kotlin.Unit
```

So, what's your idea?

**Comment by Ribesg** [comment] 2020-03-23 08:30
This was on iOS using the default engine (which I don't think is CIO) and using `ResponseObserver` in a custom logging feature

**Comment by oleg-larshin** [comment] 2020-08-10 15:31
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-439">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment] 2021-06-24 10:15
@Ribesg could you please share a code snippet to reproduce this problem?

**Comment by Stexxe** [comment] 2022-02-08 14:08
Can't reproduce.

**Closed by Stexxe** 2022-02-08 14:08 UTC
Labels: bug
