### ISSUE TITLE
ldap any credentials get authenticated

### ISSUE THREAD

**Issue by RuneHanssens** [ktorio/ktor#1634] opened 2020-02-11 10:00 UTC
**Ktor Version and Engine Used (client or server and name)**
1.3.0, server, ktor-auth-ldap

**Describe the bug**
When using the default ldap authentication any combination of a password and username gets successfully authenticated. 
I use the following code as mentioned in the documentation: 
```kotlin
basic("authName") {
        realm = "realm"
        validate { credential ->
            ldapAuthenticate(credential, "...", "...")
        }
    }
```

I used the following to work around this problem: 
```kotlin 
basic("ldap") {
            validate { credential ->
                val ldapUrl = "..."
                val configure: (MutableMap<String, Any?>) -> Unit = { env ->
                    env["java.naming.security.principal"] = credential.name
                    env["java.naming.security.credentials"] = credential.password
                    env["java.naming.security.authentication"] = "simple"
                }
                ldapAuthenticate(credential, ldapUrl, configure) {
                    UserIdPrincipal(credential.name)
                }
            }
        }
```

**Comment by oleg-larshin** [comment] 2020-08-10 15:27
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-476">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment] 2021-07-29 11:01
I cannot reproduce it using Ktor 1.6.1 with the following code:
```kt
embeddedServer(Netty, 8080) {
    install(Authentication) {
        basic("authActiveDirectory") {
            validate { cred ->
                realm = "IdapRealm"
                ldapAuthenticate(cred, "ldap://ldap.forumsys.com:389", "cn=read-only-admin,dc=example,dc=com")
            }
        }
    }

    routing {
        authenticate("authActiveDirectory") {
            get("/au") {
                call.respondText(call.authentication.principal<UserIdPrincipal>()?.name ?: "null")
            }
        }
    }
}.start(wait = t
```

**Closed by Stexxe** 2021-07-29 11:01 UTC
Labels: Server, bug
