### ISSUE TITLE
parse Authorization  Header error with Regex token68Pattern

### ISSUE THREAD

**Issue by liuboflyon145** [ktorio/ktor#1076] opened 2019-04-17 04:42 UTC
### Ktor Version 
- 1.1.2

### Ktor Engine Used(client or server and name)
- ktor-auth-jwt 
### JVM Version, Operating System and Relevant Context
- JDK 10  , Operating System by Windows
![image](https://user-images.githubusercontent.com/6317950/56261419-8415c880-610d-11e9-830d-cf76055ac043.png)
- error messages
```
java.lang.IllegalArgumentException: invalid authScheme value: it should be token
	at io.ktor.http.auth.HttpAuthHeader.<init>(HttpAuthHeader.kt:45)
	at io.ktor.http.auth.HttpAuthHeader.<init>(HttpAuthHeader.kt:43)
	at io.ktor.http.auth.HttpAuthHeader$Parameterized.<init>(HttpAuthHeader.kt:80)
	at io.ktor.http.auth.HttpAuthHeader$Parameterized.<init>(HttpAuthHeader.kt:85)
	at io.ktor.http.auth.HttpAuthHeader$Parameterized.<init>(HttpAuthHeader.kt:84)
	at io.ktor.http.auth.HttpAuthHeaderKt.parseAuthorizationHeader(HttpAuthHeader.kt:32)
	at io.ktor.auth.HeadersKt.parseAuthorizationHeader(Headers.kt:10)

```
### Feedback

eyJhbxxxxxJ9.ZXxxxxxxxzaEhiWGRyUVdReVoyxxxx1OdmJTSjk=.EEHi3SGJ1JNygT44nDbEGUtfR5lHl9hai/vFdRfZFxxxxxxgyNW/A==

![image](https://user-images.githubusercontent.com/6317950/56261521-dfe05180-610d-11e9-80a5-c76f75bff962.png)

![image](https://user-images.githubusercontent.com/6317950/56261508-d525bc80-610d-11e9-8d7b-11a1960e72d4.png)

![image](https://user-images.githubusercontent.com/6317950/56261530-f1295e00-610d-11e9-8a3a-a82b0fc4bba7.png)
because the '=.' does not pass regex matches

**Comment by e5l** [comment] 2019-04-17 07:01
Hi @liuboflyon145, thanks for the report and investigation.
It's obviously a bug and will be fixed in next release.

**Comment by asiazhang** [comment] 2019-04-18 02:26
Will release a patch version soon?Some of our users are blocked by this bug。

**Comment by cy6erGn0m** [comment] 2019-04-22 09:32
Please note that according to the specification `=` is not allowed for token68 content

**Comment by cy6erGn0m** [comment] 2019-04-22 09:35
From [RFC 7235 sec 2.1](https://tools.ietf.org/html/rfc7235#section-2.1)

```
     auth-scheme    = token

     auth-param     = token BWS "=" BWS ( token / quoted-string )

     token68        = 1*( ALPHA / DIGIT /
                          "-" / "." / "_" / "~" / "+" / "/" ) *"="
```

**Comment by asiazhang** [comment] 2019-04-23 02:14
> From [RFC 7235 sec 2.1](https://tools.ietf.org/html/rfc7235#section-2.1)
> 
> ```
>      auth-scheme    = token
> 
>      auth-param     = token BWS "=" BWS ( token / quoted-string )
> 
>      token68        = 1*( ALPHA / DIGIT /
>                           "-" / "." / "_" / "~" / "+" / "/" ) *"="
> ```

But accroding to doc:

```
The token68 syntax allows the 66 unreserved URI characters
   ([RFC3986]), plus a few others, so that it can hold a base64,
   base64url (URL and filename safe alphabet), base32, or base16 (hex)
   encoding, with or without padding, but excluding whitespace
   ([RFC4648]).
```

It can hold a base64 string, and a base64 string may have `=` padding.

**Comment by asiazhang** [comment] 2019-04-23 02:23
The JWT token contains 3 parts.The payload part may have a `=` padding inside the whole token.

**Comment by asiazhang** [comment] 2019-04-24 06:26
OK, I found the [JWT RFC doc](https://www.rfc-editor.org/rfc/rfc7515.txt): 

```
   Base64url Encoding
      Base64 encoding using the URL- and filename-safe character set
      defined in Section 5 of RFC 4648 [RFC4648], with all trailing '='
      characters omitted (as permitted by Section 3.2) and without the
      inclusion of any line breaks, whitespace, or other additional
      characters.  Note that the base64url encoding of the empty octet
      sequence is the empty string.  (See Appendix C for notes on
      implementing base64url encoding without padding.)
```

According to the RFC, padding is not allowed in payload base64.So the problem is maybe in our JWT library.This question can be closed now. @liuboflyon145 @cy6erGn0m @e5l

**Closed** 2019-04-24 06:30 UTC
Labels: bug
