### ISSUE TITLE
Kotlin ios misses last 2 bytes

### ISSUE THREAD

**Issue by flaquir4** [ktorio/ktor#920] opened 2019-02-01 11:26 UTC
### Ktor Version
1.1.2
### Ktor Engine Used(client or server and name)
io.ktor:ktor-client-ios
### JVM Version, Operating System and Relevant Context
kotlin 1.3.20
### Feedback
I have a network call which randomly drops 2 bytes it only happens sometimes.
In ktor/jvm works fine.
Do you know what the issue can be?

**Comment by e5l** [comment] 2019-02-01 11:47
Hi @flaquir4, thanks for the report.
I can't reproduce, could you provide the request URL?

**Comment by flaquir4** [comment] 2019-02-01 12:04
Unfortunately I can't it's a private API.

**Comment by e5l** [comment] 2019-02-05 12:16
Fixed by https://github.com/Kotlin/kotlinx-io/pull/36

**Comment by cy6erGn0m** [comment] 2019-02-21 16:57
Fixed in 1.1.3.

**Closed by cy6erGn0m** 2019-02-21 16:57 UTC
Labels: bug
