### ISSUE TITLE
Accessing custom config does not work with "-config" option

### ISSUE THREAD

**Issue by peterbecker** [ktorio/ktor#1161] opened 2019-05-30 06:02 UTC
### Ktor Version
1.1.3

### Ktor Engine Used(client or server and name)
Netty

### JVM Version, Operating System and Relevant Context
OpenJDK 1.8.0 / Linux

### Feedback
The documentation around config at https://ktor.io/servers/configuration.html#accessing-config does not seem to work if we use the "-config" command line option.

We generally like to use environment specific configuration files, managed separate from the code base. Using the `-config` command line option to provide a file seems appropriate, but we are encountering issues with any code relying on this style of config access:

```
val config = HoconApplicationConfig(ConfigFactory.load())
```

This seems not to include the configuration provided on the command line. The documentation also mentions configuration access via something like this:

```
val port: String = application.environment.config
    .propertyOrNull("ktor.deployment.port")?.getString()
    ?: "80"
```

This approach fails for us in that we haven't worked out where that initial `application` object would come from.

Preferably we would like to see something where a typed configuration is broken into parts and passed around, such as done in [Dropwizard](https://www.dropwizard.io/1.3.12/docs/manual/core.html#configuration) or [Config4k](https://github.com/config4k/config4k). For example: if we have more than one database connection, a `DatabaseConfig` type that appears more than once helps keeping the code clean and fails fast, vs. something that is based on prefixes and assumptions.

**Comment by cy6erGn0m** [comment] 2019-05-30 06:16
Configs provided via command line and from file are merged here:
https://github.com/ktorio/ktor/blob/master/ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/CommandLine.kt#L30

Note that it doesn't work with `embeddedServer(engine) { ... }` function

**Comment by peterbecker** [comment] 2019-05-30 23:22
If I understand this right, the question becomes: how do I access the `combinedConfig` in https://github.com/ktorio/ktor/blob/master/ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/CommandLine.kt#L33 -- I think none of the documented approaches to getting config seems to hit that version.

**Comment by peterbecker** [comment] 2019-06-10 04:02
Coming back to this I found a workaround, albeit a pretty ugly one. I start the application like this:

```
@KtorExperimentalAPI
var config: ApplicationConfig = MapApplicationConfig()

@KtorExperimentalAPI
fun main(args: Array<String>) {
    config = commandLineEnvironment(args).config
    io.ktor.server.netty.EngineMain.main(args)
}

@KtorExperimentalAPI
@Suppress("UNUSED_PARAMETER") // referenced in test code
@kotlin.jvm.JvmOverloads
fun Application.module(testing: Boolean = false) {
    DatabaseFactory.init(config.config("db"))
...
```

And in the DatabaseFactory I treat the config as a `lateinit var` field.

It's ugly, and it will probably fall apart again once I need to talk to two databases, but it will bring me over the line.

**Comment by oleg-larshin** [comment] 2020-08-10 15:25
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-611">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment] 2021-07-15 10:57
I cannot reproduce it with Ktor 1.6.1. If I have `mykey = ewqe` in my config and pass `-config` flag with its path as a value then the following code prints value of a key as expected:
```kt
fun Application.module(testing: Boolean = false) {
    routing {
        get("/") {
            println(environment.config.property("mykey").getString())
        }
    }
}
```

**Closed by Stexxe** 2021-07-15 10:57 UTC
Labels: design
