### ISSUE TITLE
Ktor-client, memory leak

### ISSUE THREAD

**Issue by Fuud** [ktorio/ktor#1223] opened 2019-07-05 08:52 UTC
### Ktor Version
1.2.2

### Ktor Engine Used(client or server and name)
ktor-client-apache

### JVM Version, Operating System and Relevant Context
jvm: 1.8.1_171, OS: Windows

### Feedback

Run this code:

```
import io.ktor.client.HttpClient
import io.ktor.client.engine.apache.Apache
import io.ktor.client.request.get
import kotlinx.coroutines.async
import kotlinx.coroutines.runBlocking
import org.junit.Test

class MemoryLeak {

    @Test
    fun `memory leak`() {
        runBlocking {
            async {
                while (true) {
                    httpClient.get<String>("http://google.com")
                }
            }
        }
    }

    private val httpClient = HttpClient(Apache) {
        engine {
            customizeClient {
                setMaxConnPerRoute(1000)
                setMaxConnTotal(1000)
            }
        }
    }
}
```

Then invoke following script:
```
jmap -histo:live <pid> |  grep Invoke
```
you will get something like:
```
  14:          1307          52280  kotlinx.coroutines.InvokeOnCancelling
  ...
```

Wait for a while, invoke script again, you will find that instance count are continuously increasing.

**Comment by cy6erGn0m** [comment] 2019-07-06 18:26
We already have something fixed about notification registration. Perhaps, it wasn't the the only problem

**Comment by haneev** [comment] 2020-01-03 14:29
I have also an issue here with sort the same problem. I found the issue because our requests were quite large, so we saw that memory was increasing when the application was running longer. The following location causes this.

commonMain/io/ktor/client/engine/HttpClientEngine.kt
```
fun install(client: HttpClient) {
        client.sendPipeline.intercept(HttpSendPipeline.Engine) { content ->
            val requestData = HttpRequestBuilder().apply {
                takeFrom(context)
                body = content
            }.build()

            validateHeaders(requestData)

            val responseData = execute(requestData)
            val call = HttpClientCall(client, requestData, responseData)

            responseData.callContext[Job]!!.invokeOnCompletion { cause ->
                @Suppress("UNCHECKED_CAST")
                val childContext = requestData.executionContext as CompletableJob
                if (cause == null) childContext.complete() else childContext.completeExceptionally(cause)
            }

            proceedWith(call)
        }
    }
```

The issue (in our case) is that `CompletionHandler` of `invokeOnCompletion` is never called. In our case `requestData` is quite large, but because the completion handler is never called the `requestData` keeps in memory until the `CompletionHandler` is called. 

When I look in the code i see that all post/get calls are a child of a supervisor job. That supervisor job is never stopped, which is fine. I would expect that a child-job is completed when the request has ended. But, i am unable to find why the completionHandler is not called. My search continues.

**Comment by oleg-larshin** [comment] 2020-08-10 15:26
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-596">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by peya-lucas-milotich** [comment] 2021-07-01 01:19
``Hello!

I my case I see old gen memory keeps increasing until I get OOO.

```kotlin
               requestBuilder = request(method = HttpMethod.Get, uri = uri, params = params, headers = headers)
                val response: HttpResponse = client.get(requestBuilder)
                val bytes = response.receive<ByteArray>()
    protected fun request(
        method: HttpMethod,
        uri: String,
        params: Map<String, Any>,
        body: Any? = null,
        headers: Map<String, Any>
    ): HttpRequestBuilder {
        val requestBuilder = HttpRequestBuilder()
        requestBuilder.url("${config.host}$uri")
        requestBuilder.method = method
        if (body != null) {
            requestBuilder.body = body
        }

        params.entries.forEach { entry -> requestBuilder.parameter(entry.key, entry.value.toString()) }
        headers.entries.forEach { entry -> requestBuilder.header(entry.key, entry.value.toString()) }

        return requestBuilder
    }
```

**Comment by Stexxe** [comment] 2021-07-23 09:10
I cannot reproduce a memory leak by @Fuud's test using Ktor 1.6.1. @peya-lucas-milotich could you please share a complete code snippet?

**Closed** 2023-12-06 12:15 UTC
Labels: perf problem
