### ISSUE TITLE
Gracefully handle WebSocket Forced Closed/Disconnects on Client Side

### ISSUE THREAD

**Issue by blackmo18** [ktorio/ktor#1335] opened 2019-09-11 02:49 UTC
**Ktor Version and Engine Used (client or server and name)**
ktor server version: 1.2.4

**Describe the bug**
Im running a websocket in server and checks if the clients is reachable and whenever is not. I cant find anyway to gracefully catch/handle exception even trying try/catch block when a client connected forcefully disconnects from the server.

**To Reproduce**
1. checkout and run [server:]( https://github.com/blackmo18/ktor-websocket-service-test)
2. checkout and run [client](https://github.com/blackmo18/ktor-websocket-client-test)
3. run at least two clients
4. forcefully shutdown a client
5. see stack trace

**Expected behavior**
I wanted to catch exception when the client is unreachable via try/catch

**Screenshots**
![stack trace](https://user-images.githubusercontent.com/22386010/64663369-25673780-d47e-11e9-8e73-dd44543caf7f.jpg)

**Comment by cy6erGn0m** [comment] 2019-09-16 16:39
Well, the reason why an exception is not thrown is that the chance of such result is too low: it can only happen due to a race when `socket.outgoing.isClosedForSend` is `false` yet so we are trying to send a message and at the same time WebSocket is closed so we are failing to send it. This is very unlikely.

So it's not exactly clear get where do you expect an exception to be thrown from?

**Comment by cy6erGn0m** [comment] 2019-09-16 16:47
Just to clarify it a bit more: you are checking `socket.outgoing.isClosedForSend` before sending so you don't have any errors so a session is simply removed. 

When a session is closed, both incoming and outgoing channels are closed.

```
for (message in incoming) {
    // handle message
} // once socket is closed, the loop will complete
```

**Comment by blackmo18** [comment] 2019-09-17 13:38
After I forced shutdown my client with at least 20 seconds interval before the server tries to send a message to the client, it still throws an exception.

I just want to simulate when a client application shutdowns/crashes and failed to close the socket on their side.

Theres is nothing much of an issue here, I guess for now I have to exclude the error on my logs.

**Comment by dmitrievanthony** [comment] 2020-03-24 15:07
Hi @blackmo18,

Is this issue still actual? I cannot reproduce it using the code you provided.

**Comment by oleg-larshin** [comment] 2020-08-10 15:30
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-554">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2021-04-05 12:12 UTC
Labels: bug
