### ISSUE TITLE
raw socket bug?

### ISSUE THREAD

**Issue by kobe2000** [ktorio/ktor#409] opened 2018-05-17 08:12 UTC
Hi,
I currently use ktor raw socket tools to write a network program. I found the reader fail to read data sometimes. Here is code reproducing error:

ktor version is 0.9.2

```
import io.ktor.network.sockets.aSocket
import io.ktor.network.sockets.openReadChannel
import io.ktor.network.sockets.openWriteChannel
import kotlinx.coroutines.experimental.async
import kotlinx.coroutines.experimental.launch
import kotlinx.coroutines.experimental.runBlocking
import java.net.InetSocketAddress

fun main(args: Array<String>) {

    async {
        val server = aSocket().tcp().bind(InetSocketAddress(12000))
        while (true) {
            println("accept")
            val socket = server.accept()
            launch {
                val rc = socket.openReadChannel()
                val wc = socket.openWriteChannel(autoFlush = true)

                var seq = 0
                while (true) {
                    wc.writeByte(1)
                    wc.writeInt(1)
                }
            }
        }
    }

    Thread.sleep(1000)

    runBlocking {
        aSocket().tcp().connect(InetSocketAddress("localhost", 12000)).use { socket ->
            val rc = socket.openReadChannel()
            val wc = socket.openWriteChannel(autoFlush = true)
            while (true) {
                check(rc.readByte() == 1.toByte()) { "byte" }
                check(rc.readInt() == 1) { "int" }
            }
        }
    }
}
```

**Comment by soywiz** [comment] 2018-05-17 08:30
If I recall correctly, the problem was in kotlinx.coroutines here: https://github.com/Kotlin/kotlinx.coroutines/blob/379f210f1d6f6ee91d6198348bd16306c93153ce/core/kotlinx-coroutines-io/src/main/kotlin/kotlinx/coroutines/experimental/io/ByteBufferChannel.kt#L714

I triggered that bug too, but was not able to reproduce it with a small self-contained test by then, so thanks for that :) Can you report this issue at the `kotlinx.coroutines` repo too? Thanks in advance!

**Comment by kobe2000** [comment] 2018-05-17 08:43
Wow, such a rapid response. Thank you for walkaround solution. I will report the issue at kotlinx

**Comment by Stexxe** [comment] 2020-06-28 12:46
Cannot reproduce it now. Seems like it was fixed in https://github.com/Kotlin/kotlinx.coroutines/commit/a432a82f48e186e540dee39d9d360ae37ef3825e

**Comment by oleg-larshin** [comment] 2020-08-10 15:29
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-784">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Closed** 2021-03-30 08:20 UTC
Labels: bug
