### ISSUE TITLE
Static content not updated

### ISSUE THREAD

**Issue by mattiejas** [ktorio/ktor#915] opened 2019-01-31 20:17 UTC
### Version
1.1.2

### Context/Issue
I am building an application where you can upload a profile picture and it would write that image to `/resources/static/users`. This works if I were to restart the application. If I wouldn't, the uploaded pictures wouldn't be served.

I am using the following piece of code to route my static content:

```java
    routing {
        // Static feature. Try to access `/static/ktor_logo.svg`
        static("/static") {
            resources("static")
        }
    }
```

Am I doing something wrong or is this intended?

**Comment by cy6erGn0m** [comment] 2019-02-04 23:49
Not sure if JVM provide ability to modify resources on the fly without specialized classloader. Serve directory instead of the classpath.

**Comment by oleg-larshin** [comment] 2020-08-10 15:24
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-684">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment] 2021-07-09 12:02
In your case, files are served from the resources folder which is located inside a JAR. When an image is uploaded, your application saves it to a filesystem. The problem is that resources are packed into a JAR during the build process and read-only inside it.

**Closed by Stexxe** 2021-07-09 12:02 UTC
