### ISSUE TITLE
Unexpected behavior of the Android client on Android L

### ISSUE THREAD

**Issue by Ribesg** [ktorio/ktor#1084] opened 2019-04-25 11:11 UTC
### Ktor
`ktor-client-android` 1.1.4

### Context
Java 1.8
Kotlin 1.3.30
Gradle 5.4
Android Gradle Plugin 3.4.0
Multiplatform context
Android app: no ProGuard nor R8, Multidex enabled

### Implementation
MPP Library H exposes a factory of `HttpClient`
MPP Library M implements the Algolia REST API using library H
Non-MPP Android app uses library M to call Algolia's search API

### Result
Only difference is the Android version. Both requests are done roughly at the same time on two different emulators running the same APK, and running on the same MacOS machine.
* On Android Q, the request works as expected, returns status code 200 and the expected json
* On Android L, the request returns a status code 400 with a basic json result:
    ```
    {
      "message": "Bad request",
      "status": 400
    }
    ```
The experience could be reproduced again and again. 100% 200 on Android Q and 100% 400 on Android L. Restarting and wiping both devices had no impact. Complete clear and rebuild of project had no impact.
Further investigation with Algolia shows that the request never actually reached them: there's no trace of a 400 response on the server side. The lack of standard Algolia headers in the 400 response seem to confirm this.
The requests are using HTTPS.

I had to switch to `ktor-client-okhttp` and move on. Didn't have time to create dozens on emulators to test which version of Android works and which doesn't.

**Comment by chrismabotuwana** [comment] 2020-02-11 04:39
any updates on this issue? @e5l @Ribesg

**Comment by Ribesg** [comment] 2020-02-11 09:27
>I had to switch to `ktor-client-okhttp` and move on.

**Comment by oleg-larshin** [comment] 2020-08-10 15:25
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-630">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment] 2021-07-22 10:37
I am unable to reproduce it.

**Closed by Stexxe** 2021-07-22 10:37 UTC
