### ISSUE TITLE
Generic Serialization 

### ISSUE THREAD

**Issue by Bizilizi** [ktorio/ktor#2013] opened 2020-07-31 10:15 UTC
ktor Server, kotlinx serialization

This issue is a try to draw attention to fixes made with respect to [1879](https://github.com/ktorio/ktor/issues/1879) and partially related to [1858](https://github.com/ktorio/ktor/issues/1858)

With the current approach, kotlinx serialization feature is not able to perform serialization of generic classes during the `call.respond`.

Suppose you want to formalize responses in a way like this:
```Kotlin 
@Serializable
data class APIResponse<T>(
        val result: T,
        val success: Boolean = true,
        val errorCode: Int?,

        @Serializable(with = DateTimeSerializer::class)
        val timestamp: DateTime

)
``` 

In that situation serializer of `APIResponse` would have an argument, in order to implicitly declare nested serializer:

```Kotlin 
val serializer = APIResponse.serializer(ContentReview.serializer())
```

And by calling `call.respond` you would receive `Can't locate argument-less serializer for class APIResponse`, since with the [current fixes](https://github.com/ktorio/ktor/commit/4de5c8a2be868a879722214186f195add8a101da#diff-ede08d8977d9f82cdd7a62575fa8fbc5R61) `module.getContextual(value::class)` returns null.
I guess this problem also can be generalized to the case of `call.receive<Boxed<Int>>()`

Please consider specifying serializer to use in `call.respond` and  `call.receive` in some way other than `module.getContextual(...)`. Unless you want to deal with all of the feature requests related to kotlinx serialization of course.

My suggestion is to add an option to `call.respond`/`call.receive` in order to specify the serializer for complex cases and use default serializer installed through `install(ContentNegotiation)` as a default one.

**Comment by cy6erGn0m** [comment] 2020-08-03 08:42
Yes, this is the known limitation that will be eliminated in the future.

**Comment by lamba92** [comment] 2020-08-07 09:54
Duplicate of #1783

**Comment by rwsbillyang** [comment] 2020-08-28 14:38
I am also plagued by this problem. I used the similar design in http response. I have to add 'contextual(MyDataModel.serializer()) ' into SerializersModule for every  data model class after upgrade to koltin 1.4.0.  It's cumbersome if too many data model classes.

**Comment by e5l** [comment] 2021-04-05 16:00
Duplicate

**Closed by e5l** 2021-04-05 16:00 UTC
Labels: feature

**Comment by xht418** [comment] 2021-12-03 14:28
I got the similar problem today: https://stackoverflow.com/q/70207677/3466808, any one can help?
