### ISSUE TITLE
Auto-reloading on resources content change

### ISSUE THREAD

**Issue by AdityaAnand1** [ktorio/ktor#1653] opened 2020-02-16 08:40 UTC
Is there a way to setup auto-reloading when the contents of the resources directory change?

I'm setting up static serving with SSR (via HTML templating) and just putting all my frontend stuff in resources directory. Would be super helpful in development if my frontend changes (in the resources directory) are auto-reloaded by ktor (i.e, always serve the latest files).

**Comment by arnavb** [comment] 2020-07-18 02:05
I'd also like to see this feature in ktor. It would make debugging frontend stuff a lot easier.

**Comment by oleg-larshin** [comment] 2020-08-10 15:28
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-471">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by kamilgregorczyk** [comment] 2021-01-23 17:32
ping, this is something really needed, especially that when I run the most basic app, the console says:

```
021-01-23 18:31:58.228 [main] DEBUG Application - Watching /Users/kamilgregorczyk/IdeaProjects/befame/build/resources/main/static/image for changes.
2021-01-23 18:31:58.228 [main] DEBUG Application - Watching /Users/kamilgregorczyk/IdeaProjects/befame/build/resources/main/static/html for changes.
2021-01-23 18:31:58.228 [main] DEBUG Application - Watching /Users/kamilgregorczyk/IdeaProjects/befame/build/classes/kotlin/main for changes.
2021-01-23 18:31:58.228 [main] DEBUG Application - Watching /Users/kamilgregorczyk/IdeaProjects/befame/build/resources/main/static for changes.
2021-01-23 18:31:58.228 [main] DEBUG Application - Watching /Users/kamilgregorczyk/IdeaProjects/befame/build/classes/kotlin/main/com for changes.
2021-01-23 18:31:58.228 [main] DEBUG Application - Watching /Users/kamilgregorczyk/IdeaProjects/befame/build/classes/kotlin/main/com/befame for changes.
2021-01-23 18:31:58.228 [main] DEBUG Application - Watching /Users/kamilgregorczyk/IdeaProjects/befame/build/classes/kotlin/main/META-INF for changes.
2021-01-23 18:31:58.228 [main] DEBUG Application - Watching /Users/kamilgregorczyk/IdeaProjects/befame/build/resources/main for changes.
2021-01-23 18:31:58.228 [main] DEBUG Application - Watching /Users/kamilgregorczyk/IdeaProjects/befame/build/resources/main/static/css for changes.
2021-01-23 18:31:58.482 [main] INFO  Application - Responding at http://0.0.0.0:8080
20
```

but it does not work, I have to restart server all the time

**Comment by Stexxe** [comment] 2021-07-08 11:25
Cannot reproduce with Ktor 1.6.1.

**Closed by Stexxe** 2021-07-08 11:25 UTC
Labels: feature
