### ISSUE TITLE
Serializing Flowable in response

### ISSUE THREAD

**Issue by pracownia-ioad** [ktorio/ktor#917] opened 2019-01-31 22:39 UTC
### Ktor Version
1.1.2
### Ktor Engine Used(client or server and name)
Netty
### JVM Version, Operating System and Relevant Context
OpenJDK 1.8.0_191, Ubuntu 18.04.1
### Feedback
I'm using jackon as an content negotiator. I'm trying to return on my endpoint as a response `Flowable<>` but then I get an exception saying:

`"error":"com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class io.reactivex.internal.operators.flowable.FlowableFlatMap and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)"`

Is there any way to return stream of data from reactive extensions as Flowable to the client properly parsed in ktor? When using Spring I had no problem doing that just by defining return type. I searched from some examples given in the docs, but they use either `awaitLast `or `consumeEach `for getting access to the internals of Flowable.

Here is sample code for better understanding of my intentions:

```
    routing {
        post(PROVIDERS_URL) {
            errorAware {
                logger.info("Get all job offers")
                val something= call.receive<Something>()
                call.respond(providerAdapter.acquireSomething(something))
            }
        }
    }
```

`fun acquireSomething(something: Something): Flowable<Some>`

**Comment by pracownia-ioad** [comment] 2019-02-18 20:47
Is there any chance I will get some feedback?

**Comment by oleg-larshin** [comment] 2020-08-10 15:24
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-682">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment] 2021-07-09 11:50
I cannot reproduce this error using Ktor 1.6.1 with the following code:
```kt
fun main(args: Array<String>) {
    val server = embeddedServer(CIO, port = 8082) {
        install(ContentNegotiation) {
            jackson()
        }

        routing {
            get("/") {
                call.respond(Flowable.just(Some(123)))
            }
        }
    }

    server.start(wait = true)
}

data class Some(val x: Int)
```

**Closed by Stexxe** 2021-07-09 11:50 UTC
