### ISSUE TITLE
java.lang.IllegalStateException: Unknown form content type

### ISSUE THREAD

**Issue by himaanshi** [ktorio/ktor#1760] opened 2020-03-30 11:48 UTC
implementation io.ktor:ktor-client-core
  implementation io.ktor:ktor-client-android
  implementation io.ktor:ktor-client-ios
  verison : 1.2.2

I am working on kotlin mpp demo , in that demo i am trying to upload image to server .
I am uploading image using multipart . My code to create form data 

  val disp = " form-data; name='file'; filename="
            val finalDisp = disp + file.name

            val formDataFile = formData {
                append("file", file, Headers.build {
                    append(HttpHeaders.ContentType, "multipart/form-data; boundary=something")
                    append(HttpHeaders.ContentDisposition, finalDisp
                    )
                })
            }

            imageUploadPresenter.uploadImage(formDataFile)

//Method to upload image :

 suspend fun uploadImage(uploadFile: List<PartData>): String {
        var data: String = ""
        try {
            client.post<HttpResponse>(url) {
                body = MultiPartFormDataContent(uploadFile)
                println("Response body  " + body)
            }.use { response ->
                println("Response status is : ${response.call.response.status}")
                println("Response requestTime is : ${response.call.response.requestTime}")
                println("Response responseTime is : ${response.call.response.responseTime}")

                data = response.call.response.status.toString()
            }
        } catch (e: Exception) {
            println("FileUploadApi Exception  " + e)
            data = "Exception>> " + e

        }
        return data
    }

when i try to create form data it gives exception : java.lang.IllegalStateException: Unknown form content type. Can anybody help .

**Comment by Stexxe** [comment] 2020-07-27 10:07
I cannot reproduce it with `1.3.2`. @himaanshi are you able to reproduce it with the [last released version](https://github.com/ktorio/ktor/releases/tag/1.3.2)?

**Comment by oleg-larshin** [comment] 2020-08-10 15:22
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-428">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment] 2021-04-05 15:14
Closed

**Closed by e5l** 2021-04-05 15:14 UTC
Labels: bug

**Comment by wiryadev** [comment] 2024-05-21 15:32
Im having this issue too when using `append(HttpHeaders.ContentType, ContentType.Application.Pdf)`, but solved after change it to `append(HttpHeaders.ContentType, "application/pdf")`
