### ISSUE TITLE
Creating HttpClient with Apache engineFactory doesn't work

### ISSUE THREAD

**Issue by tentypwtk** [ktorio/ktor#1234] opened 2019-07-17 19:01 UTC
**Ktor Version and Engine Used (client or server and name)**
version, client/server, additional ktor modules included
ktor 1.2.2
kotlin 1.3.41

dependencies
```
compile "ch.qos.logback:logback-classic:$logback_version"
    compile "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.9.2"
    compile "com.google.appengine:appengine:$appengine_version"
    compile "com.google.cloud:google-cloud-logging-logback:$gce_logback_version"
    compile "io.ktor:ktor-auth:$ktor_version"
    compile "io.ktor:ktor-client-apache:$ktor_version"
    compile "io.ktor:ktor-client-auth-jvm:$ktor_version"
    compile "io.ktor:ktor-client-core-jvm:$ktor_version"
    compile "io.ktor:ktor-client-core:$ktor_version"
    compile "io.ktor:ktor-html-builder:$ktor_version"
    compile "io.ktor:ktor-jackson:$ktor_version"
    compile "io.ktor:ktor-locations-metadata:$ktor_version"
    compile "io.ktor:ktor-locations:$ktor_version"
    compile "io.ktor:ktor-server-core:$ktor_version"
    compile "io.ktor:ktor-server-netty:$ktor_version"
    compile "io.ktor:ktor-server-servlet:$ktor_version"
    compile "net.logstash.logback:logstash-logback-encoder:5.1"
    compile "org.jetbrains:kotlin-css-jvm:1.0.0-pre.31-kotlin-1.2.41"
    compile 'com.google.cloud:google-cloud-firestore:1.11.0'
    compile 'com.google.cloud:google-cloud-storage:1.38.0'
    compile 'org.koin:koin-ktor:2.0.1'
    testCompile "io.ktor:ktor-server-tests:$ktor_version"
    compile "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
```

Intelij:
```
IntelliJ IDEA 2019.1.3 (Ultimate Edition)
Build #IU-191.7479.19, built on May 28, 2019
JRE: 1.8.0_202-release-1483-b58 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.1
```

**Describe the bug**
When installin Authentication module I need to create an Apache client. Doing that by using the constructor with engineFactory causes a weird error where Inteliji syntax is almost error like colour (#C53A47). When hovering over - no explanation, when I start the app it says that client lateinit var has never been initialized.

**To Reproduce**
Follow official tutorial for adding authentication. 

**Expected behavior**
Adding http client by following factory object (Apache).

My workaround (1st line on the screenshot) is to use the constructor with engine (not engineFactory) and calling build() on Apache object.

**Screenshots**
<img width="342" alt="Screenshot 2019-07-17 at 20 54 53" src="https://user-images.githubusercontent.com/1330830/61403559-d49bee00-a8d5-11e9-95e2-5207f384428a.png">

Please accept my apologies if I posted this in a wrong place or this is obvious. It's just my best intention to help others to avoid this behaviour.

Thanks

**Comment by e5l** [comment] 2019-07-18 10:11
Hi @tentypwtk, thanks for the report.
The last line is working, but the color is wrong. It looks like an IDE problem

**Comment by tentypwtk** [comment] 2019-07-19 15:18
Hi @e5l  If it was just the colour, I would have ignored it and hope that next update of Intelij will fix it. As I said:
> when I start the app it says that client lateinit var has never been initialized.
So this code isn't marked as error but at the same time it is not "processed" correctly.

**Comment by e5l** [comment] 2019-07-19 17:31
Could you provide self contained reproducer?

**Comment by tentypwtk** [comment] 2019-07-22 13:16
Sure I can, I'll send a link over a DM

**Comment by tentypwtk** [comment] 2019-07-22 13:18
https://www.dropbox.com/s/p8pb0sgggo7pf4u/selfcontained_example_for_issue_1234.zip?dl=0

**Comment by oleg-larshin** [comment] 2020-08-10 15:25
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-589">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment] 2022-04-26 12:38
Can't reproduce with Ktor 2.0.0

**Closed by e5l** 2022-04-26 12:38 UTC
Labels: ux
