### ISSUE TITLE
Setting contentType on a GET request fails with a socket timeout exception

### ISSUE THREAD

**Issue by saket** [ktorio/ktor#1979] opened 2020-06-30 03:59 UTC
**Ktor Version and Engine Used (client or server and name)**
Ktor client 1.3.72

**Describe the bug**
Setting the `contentType` of a GET request fails with a socket timeout exception after the timeout period (which defaults to 10s).

**To Reproduce**
I was only able to reproduce this on a specific GitHub endpoint that requires [auth](https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/), so apologies for not sharing a better example. 

```kotlin
val accessToken = "..."
val response = client.get<String>("https://api.github.com/user/repos") {
  accept(ContentType.Application.Json)
  header("Authorization", "token $accessToken")
}
```

**Expected behavior**
I'm not sure. Should Ktor throw an exception because a content type was set for a request without a body? Or should the content-type be ignored?

**Comment by hhariri** [comment] 2020-06-30 08:35
What is the specific endpoint you're calling? The user/repos one?

**Comment by saket** [comment] 2020-06-30 15:07
Yep!

**Comment by hhariri** [comment] 2020-06-30 15:11
What happens if you remove the <String>?

**Comment by saket** [comment] 2020-06-30 16:19
Not sure if I understand? `HttpClient#get()` explicitly needs a type parameter:

```kotlin
suspend inline fun <reified T> HttpClient.get(
    urlString: String,
    block: HttpRequestBuilder.() -> Unit = {}
): T
```

**Comment by oleg-larshin** [comment] 2020-08-10 15:27
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-321">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment] 2022-02-08 13:46
Can't reproduce.

**Closed by Stexxe** 2022-02-08 13:46 UTC
Labels: bug, triaged
