### ISSUE TITLE
DoubleReceiveException inside HttpCallValidator.validateResponse

### ISSUE THREAD

**Issue by sydneyagcaoili** [ktorio/ktor#1184] opened 2019-06-12 03:45 UTC
### Ktor Version 1.2.0
###Ktor Engine Used(client or server and name) Client OkHttp
###JVM Version, Operating System and Relevant Context JVM 1.8
```
install(HttpCallValidator) {
            validateResponse { response ->
                val statusCode = response.status.value
                when (statusCode) {
                    var responseString = response.readText //DoubleReceiveException
                    in 400..499 -> throw  TheCustomExceptionIWant(parseIntoObject(responseString))
                   ...
                }
            }
        }
```

Hi (⌒_⌒;), I'm a bit new to Kotlin. I wanted to parse the custom json errors returned from our server.
ex.
```{
    error : {
           title : "some error"
    }
    code : "422" 
}```

I've always thought the HttpCallValidator feature is a good way to do this instead of putting handlers in each api calls with JsonFeature - Kotlinx Serializer. 

How do I achieve reading the response from the validator?

**Comment by dusk007** [comment] 2019-12-17 11:26
I had the same issue (v 1.2.6) and fixed it temporarily via useing readBytes()
The issue is that in readText you call receive<Input>(). What receive does is it asks an `received atomic(boolean)` where the client has already been received.
The copy hack of the HttpResponse does not fix it for receive because the HttpClient which contains the atomic(bool) cannot be overridden and is not reset.
`readBytes()` does not go through the receive method and there is no check for `received?` thus it works as long as the content can be received again. 

My attempt at using the default ValidationCode and changing it a bit. 
We should add a DoubleReceive Feature as it exists as an ApplicationFeature.
Resetting the recieve pipline is unfortunately tricky but the current SavedHttpResponse experimental implementation is obviously missing a way to buffer or reset the receive. I suppose people will only need this for json or String payloads with a limit. But Intereceptors like a validator sometimes need to look into json payloads.
Another idea would be to allow caching of receives via a flag with some settings like max size, content types, ... Pretty much what DoubleReceive does I think just that we need it for the client.

`fun HttpClientConfig<*>.addDefaultResponseValidation() {
  HttpResponseValidator {
    validateResponse { response ->
      val statusCode = response.status.value
      val originCall = response.call

      if (statusCode < 300 || originCall.attributes.contains(ValidateMark)) return@validateResponse
      response.use {
        val exceptionCall = originCall.save().apply {
          attributes.put(ValidateMark, Unit)
        }
        //try parse error from json payload which other microservice usually send
        exceptionCall.response.receiveError()?.also { throw mapErrors(response, it) }
        //default ktor exception mapping
        when (statusCode) {
          in 300..399 -> throw RedirectResponseException(response)
          in 400..499 -> throw ClientRequestException(response)
          in 500..599 -> throw ServerResponseException(response)
        }
        if (statusCode >= 600) {
          throw ResponseException(response)
        }
      }
    }
  }
}

suspend fun HttpResponse.receiveError():ServiceErrorResponse? {
  val size = contentLength()?:0L
  return if(size in 1 until MAX_ERROR_PAYLOAD_LENGTH) {
    val payload = readBytes()
    try {
      this.readText(Charsets.UTF_8)
      JacksonConfig.defaultMapper.readValue<ServiceErrorResponse>(payload)
          .apply {
            url = call.request.url.toString()
          }
    } catch (e: JsonMappingException) {
      ServiceErrorResponse(
          statusCode = status.value,
          url = call.request.url.toString(),
          error = "ServiceErrorResponse",
          message = payload.toString(Charsets.UTF_8)
      )
    }
  }else {
    null
  }
}`

**Comment by k0enf0rNL** [comment] 2020-07-01 08:10
I have the exact same problem. We send information about what exactly went wrong in the body of the response that goes back to the caller. We use the Zalando problem library so that we comply with the application/problem+json standard. 

It also makes no sense why the responsevalidator (which is only allowed to check metadata at the moment) gets called later than the receive of the body in the response + conversion to an object. I want to determine wheter the call has gone wrong and then decide what I'm going to do with the body. So either give me the content of the response in the validateResponse function, allow me to read the response when I want to or give us an optional parameter in the request function that accepts a class that the response will be converted to in case of an error.

It's not a good solution to just copy all the code that reads the response and do it all manually.

**Comment by oleg-larshin** [comment] 2020-08-10 15:25
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-608">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by hikkidev** [comment] 2020-08-24 09:12
On version 1.4.0 the error is simply reproduced:
```kotlin
val client = HttpClient(OkHttp) {
        expectSuccess = false        
        install(HttpCallValidator) {
            validateResponse { response ->  throw RuntimeException("Response not valid") }
        }
}
suspend fun myBestRequest(): MyResponseObj = client.get {...}

try {
        val response = myBestRequest()
        Result.success(response)
} catch (cause: Throwable) {
        Result.failure(cause) <- caught the first `cause`, and then the application crashes with the error `cause`.
}
```

**Comment by Stexxe** [comment] 2021-07-22 11:04
Cannot reproduce using Ktor 1.6.1.

**Closed by Stexxe** 2021-07-22 11:04 UTC
Labels: ux
