### ISSUE TITLE
Prepend/Append bytes/packet to index

### ISSUE THREAD

**Issue by ronjunevaldoz** [ktorio/ktor#1772] opened 2020-04-06 08:29 UTC
#### Manual
```
val packet = BytePacketBuilder()
packet.writeByte(0x00) // set as header 
packet.writeInt(8) // 8 = 4+4 bytes total written below bytes
packet.writeInt(0) // 4 bytes
packet.writeInt(0) // 4 bytes
```
#### Current
```
val packet = BytePacketBuilder()
packet.writeInt(0)
 packet.writeInt(0)
val finalPacket = buildPacket {
      writeByte(0)
      writeInt(packet.size)
      writePacket(packet.build())
 } 
00 00000008 00000000 00000000
```

#### Feature request
```
val size = packet.size // total bytes, 8 bytes ignoring the header
packet.append(size)
#### Expected result
// 00 00000008 00000000 00000000
// total of 13 bytes
```
### Question
If there's a better way, I am open for suggestions.

**Comment by oleg-larshin** [comment] 2020-08-10 15:28
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-422">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment] 2022-02-08 14:04
Can't reproduce.

**Closed by Stexxe** 2022-02-08 14:04 UTC
Labels: feature
