### ISSUE TITLE
iOS Client Cookies on 302 Response

### ISSUE THREAD

**Issue by nectar1** [ktorio/ktor#1625] opened 2020-02-07 17:40 UTC
**Ktor Version and Engine Used (client or server and name)**
1.3.0 iOS client

**Describe the bug**
if you setup cookies storage manually by
`install(HttpCookies) {
    storage = AcceptAllCookiesStorage()
}`
on redirection response (http code 302) cookies doest apply on new request 

I thought that AcceptAllCookiesStorage is default storage, but if I don't setup storage everything works fine.

Android is ok in both cases.

**Comment by e5l** [comment] 2020-03-25 08:25
Hi @nectar1, the issue is fixed in `1.3.2`

**Closed by e5l** 2020-03-25 08:25 UTC
Labels: bug
