### ISSUE TITLE
Crash with Firebase Performance in iOS

### ISSUE THREAD

**Issue by eduardbosch** [ktorio/ktor#1040] opened 2019-03-25 14:11 UTC
### Ktor Version
1.1.3

### Ktor Engine Used(client or server and name)
Client iOS with default engine

### Feedback (Bug)
When adding Firebase Performance to an iOS application, the app crashes when making a request with Ktor.

I've forked the sample mmp project and added the Firebase Performance library. The application crashes due to Firebase Performance. It might be because Firebase intercepts all network requests and it might be incompatible with Ktor.

You can find the sample mmp client crashing with Firebase Performance here https://github.com/eduardbosch/ktor-samples/commit/35bb435b4138ef966eeb9c44cbaf632bfaaeb305
Remember to add the GoogleServices-Info.plist to prevent Firebase to crash when it is initialised.

I hope this can help Ktor! 🎉

**Comment by e5l** [comment] 2019-03-25 14:21
Hi @eduardbosch, thanks for the report. I'll investigate the problem.

**Comment by oleg-larshin** [comment] 2020-08-10 15:30
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-642">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by AlexTyurinV** [comment] 2020-09-30 08:02
I have this problem reproduced on the version "1.3.2-1.4.0-rc"

**Comment by corbella83** [comment] 2020-11-24 13:56
It still happening in 1.4.2

**Comment by leinardi** [comment] 2021-01-08 15:14
We are experiencing this crash after we upgraded from Kotlin 1.3.72 to 1.4.10.

Unfortunately the issue on Firebase side was closed due to inactivity without a proper fix: https://github.com/firebase/firebase-ios-sdk/issues/2626

Is there any workaround available, beside removing Firebase?

**Comment by corbella83** [comment] 2021-02-23 17:09
Good News:

With kotlin 1.4.30, ktor 1.5.0 and coroutines 1.4.2-native-mt NOT CRASHING anymore.

Seems to be this kotlin-native PR that solves it: https://github.com/JetBrains/kotlin-native/pull/4569

**Comment by e5l** [comment] 2021-02-24 07:52
Hey @corbella83, Thanks for the notice! Closed

**Closed by e5l** 2021-02-24 07:52 UTC
Labels: bug

**Comment by andersoncanteiro** [comment] 2021-07-15 22:54
Hi @e5l, first of all, thanks for your work, I really appreciate

I am still facing this problem. Here it is more details about

```
Kotlin: 1.5.10
Ktor: 1.6.0
Coroutines: 1.5.0-native-mt

Firebase iOS SDK: 6.31.0 and 8.3.0
```
