### ISSUE TITLE
httpClientCall cannot be canceled in other job

### ISSUE THREAD

**Issue by steveyangmoto** [ktorio/ktor#1411] opened 2019-10-23 13:49 UTC
**Ktor Version and Engine Used (client or server and name)**
ktor 1.2.5, client, coroutines 1.3.2

**Describe the bug**
httpClientCall.cancel() does not work as expected.
HttpClientCall can only be canceled within the current job.
calling httpClient.Call.cancel() within another job/coroutine does not work.

**To Reproduce**
Create two async jobs, one has httpClientCall.receive() running, other one calls httpClientCall.cancel()

**Expected behavior**
httpClientCall.cancel() should cancel the job that the http request runs in

**Comment by dmitrievanthony** [comment] 2020-02-27 15:31
Hi @steveyangmoto,

I prepared the following code to reproduce this issue:

```
suspend fun main() {
    HttpClient(Apache).use { client ->
        val builder = HttpRequestBuilder()
        builder.url("http://localhost:4242/stream-response")
        val result = client.execute(builder)

        GlobalScope.async {
            try {
                val res: String = result.receive()
                println("Res: $res")
            } finally {
                println("Receive is done!")
            }
        }

        delay(500)
        result.cancel()
        println("Result is active: ${result.isActive}")
    }
}
```

But this code works fine and `HttpClientCall` is canceled (version `1.2.5`).

Moreover, in the current version (I mean `1.3.1` and `master`) the `HttpClientCall` made internally and this API is not public anymore.

So, @steveyangmoto, please check if the code I mentioned here works for you and let me know whether this issue is still actual for you.

**Comment by oleg-larshin** [comment] 2020-08-10 15:30
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-538">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment] 2021-06-23 08:53
Can't reproduce it cause that API is not available anymore.

**Closed by Stexxe** 2021-06-23 08:53 UTC
Labels: bug
