### ISSUE TITLE
Reading from CIO's call.request.receiveChannel() causes 100% CPU usage

### ISSUE THREAD

**Issue by DanThrane** [ktorio/ktor#1046] opened 2019-03-28 11:29 UTC
### Ktor Version

1.1.3

### Ktor Engine Used(client or server and name)

CIO (Server)

### JVM Version, Operating System and Relevant Context

Tested with:

- OSX 10.14.4/Zulu 8.31.0.1-macosx
- Docker image: `adoptopenjdk/openjdk8-openj9`

### Feedback

Reading from the receive channel causes all cores to reach 100% CPU usage.
I have only experienced this issue with the CIO engine.

Minimal example for reproducing:

```kotlin
embeddedServer(CIO, port = 8080) {
    routing {
        post("/cpu") {
            val channel = call.request.receiveChannel()
            val buffer = ByteBuffer.allocate(1024 * 64)
            while (!channel.isClosedForRead) {
                channel.readAvailable(buffer)
                buffer.clear()
            }
            call.respondText("Bye")
        }

        post("/multipart") {
            val multipart = call.receiveMultipart()
            multipart.readAllParts()
            call.respondText("Bye")
        }
    }
}.start(wait = true)
```

Both of these endpoints trigger massive CPU usage.

**Comment by oleg-larshin** [comment] 2020-08-10 15:24
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-639">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment] 2021-07-15 10:09
Cannot reproduce with Ktor 1.6.1.

**Closed by Stexxe** 2021-07-15 10:09 UTC
