### ISSUE TITLE
Error serving static video: Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING

### ISSUE THREAD

**Issue by ScottPierce** [ktorio/ktor#1052] opened 2019-04-02 04:09 UTC
### Ktor Version
1.1.3

### Ktor Engine Used(client or server and name)
Netty

### JVM Version, Operating System and Relevant Context
Java 1.8.0_181 Is what my JAVA_HOME is set to.

Also:
```
IntelliJ IDEA 2019.1 (Ultimate Edition)
Build #IU-191.6183.87, built on March 27, 2019
JRE: 1.8.0_202-release-1483-b39 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.3
```

### Feedback
I'm seeing the following error in the browser console (chrome), while serving the page locally on my computer: `Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING`

That's all the information with the error. This is the first time I've seen this. It's just another indicator that there seems to be some race condition with the ktor code. Again, I can't reproduce this.

Here is the video that I saw the error happen with while loading. I have to zip it so github accepts it:
[intersection-time-lapse.mp4.zip](https://github.com/ktorio/ktor/files/3032274/intersection-time-lapse.mp4.zip)

The video is loaded via this html element:
```html
    <video id="home-background-video" muted playsinline autoplay loop preload="auto" poster="assets/images/intersection-first-frame.jpg" width="1920" height="1080">
      <source src="assets/images/intersection-time-lapse.mp4" type="video/mp4">
    </video>
```

The video is served via this ktor server code, via the static files route:
```Kotlin
fun main() {
    embeddedServer(
        Netty,
        port = 8080,
        module = Application::main
    ).apply { start(wait = true) }

}

private fun Application.main() {
    features()
    registration()
    staticFiles()
}

private fun Application.features() {
    install(Compression)
    install(ContentNegotiation) {
        jackson {
            configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
            configure(SerializationFeature.INDENT_OUTPUT, false)
        }
    }
}

private fun Application.staticFiles() {
    routing {
        static {
            files("web")
            default("web/index.html")
        }
    }
}
```

**Comment by ScottPierce** [comment] 2019-04-02 06:29
I've seen other similar errors since then: `GET http://localhost:8080/assets/images/intersection-time-lapse.mp4 net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)`

**Comment by oleg-larshin** [comment] 2020-08-10 15:24
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-637">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment] 2021-07-21 09:24
Cannot reproduce with Ktor 1.6.1.

**Closed by Stexxe** 2021-07-21 09:24 UTC
