### ISSUE TITLE
Getting UnsupportedOperationException when calling call.receive

### ISSUE THREAD

**Issue by JosueGramajo** [ktorio/ktor#1249] opened 2019-07-25 14:51 UTC
Ktor pre-release version 1.2.3-rc

When trying to parse the request using:
`suspend inline fun <reified T : Any> ApplicationCall.receive(): T = receive(T::class)`

In this way:
`val obj = call.receive<MyCustomObject>()`

It produces de following exception:

> java.lang.UnsupportedOperationException: This function has a reified type parameter and thus can only be inlined at compilation time, not called directly.
> 	at kotlin.jvm.internal.Intrinsics.throwUndefinedForReified(Intrinsics.java:193)
> 	at kotlin.jvm.internal.Intrinsics.throwUndefinedForReified(Intrinsics.java:187)
> 	at kotlin.jvm.internal.Intrinsics.reifiedOperationMarker(Intrinsics.java:197)
> 	at "my package"$main$2$3.invokeSuspend(KtorServices.kt:205)
> 	at "my package"$main$2$3.invoke(KtorServices.kt)
> 	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:268)
> 	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
> 	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:141)
> 	at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:161)
> 	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
> 	at io.ktor.routing.Routing.executeResult(Routing.kt:147)
> 	at io.ktor.routing.Routing.interceptor(Routing.kt:34)
> 	at io.ktor.routing.Routing$Feature$install$1.invokeSuspend(Routing.kt:99)
> 	at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt)
> 	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:268)
> 	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
> 	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:141)
> 	at io.ktor.features.ContentNegotiation$Feature$install$1.invokeSuspend(ContentNegotiation.kt:106)
> 	at io.ktor.features.ContentNegotiation$Feature$install$1.invoke(ContentNegotiation.kt)
> 	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:268)
> 	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
> 	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:141)
> 	at io.ktor.features.CallLogging$Feature$install$2.invokeSuspend(CallLogging.kt:139)
> 	at io.ktor.features.CallLogging$Feature$install$2.invoke(CallLogging.kt)
> 	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:268)
> 	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
> 	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:141)
> 	at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:161)
> 	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
> 	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invokeSuspend(DefaultEnginePipeline.kt:118)
> 	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
> 	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:268)
> 	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
> 	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:141)
> 	at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:161)
> 	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
> 	at io.ktor.server.servlet.KtorServlet$blockingService$1.invokeSuspend(KtorServlet.kt:148)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 	at kotlinx.coroutines.DispatchedKt.resumeCancellable(Dispatched.kt:447)
> 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:25)
> 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
> 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:154)
> 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:53)
> 	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
> 	at io.ktor.server.servlet.KtorServlet.blockingService(KtorServlet.kt:113)
> 	at io.ktor.server.servlet.KtorServlet.service(KtorServlet.kt:71)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
> 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
> 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1772)
> 	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
> 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
> 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
> 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
> 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
> 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
> 	at com.google.apphosting.runtime.jetty9.ParseBlobUploadHandler.handle(ParseBlobUploadHandler.java:119)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1182)
> 	at com.google.apphosting.runtime.jetty9.AppEngineWebAppContext.doHandle(AppEngineWebAppContext.java:187)
> 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
> 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
> 	at com.google.apphosting.runtime.jetty9.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:293)
> 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
> 	at org.eclipse.jetty.server.Server.handle(Server.java:539)
> 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:333)
> 	at com.google.apphosting.runtime.jetty9.RpcConnection.handle(RpcConnection.java:213)
> 	at com.google.apphosting.runtime.jetty9.RpcConnector.serviceRequest(RpcConnector.java:81)
> 	at com.google.apphosting.runtime.jetty9.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:134)
> 	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:722)
> 	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:685)
> 	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:655)
> 	at com.google.apphosting.runtime.JavaRuntime$NullSandboxRequestRunnable.run(JavaRuntime.java:847)
> 	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:270)
> 	at java.lang.Thread.run(Thread.java:748)
>

**Comment by cy6erGn0m** [comment] 2019-07-25 20:33
Looks like a kotlin compiler issue, probably incremental compiler. Could you please try to clean first?

**Comment by JosueGramajo** [comment] 2019-07-26 17:06
Yes, I tried cleaning and re-building, same result

Also, is worth mentioning that this implementation is running in a gcloud Appengine application, the gradle version of ktor was set to the latest using "+", and when setting the version manually back to 1.2.2, everything started working again, hope it helps

**Comment by cy6erGn0m** [comment] 2019-07-29 12:25
Unfortunately, I am not able to reproduce it yet. I believe it is something related to the suspend functions inliner that accidentally inlines the wrong code so it crashes. Any chance to see the code or get your project? If not, we'd like to see at least the bytecode of `"my package"$main$2$3` class.

**Comment by JosueGramajo** [comment] 2019-07-29 15:30
Yes, of course, I will attach the class where the ktor implementation is, and also the gradle file, if you need anything else, let me know.



[Archive.zip](https://github.com/ktorio/ktor/files/3442991/Archive.zip)

**Comment by cy6erGn0m** [comment] 2019-07-29 21:57
Ok, the reason is that you use older Kotlin compiler. Please upgrade kotlin plugin to 1.3.41 to eliminate the issue.

**Comment by cy6erGn0m** [comment] 2019-07-29 21:58
For sure it is a compiler bug, will investigate in more details in spite of the existing workaround

**Comment by JosueGramajo** [comment] 2019-07-30 15:06
I see, would do

thanks for the support

**Comment by e5l** [comment] 2021-04-05 09:26
Fixed with Kotlin update

**Closed by e5l** 2021-04-05 09:26 UTC
Labels: bug
