### ISSUE TITLE
JSON feature fails with io.ktor.client.features.ClientRequestException: Client request invalid: 406 Not Acceptable

### ISSUE THREAD

**Issue by holgerbrandl** [ktorio/ktor#1907] opened 2020-05-29 17:41 UTC
**Ktor Version and Engine Used (client or server and name)**
```
implementation "io.ktor:ktor-client-cio:$ktor_version"
implementation "io.ktor:ktor-client-json-jvm:$ktor_version"
implementation "io.ktor:ktor-client-gson:$ktor_version"
ext.ktor_version = "1.3.1"
```
JVM 1.8, with Kotlin v1.3.72

**Describe the bug**
With JSON support being enabled, it can not consume a REST API.

Example Implementation
```
import io.ktor.client.HttpClient
import io.ktor.client.features.json.JsonFeature
import io.ktor.client.request.get


suspend fun main() {
    val clusterJson: String = HttpClient().get("http://ubuntu:8082/v3/clusters")
    println(clusterJson)

    val client: V3Cluster = HttpClient() {
        install(JsonFeature)
    }.get("http://ubuntu:8082/v3/clusters")

}

data class V3Cluster(
        val `data`: List<Data>
)

data class Data(
        val attributes: Attributes,
        val id: String,
        val type: String
)

data class Attributes(
        val cluster_id: String
)
```

This fails with 
```
Exception in thread "main" io.ktor.client.features.ClientRequestException: Client request(http://ubuntu:8082/v3/clusters) invalid: 406 Not Acceptable
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:35)
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(DefaultResponseValidation.kt)
	at io.ktor.client.features.HttpCallValidator.validateResponse(HttpCallValidator.kt:35)
	at io.ktor.client.features.HttpCallValidator$Companion$install$2.invokeSuspend(HttpCallValidator.kt:96)
	at io.ktor.client.features.HttpCallValidator$Companion$install$2.invoke(HttpCallValidator.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:273)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:141)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:161)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
	at io.ktor.client.call.HttpClientCall.receive(HttpClientCall.kt:75)
	at controllers.KafkaClusterKt.main(KafkaCluster.kt:105)
....
```
The first get request is processed correctly, but the second one fails with the provided stacktrace.

**Expected behaviour**
It should deserialize the json response into an object.

Without JSON feature, the request works fine and is producing the JSON as output. Also when using curl on the terminal, the API endpoint itself seems fine:
```
brandl@ubuntu:~$ curl http://ubuntu:8082/v3/clusters | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   594  100   594    0     0  84857      0 --:--:-- --:--:-- --:--:-- 84857
{
  "links": {
    "self": "http://rest-proxy:8082/v3/clusters",
    "next": null
  },
  "data": [
    {
      "id": "crn:///kafka=CVyJNKWhSrmXmnRUKWo5cg",
      "links": {
        "self": "http://rest-proxy:8082/v3/clusters/CVyJNKWhSrmXmnRUKWo5cg"
      },
      "attributes": {
        "cluster_id": "CVyJNKWhSrmXmnRUKWo5cg"
      },
      "relationships": {
        "controller": {
          "links": {
            "related": "http://rest-proxy:8082/v3/clusters/CVyJNKWhSrmXmnRUKWo5cg/brokers/1"
          }
        },
        "brokers": {
          "links": {
            "related": "http://rest-proxy:8082/v3/clusters/CVyJNKWhSrmXmnRUKWo5cg/brokers"
          }
        },
        "topics": {
          "links": {
            "related": "http://rest-proxy:8082/v3/clusters/CVyJNKWhSrmXmnRUKWo5cg/topics"
          }
        }
      },
      "type": "KafkaCluster"
    }
  ]
}
```

Not relevant for the ticket, but maybe some context is helpful: I'm trying to cusome the confluent broker config API v3 as described under https://github.com/confluentinc/kafka-rest/issues/676

**Comment by holgerbrandl** [comment] 2020-05-29 17:55
The problem is not my data class. I've tried with klaxon, and it works perfectly fine (although being less pretty compared to *native* ktor):
```
val clusterJson = HttpClient().get<String>("http://$host:$port/v3/clusters")
val cluster = with(Klaxon()) { parseFromJsonObject<V3Cluster>(parseJsonObject(StringReader(clusterJson))) }!!
```

**Comment by e5l** [comment] 2020-06-04 11:33
Hi @holgerbrandl, thanks for the report. Could you add `Logging` feature and add the log here? I'm interested in request and response headers. It also would help if you post the `curl` headers as well(with `curl -v myurl`).

**Comment by holgerbrandl** [comment] 2020-06-09 00:18
Thanks for the support @e5l . The log is

```
Connected to the target VM, address: '127.0.0.1:62929', transport: 'socket'
{"links":{"self":"http://rest-proxy:8082/v3/clusters","next":null},"data":[{"id":"crn:///kafka=2XZZR4vQQMyQbs65v0BcQg","links":{"self":"http://rest-proxy:8082/v3/clusters/2XZZR4vQQMyQbs65v0BcQg"},"attributes":{"cluster_id":"2XZZR4vQQMyQbs65v0BcQg"},"relationships":{"controller":{"links":{"related":"http://rest-proxy:8082/v3/clusters/2XZZR4vQQMyQbs65v0BcQg/brokers/1"}},"brokers":{"links":{"related":"http://rest-proxy:8082/v3/clusters/2XZZR4vQQMyQbs65v0BcQg/brokers"}},"topics":{"links":{"related":"http://rest-proxy:8082/v3/clusters/2XZZR4vQQMyQbs65v0BcQg/topics"}}},"type":"KafkaCluster"}]}
02:12:38.832 [ktor-cio-dispatcher-worker-2] INFO io.ktor.client.HttpClient - REQUEST: http://ubuntu:8082/v3/clusters
02:12:38.835 [ktor-cio-dispatcher-worker-2] INFO io.ktor.client.HttpClient - METHOD: HttpMethod(value=GET)
02:12:38.835 [ktor-cio-dispatcher-worker-2] INFO io.ktor.client.HttpClient - COMMON HEADERS
02:12:38.835 [ktor-cio-dispatcher-worker-2] INFO io.ktor.client.HttpClient - -> Accept: application/json
02:12:38.835 [ktor-cio-dispatcher-worker-2] INFO io.ktor.client.HttpClient - -> Accept-Charset: UTF-8
02:12:38.835 [ktor-cio-dispatcher-worker-2] INFO io.ktor.client.HttpClient - CONTENT HEADERS
Exception in thread "main" io.ktor.client.features.ClientRequestException: Client request(http://ubuntu:8082/v3/clusters) invalid: 406 Not Acceptable
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:35)
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(DefaultResponseValidation.kt)
	at io.ktor.client.features.HttpCallValidator.validateResponse(HttpCallValidator.kt:37)
	at io.ktor.client.features.HttpCallValidator$Companion$install$2.invokeSuspend(HttpCallValidator.kt:99)
	at io.ktor.client.features.HttpCallValidator$Companion$install$2.invoke(HttpCallValidator.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:318)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:163)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:183)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
	at io.ktor.client.call.HttpClientCall.receive(HttpClientCall.kt:75)
	at kafka.heartbeats.configui.controllers.Ticket1907Kt.main(Ticket1907.kt:81)
	at kafka.heartbeats.configui.controllers.Ticket1907Kt$main$1.invokeSuspend(Ticket1907.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:238)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:194)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:144)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:238)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:194)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:144)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:238)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:194)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:144)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:238)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:194)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:144)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:238)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:194)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:144)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:250)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:123)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:111)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:307)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:317)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:249)
	at kotlinx.coroutines.ResumeAwaitOnCompletion.invoke(JobSupport.kt:1411)
	at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1529)
	at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:323)
	at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:240)
	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:903)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:860)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:825)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Disconnected from the target VM, address: '127.0.0.1:62929', transport: 'socket'

```

curl headers are
```
curl -v http://localhost:8082/v3/clusters | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 127.0.0.1:8082...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8082 (#0)
> GET /v3/clusters HTTP/1.1
> Host: localhost:8082
> User-Agent: curl/7.65.3
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Tue, 09 Jun 2020 00:15:26 GMT
< Content-Type: application/vnd.api+json
< Vary: Accept-Encoding, User-Agent
< Content-Length: 594
<
{ [594 bytes data]
100   594  100   594    0     0  29700      0 --:--:-- --:--:-- --:--:-- 29700
* Connection #0 to host localhost left intact
{
  "links": {
    "self": "http://rest-proxy:8082/v3/clusters",
    "next": null
  },
  "data": [
    {
      "id": "crn:///kafka=2XZZR4vQQMyQbs65v0BcQg",
      "links": {
        "self": "http://rest-proxy:8082/v3/clusters/2XZZR4vQQMyQbs65v0BcQg"
      },
      "attributes": {
        "cluster_id": "2XZZR4vQQMyQbs65v0BcQg"
      },
      "relationships": {
        "controller": {
          "links": {
            "related": "http://rest-proxy:8082/v3/clusters/2XZZR4vQQMyQbs65v0BcQg/brokers/1"
          }
        },
        "brokers": {
          "links": {
            "related": "http://rest-proxy:8082/v3/clusters/2XZZR4vQQMyQbs65v0BcQg/brokers"
          }
        },
        "topics": {
          "links": {
            "related": "http://rest-proxy:8082/v3/clusters/2XZZR4vQQMyQbs65v0BcQg/topics"
          }
        }
      },
      "type": "KafkaCluster"
    }
  ]
}
```

Feel welcome if there's anything else I could try to describe the problem better.

**Comment by holgerbrandl** [comment] 2020-06-09 00:20
The problem also occurs with ktor v1.3.2

**Comment by e5l** [comment] 2020-06-15 12:21
It looks like the `ContentType` is `application/vnd.api+json`. Could you add it with the `accept` method in the feature config?
```
val client: V3Cluster = HttpClient() {
    install(JsonFeature) {
        accept(ContentType("application", "vnd.api+json"))
    }
}.get("http://ubuntu:8082/v3/clusters")
```

**Comment by holgerbrandl** [comment] 2020-06-16 19:39
Thanks for the continued support. Unfortunately, this does not solve the problem. I kept logging feature enabled and now I see
```
21:31:54.843 [ktor-cio-dispatcher-worker-3] INFO io.ktor.client.HttpClient - REQUEST: http://ubuntu:8082/v3/clusters
21:31:54.845 [ktor-cio-dispatcher-worker-3] INFO io.ktor.client.HttpClient - METHOD: HttpMethod(value=GET)
21:31:54.845 [ktor-cio-dispatcher-worker-3] INFO io.ktor.client.HttpClient - COMMON HEADERS
21:31:54.845 [ktor-cio-dispatcher-worker-3] INFO io.ktor.client.HttpClient - -> Accept: application/json; application/vnd.api+json
21:31:54.845 [ktor-cio-dispatcher-worker-3] INFO io.ktor.client.HttpClient - -> Accept-Charset: UTF-8
21:31:54.845 [ktor-cio-dispatcher-worker-3] INFO io.ktor.client.HttpClient - CONTENT HEADERS
```
but the problem (400 Bad Request) remains.

Feel welcome if you more info.

**Comment by oleg-larshin** [comment] 2020-08-10 15:27
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-357">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment] 2021-02-12 08:56
@holgerbrandl I've reproduced the `406 Not acceptable` status code with Confluent 5.5.1. 
When you send a request with `JsonFeature` installed the `Accept: application/json` header is added. Without it, the client accepts every content type (`Accept: */*`). The solution to accept specific `application/vnd.api+json` content type works for me:
```kotlin
val res: V3Cluster = HttpClient(CIO) {
    install(Logging)
    install(JsonFeature) {
        serializer = GsonSerializer()
        accept(ContentType("application", "vnd.api+json"))
    }
}.get("http://localhost:8082/v3/clusters")
```

Please note that this problem is not reproducible with Confluent 6.1.0.

**Comment by holgerbrandl** [comment] 2021-02-12 19:45
Thanks for the workaround and the great analysis @Stexxe

**Closed** 2021-04-05 15:47 UTC
Labels: bug, triaged
