### ISSUE TITLE
OkHttp WebSocket hangs when computer goes to sleep on Linux

### ISSUE THREAD

**Issue by matejdro** [ktorio/ktor#1958] opened 2020-06-20 06:05 UTC
**Ktor Version and Engine Used (client or server and name)**

JVM Ktor 1.3.1 (which is latest stable `ktor-client-websockets` version as of writing this), OkHttp engine on both server and client.

Client is on Linux system (not sure if other operating systems behave differently).

**To Reproduce**
1. Connect to the websocket using following client code:

```kotlin
try {
    client.ws("wss://my-websocket.com",) {
        for (frame in incoming) {
            LOGGER.debug("Received $frame")
        }

        val closeReason = closeReason.await()
        LOGGER.debug("Close $closeReason")
    }
} catch (e: Exception) {
    LOGGER.error("Websocket Error", e)
}
```
2. Send messages periodically from the server (for example one every couple of seconds)
3. Verify that messages are being received (above code prints out "Received" log on every message)
4. Put the computer that hosts the client in sleep mode
5. Wait in sleep mode for about 15 minutes
6. Turn computer back on

**Expected behavior**

Socket should probably disconnect or at least give some sort of indication that connection has been dropped.

**Actual behavior**

Socket just hangs. It does not receive any new messages from the server and does not close or error out (no log outputs from the above code).

**Comment by matejdro** [comment] 2020-06-21 04:52
Workaround that I made:

1. Create a loop that calls `delay` for couple of seconds
2. After every sleep check for how much has the system time changed since last delay
3. If time was significantly longer than the amount you delayed for, assume system was in sleep mode and force-reconnect the socket.

**Comment by oleg-larshin** [comment] 2020-08-10 15:26
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-335">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment] 2022-08-17 08:50
Can't reproduce with 2.1.0

**Closed by e5l** 2022-08-17 08:50 UTC
Labels: bug, Client
