### ISSUE TITLE
ApplicationCall.respond should not be inline

### ISSUE THREAD

**Issue by schikin** [ktorio/ktor#304] opened 2018-01-29 21:36 UTC
Consider the repo https://github.com/schikin/ktor-netty-exception

Finishing the call with `ApplicationCall.respondText` works perfectly well. Calling `ApplicationCall.respond` results in exception (see screenshot) 
<img width="1680" alt="screen shot 2018-01-27 at 01 09 28" src="https://user-images.githubusercontent.com/2189133/35535499-d6630b0e-0554-11e8-8d0b-5f4daebc91fd.png"> but the result is still returned to the client correctly

I tried redefining the `respond` function in the following way:
```
suspend fun ApplicationCall.respond(message: Any) {
    response.pipeline.execute(this, message)
}
```

and it works perfectly well. Given there was recently a number of issues with inline suspend functions (
https://youtrack.jetbrains.com/issue/KT-16603) it seems like `respond` shouldn't be inline function

**Comment by cy6erGn0m** [comment] 2018-02-01 14:15
I believe it is not related to the issue, we just raising extra cancellation somewhere

**Comment by schikin** [comment] 2018-02-01 16:49
@cy6erGn0m maybe. but then why does `respondText` work and if I do `respond` with the same `TextContent` it throws an exception?

**Comment by orangy** [comment] 2018-02-25 12:40
I cannot reproduce it with the latest `master`, is it still a problem for you? Did you try with 0.9.1?

**Comment by orangy** [comment] 2018-03-09 13:10
I'm closing it for now, if you still see the issue feel free to reopen it.

**Closed by orangy** 2018-03-09 13:10 UTC
