### ISSUE TITLE
call.respond(Object) cause error

### ISSUE THREAD

**Issue by Alcheorg** [ktorio/ktor#192] opened 2017-08-28 09:01 UTC
At sample json for example:
`java.lang.IllegalArgumentException: Response pipeline couldn't transform 'class org.jetbrains.ktor.samples.json.Model' to the FinalContent`

//ktor-test-host used

**Comment by cy6erGn0m** [comment] 2017-08-29 06:20
Are you sure you have Gson feature installed?

**Comment by orangy** [comment] 2017-08-29 06:40
More likely Accept header is missing `application/json`. It looks like a duplicate of #180

**Comment by mohammadrafigh** [comment] 2017-09-19 16:09
I have the same problem. @cy6erGn0m Gson is installed, and @orangy application/json is set both for request and response. but the only thing works is that I manually convert to Json like this:
`call.respond(gson.toJson(myObject))`

**Comment by orangy** [comment] 2017-11-14 12:51
Is it still a problem with 0.9 and its new content negotiation feature?

**Comment by cy6erGn0m** [comment] 2018-08-30 10:03
Closing it due to no response. Please reopen it if there is still issue.

**Closed by cy6erGn0m** 2018-08-30 10:03 UTC
Labels: problem
