### ISSUE TITLE
CIO server html generation problem. Missing port

### ISSUE THREAD

**Issue by JajaComp** [ktorio/ktor#1401] opened 2019-10-15 22:20 UTC
**Ktor Version and Engine Used (client or server and name)**
io.ktor:ktor-server-cio:1.2.5

**Describe the bug**
I use not custom port for http server (port 8999). When i use "call.url" method inside "action" for form i get next link - "http://localhost/login" without port.
The function "call.respondRedirect" behaves similarly!
When i use "io.ktor:ktor-server-netty-1.2.5" i no have problem

Example: 
```
get<Login> {
        call.respondDefaultHtml2(emptyList(), CacheControl.Visibility.Public, title = Localization.titleLogin) {
            h2 { +Localization.titleLogin }
            form(
                action = call.url(Login(initPassword)),
                encType = FormEncType.applicationXWwwFormUrlEncoded,
                method = FormMethod.post)
            {
                div {
                    +Localization.lbPassword
                    passwordInput(name = "password") { autoFocus = true}
                }
                br
                div {
                    submitInput(classes = "pure-button pure-button-primary") {
                        value = Localization.btLogin
                    }
                }
            }
        }
    }
```

For fix i use "locations.href()" method.

Also for fix "call.respondRedirect(Index())" i use "call.respondRedirect(locations.href(Index()))"

**Comment by JajaComp** [comment] 2019-10-15 22:34
For respondRedirect i use extention from sample https://ktor.io/samples/app/youkube.html

suspend fun ApplicationCall.respondRedirect(location: Any) = respondRedirect(url(location), permanent = false)

**Comment by JajaComp** [comment] 2019-10-15 22:47
![Screenshot_20191016_014702](https://user-images.githubusercontent.com/7366014/66875406-e2d1d700-efb6-11e9-84c2-fde07eb0d122.png)

**Comment by JajaComp** [comment] 2019-10-15 22:52
Result for "ktor-server-cio"
![1](https://user-images.githubusercontent.com/7366014/66875612-9d61d980-efb7-11e9-934f-74f67b65a114.png)

Result for "ktor-server-netty"
![2](https://user-images.githubusercontent.com/7366014/66875622-a652ab00-efb7-11e9-8d35-885a68d1b371.png)

**Comment by oleg-larshin** [comment] 2020-08-10 15:30
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-540">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment] 2021-07-16 11:11
Cannot reproduce with Ktor 1.6.1.

**Closed by Stexxe** 2021-07-16 11:11 UTC
Labels: bug
