### ISSUE TITLE
Cookies are not logged by ktor-client-logging

### ISSUE THREAD

**Issue by varahash** [ktorio/ktor#1506] opened 2019-12-17 13:53 UTC
**Ktor Version and Engine Used (client or server and name)**
ktor-client-logging, 1.2.5

**Describe the bug**
If you install 'HttpCookies' and 'Logging' features, the cookies setted by 'HttpCookies' feature are not logged. This due to fact that logging happens before cookies was set for request.

Cookies set happens at `scope.sendPipeline.intercept(HttpSendPipeline.State)` https://github.com/ktorio/ktor/blob/1.2.5/ktor-client/ktor-client-core/common/src/io/ktor/client/features/cookies/HttpCookies.kt#L63

Logging happens at `scope.sendPipeline.intercept(HttpSendPipeline.Before)` https://github.com/ktorio/ktor/blob/1.2.5/ktor-client/ktor-client-features/ktor-client-logging/common/src/io/ktor/client/features/logging/Logging.kt#L143

**Comment by dmitrievanthony** [comment] 2019-12-18 07:34
Hi @varahash, thanks for reporting.

I've prepared a reproducer (see [here](https://github.com/dmitrievanthony/KPlayground/blob/%231506/src/main/kotlin/app.kt)) that demonstrates the problem. You correctly described the root cause, so I'll try to fix it soon.

**Comment by dmitrievanthony** [comment] 2019-12-18 12:36
Hi @varahash, https://github.com/ktorio/ktor/pull/1508 is merged and the fix will be released in `1.3.0`.

**Closed** 2019-12-18 12:39 UTC
Labels: bug
