### ISSUE TITLE
How to monitor whether ktor is running and restart server automatically if there's an exception?

### ISSUE THREAD

**Issue by AdityaAnand1** [ktorio/ktor#1435] opened 2019-11-12 02:43 UTC
I was wondering what is the recommended way of restarting the server any time there is a crash? Or better, how to make it so that no errors end up becoming fatal?

E.g: In the basic setup, throwing any Exceptions results in the server shutting down.

**Comment by oleg-larshin** [comment] 2020-08-10 15:28
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-530">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment] 2022-11-28 12:59
Can't reproduce.

**Closed by Stexxe** 2022-11-28 12:59 UTC
Labels: feature
