### ISSUE TITLE
Compression support stream

### ISSUE THREAD

**Issue by icode** [ktorio/ktor#1504] opened 2019-12-17 07:03 UTC
Compression Feature can not support stream response, response data at `call.respond` done every time.

```kotlin
install(Compression)

call.respond(object : OutgoingContent.WriteChannelContent() {
            override val contentType = ContentType("application", "stream+json")
            override val status: HttpStatusCode? = HttpStatusCode.OK

            override suspend fun writeTo(channel: ByteWriteChannel) {
                channel.writeLong(1L)
                channel.flush()
                delay(2000)
                channel.writeLong(2L)
                channel.flush()
            }
}
```

Expect the same as not enabling compression, invoke `flush` method can send chunk response.

**Comment by cy6erGn0m** [comment] 2019-12-17 16:08
Compress does support streaming but compression is block-based so it does only flush once a buffer is compressed.

**Comment by icode** [comment] 2019-12-17 16:10
@cy6erGn0m How to flush compressed buffer?

**Comment by cy6erGn0m** [comment] 2019-12-17 16:17
Unfortunately, you can't. It is always buffered with no flush support for now.

**Comment by cy6erGn0m** [comment] 2019-12-17 16:17
So you can't use compression with json+stream

**Comment by icode** [comment] 2019-12-17 16:21
So, can you support it? A lot of chunk streaming function not work on compress now.

**Comment by icode** [comment] 2019-12-17 16:24
And, can you support stream+json feature? Same like Spring WebFlux.

**Comment by oleg-larshin** [comment] 2020-08-10 15:28
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-507">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment] 2021-07-12 13:03
Cannot reproduce with Ktor 1.6.1.

**Closed by Stexxe** 2021-07-12 13:03 UTC
Labels: feature
