### ISSUE TITLE
Incorrect parsing of query parameters

### ISSUE THREAD

**Issue by McDjuady** [ktorio/ktor#1221] opened 2019-07-03 17:01 UTC
Ktor Version: 1.2.2

Ktor Engine Used: Client - OkHttp, followRedirects set to false

Operating System: JVM 1.8 Windows 10 64-bit

Issue:
A site I'm trying to access redirects me to a path similar to "http://\<url\>/\<page\>?PartOf?Name=Value" 
Ktor will encode this to "http://\<url\>/\<page\>?PartOf%3Name=Value"
According to https://tools.ietf.org/html/rfc3986#section-3.4 this is incorrect, as any ? following the first should be treated the same as a normal character.
If redirects are handled by the engine itself (e.g. OkHttp) this is handled correctly. In my case i need access to redirects though so this is not an option

**Comment by cy6erGn0m** [comment] 2019-07-04 10:03
Well, this URL is definitely not correct: it should be host-port spec after `//`

**Comment by McDjuady** [comment] 2019-07-04 10:06
Sorry my bad. I didn't escape the characters correctly in my post. Fixed it now

**Comment by McDjuady** [comment] 2019-07-04 13:16
Was this fixed?

**Comment by oleg-larshin** [comment] 2020-08-10 15:30
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-597">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment] 2021-07-22 11:51
Cannot reproduce using Ktor 1.6.1.
Server:
```kt
embeddedServer(Netty, port = 8080) {
    routing {
        get("/") {
            call.respondRedirect("/?PartOf?Name=Value")
        }
    }
}.start(wait = true)
```

Client:
```kt
val client = HttpClient(OkHttp) {
    followRedirects = false
    expectSuccess = false
}

val r = client.get<HttpResponse>("http://localhost:8080")
println(r.headers["Location"]) // Prints /?PartOf?Name=Value
```

**Closed by Stexxe** 2021-07-22 11:51 UTC
Labels: bug
