### ISSUE TITLE
Crash on multiple requests 

### ISSUE THREAD

**Issue by desgraci** [ktorio/ktor#1395] opened 2019-10-10 13:54 UTC
**Ktor Version and Engine Used (client or server and name)**
Common:
using 
apply plugin: 'kotlinx-serialization'

dependencies:
io.ktor:ktor-client-core:1.2.5
io.ktor:ktor-client-json:1.2.5
io.ktor:ktor-client-serialization:1.2.5
org.jetbrains.kotlinx:kotlinx-serialization-runtime-common:0.13.0
Android:
io.ktor:ktor-client-android:1.2.5
io.ktor:ktor-client-json-jvm:1.2.5
io.ktor:ktor-client-serialization-jvm:1.2.5

**Describe the bug**
Requesting multiple times in a short period (e.g. concurrent calls) from the library causes a crash.

**To Reproduce**
1. Creating a button to load any url, click it multiple times quickly, eventually it will fail
2. Using K/N and kodein
```
bind<HttpClient>() with provider {
        HttpClient {
            install(JsonFeature) {
                serializer = KotlinxSerializer(Json.nonstrict).apply {
                    setMapper(ApiResponse::class, ApiResponse.serializer())
                }

            }
            install(HttpCallValidator)
        }
    }
```
And to consume it:

```
override suspend fun getResponse(): ApiResponse  {
        val apiResponse = client.get<ApiResponse> {
            apiUrl("random")
        }
        return ApiResult.FetchedReponse(apiResponse)
    }
}
```

3. See error
```
Process: com.vonderful.testapi.lib, PID: 19866
    io.ktor.client.call.NoTransformationFoundException: No transformation found: class kotlinx.coroutines.io.ByteBufferChannel (Kotlin reflection is not available) -> class com.vonderful.testapi.data.ApiResponse (Kotlin reflection is not available)
    at io.ktor.client.call.HttpClientCall.receive(HttpClientCall.kt:88)
    at com.vonderful.testapi.data.RemoteApiDataSourceImpl.getRandom(RemotePhotoApiDataSource.kt:48)
    at com.vonderful.testapi.data.RemoteApiDataSourceImpl$getRandom$1.invokeSuspend(Unknown Source:11)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:215)
    at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:172)
    at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
    at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:122)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
    at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:215)
    at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:172)
    at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
    at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:122)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
    at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:215)
    at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:172)
    at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
    at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:122)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
    at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
```

**Expected behavior**
Even with a debounce system of 500 the `io.ktor.client.call.NoTransformationFoundException: No transformation found: class kotlinx.coroutines.io.ByteBufferChannel (Kotlin reflection is not available)` is quite easy to reproduce...

**Comment by cy6erGn0m** [comment] 2019-10-11 08:27
> Kotlin reflection is not available

🤔

**Comment by shanling** [comment] 2019-11-04 06:48
I am getting this same issue with a single request using the same `setMapper()` function with Kotinx.Serialization. It's only happening on my multi-platform project. I'm using the CIO engine with `jvmMain`. I've attached the log.

[ktor_exception.txt](https://github.com/ktorio/ktor/files/3802870/ktor_exception.txt)

**Comment by luca992** [comment] 2019-11-23 02:42
you might have to set acceptContentTypes when installing JsonFeature. What content types are your requests using?

**Comment by mdenissov** [comment] 2019-11-28 17:06
Have the same problem 

Android:
io.ktor.client.call.NoTransformationFoundException: No transformation found: class kotlinx.coroutines.io.ByteBufferChannel (Kotlin reflection is not available) -> class

iOS:
io.ktor.client.call.NoTransformationFoundException: No transformation found: class kotlinx.coroutines.io.ByteChannelNative -> class

**Comment by oleg-larshin** [comment] 2020-08-10 15:30
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-543">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by xsveda** [comment] 2020-09-10 08:02
Same issue encountered with `Ktor 1.4.0`. The problem is in incomplete configuration where `acceptContentTypes` must be defined manually. In your case:
```
            install(JsonFeature) {
    ----->      accept(ContentType.Application.Json)
                serializer = KotlinxSerializer(Json.nonstrict).apply {
                    setMapper(ApiResponse::class, ApiResponse.serializer())
                }
            }
```

**Comment by charleston10** [comment] 2020-11-20 16:59
someone managed to solve the problem?

**Comment by Stexxe** [comment] 2021-07-26 13:27
Cannot reproduce it using Ktor 1.6.1 with the following code:
```kt
@OptIn(InternalAPI::class)
fun main() = runBlocking {
    val client = HttpClient(CIO) {
        install(JsonFeature) {
            serializer = KotlinxSerializer(kotlinx.serialization.json.Json {
                ignoreUnknownKeys = true
            })
        }
        install(HttpCallValidator)
    }

    (1..100).map {
        async {
            val r = client.get<ApiResponse>("http://httpbin.org/get") {
                header("custom", "value")
            }

            println(r)
        }
    }.awaitAll()

    client.close()
}

@Serializable
data class ApiResponse(val origin: String)
```

**Closed by Stexxe** 2021-07-26 13:27 UTC
Labels: bug
