### ISSUE TITLE
io.ktor.sessions.CacheStorage.invalidate() rethrows cached exception

### ISSUE THREAD

**Issue by planerist** [ktorio/ktor#1444] opened 2019-11-15 20:31 UTC
**Ktor 1.2.3 –  ktor-server-session**

**Describe the bug**
io.ktor.sessions.CacheStorage.write()  throws cached exception

**To Reproduce**
1. _var cachedStorage =  CacheStorage(delegateStorage,...)_
2. _cachedStorage.read("myid",...)_ – this will throw NoSuchElementException from delegateStorage
3. Subsequent _cachedStorage.read("myId",.. )_ will throw cached NoSuchElementException as acrually caches kotlinx.coroutines.Deferred<T> – this is desired behaviour
4. But calling _cachedStorage.write("myId",..)_ or _cachedStorage.invalidate("myId",...)_ also thows that cached exception. This breaks ktor session behavior, confuses users and makes them reload page multiple times.

**Expected behavior**
Just ignore cached exception for invalidate & write

**Comment by oleg-larshin** [comment] 2020-08-10 15:30
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-526">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment] 2021-07-16 11:22
Cannot reproduce with Ktor 1.6.1 by running the following code:
```kt
suspend fun main() {
    val delegate = SessionStorageMemory()
    val storage = CacheStorage(delegate, 100)

    try {
        storage.read("id") {}
    } catch (cause: NoSuchElementException) {
        println(cause)
    }

    try {
        storage.write("id") {
            it.writeStringUtf8("value")
        }
    } catch (cause: NoSuchElementException) {
        println(cause)
    }

    try {
        storage.read("id") {}
    } catch (cause: NoSuchElementException) {
        println(cause)
    }
}
```

**Closed by Stexxe** 2021-07-16 11:22 UTC
Labels: bug
