### ISSUE TITLE
Ktor HttpClient runs forever (after encountering an error in the previous execution)

### ISSUE THREAD

**Issue by nikhilgupta16** [ktorio/ktor#679] opened 2018-10-29 07:01 UTC
Hi Team,

**Scenario:**
Host 1.1.1.1/8080 in my case takes a bit of time to get running, hence when I perform a get on the host 1.1.1.1/8080 I get a ConnectException. Since, I am expecting it I add a delay and reconnect with the host after 5 seconds until a certain defined interval.

I have 2 code snippets below (working one, failing one):

**Not working:**
The first execution throws an exception, which leads to a delay of 5 seconds. The execution then retries to perform a get and hangs forever.

```
while (condition) {
	try {
		httpStatusCode = httpClient.get<HttpResponse> {
			method = HttpMethod.Get
			url("http://1.1.1.1:8080")
		}.status.value
	} catch (exception: ConnectException) {
		delay( 5, TimeUnit.SECONDS)
	}
}
```

**Working:**
The first execution throws an exception. I reinitialize the client and reconnect after 5 seconds. The execution goes through after a couple of tries (when the host is up)

```
while (condition) {
	try {
		httpStatusCode = httpClient.get<HttpResponse> {
			method = HttpMethod.Get
			url("http://1.1.1.1:8080")
		}.status.value
	} catch (exception: ConnectException) {
		httpClient = HttpClient(CIO)
		delay( 5, TimeUnit.SECONDS)
	}
} 
```

After reaching out to the #ktor community on slack, I was advised to raise a bug for this.

**Comment by e5l** [comment] 2018-11-08 13:44
Hi, @nikhilgupta16. Thanks for the report.
The `HttpResponse` object should be explicitly closed. 

Could you check if the problem appears if you close all responses(even when exception throws)?
You could use `get<HttpResponse>("http://1.1.1.1:8080").use { response -> } `for it.

**Comment by ps-feng** [comment] 2018-12-19 12:15
Hi @e5l. Why is it necessary to explicitly close `HttpResponse` but it's apparently not when you have some Json serializer? In `get<SerializedObject>` you don't have access to a `Closeable` interface anymore.

Also, I'm not sure if it's the same but it seems the response is already closed in https://github.com/ktorio/ktor/blob/master/ktor-client/ktor-client-apache/src/io/ktor/client/engine/apache/ApacheHttpRequest.kt#L38? (if you use Apache, that is). 

In any case though, I've also tried `use`ing `HttpResponse` and I get the same problem. More findings in https://github.com/ktorio/ktor/issues/770#issuecomment-448567997

**Comment by e5l** [comment] 2018-12-19 15:44
Cause ‘HttpReaponse’ holds the connection(for the response channel), so you have to release it manually by closing the response.

**Comment by e5l** [comment] 2019-02-15 12:07
Please reopen if the problem happens after  `close()` call.

**Comment by ps-feng** [comment] 2019-02-15 12:09
The problem does happen after `close()` as well. Please refer to my comment above for more info as I believe there are unanswered issues.

**Comment by e5l** [comment] 2019-02-27 08:33
Related #770 is fixed in master. Could you try to test against it?

**Comment by e5l** [comment] 2019-04-16 09:11
Closed. Please reopen if the problem is active.

**Closed by e5l** 2019-04-16 09:11 UTC
