### ISSUE TITLE
Why is the HttpClient.request changing response/return type depending on if i use Features or not?

### ISSUE THREAD

**Issue by Syrou** [ktorio/ktor#930] opened 2019-02-05 11:35 UTC
### Ktor Version
1.1.2
### Ktor Engine Used(client or server and name)
Client
### JVM Version, Operating System and Relevant Context
Android
### Feedback
Why is the httpClient.request changing response/return type depending on if i use Features or not?
I am trying to wrap a promise like solution to the httpClient.request response but for whatever reason
it will change between HttpResponse and io.ktor.client.features.observer.DelegatedResponse if I use logging.

This is while using KotlinxSerializer too, so it does not even seem to map it to json
     
```
internal suspend inline fun <reified T> makeRequest(): T? {
            val httpClient = HttpClient(mBlockHttpClientConfig)
            var result: T? = null
            try {
                result = httpClient.request<T> {
                    method = mHttpMethod
                    url {
                        takeFrom(restieUrl)
                        encodedPath = mPath
                    }
                    mContentType?.let {
                        accept(it)
                    }
                    mParameters.takeIf { it.size > 0 } ?: let {
                        mParameters.forEach { param ->
                            parameter(param.first, param.second)
                        }
                    }
                    body = mBody
                }
                SdkLogger(LOGGER_TYPE.DANGEROUS, "WTF: $result")
            } catch (e: Exception) {
                SdkLogger(LOGGER_TYPE.ERROR, "BOOOM: ${e.message}")
            } finally {
                return result
            }
        }
```

This is currently not able to cast the specified generic even though mBlockHttpClientConfig contains:
```
install(JsonFeature) {
                serializer = KotlinxSerializer().apply {
                    setMapper(GameAvailable::class, GameAvailable.serializer())
                    setMapper(GameOptions::class, GameOptions.serializer())
                    setMapper(ReportMatch::class, ReportMatch.serializer())
                }
            }
```

calling makeRequest<GameOptions> (as an example) should give me GameOptions back, but it does not

**Comment by Syrou** [comment] 2019-02-05 12:39
Found the error. Basicly deep down in the JsonSerializer feature. If it tries to re-map a value which for instance is missing a field declaration or a field that is not marked as optional and handeled, everything will just stop midway without ever being resolved.

As far as I can see: KotlinxSerializer needs to handle the exception because we can not catch the feature exception ourselves as things are now.

I solved it like this by overriding KotlinxSerializer::read method:
```
    override suspend fun read(type: TypeInfo, response: HttpResponse): Any {
        var result: Any? = null
        try {
            val mapper = mappers[type.type]!!
            val text = response.readText(charset = Charsets.UTF_8)
            result = Json.nonstrict.parse(mapper, text)
        } catch (e: Exception) {
            println(e.message)
        } finally {
            return result ?: ""
        }
    }
```
To finally be able to tell what the error was

**Comment by e5l** [comment] 2019-02-06 11:30
Hi @Syrou, thanks for the report.
Why do you want to catch the exception inside serializer?

**Comment by Syrou** [comment] 2019-02-06 11:58
@e5l Hi! Well I have to catch it down there as things are now, because it does not seems like Ktor is able to inform me that fields are not properly setup when using the Serializer. The result was that no json bodies got serialized and the flow just stopped entirely without ever informing me of the reason why. The only thing I noticed was that the return after httpClient.request was either `HttpResponse and io.ktor.client.features.observer.DelegatedResponse`

And not the serialized type that I was expecting. There does not seem to be a way I can catch this error as things are now

**Comment by e5l** [comment] 2019-02-06 11:59
Could you provide the code sample?

**Comment by e5l** [comment] 2019-02-06 12:01
Could you provide the logger output before the serializer transformation?

**Comment by Syrou** [comment] 2019-02-06 12:25
@e5l I added this code to my extension of the JsonFeature:
```
        scope.responsePipeline.intercept(HttpResponsePipeline.Receive) { (info, response) ->
                println("Before Transform Content Type: ${context.response.contentType()}")
                println("Before Transform Type Info: ${info}")
                println("Before Transform object instance:$response")
            }

```

This gives me the output:
```
Before Transform Content Type: application/json
Before Transform Type Info: TypeInfo(type=class com.random.models.RandomOptions, reifiedType=class com.random.models.RandomOptions)
Before Transform:io.ktor.client.features.observer.DelegatedResponse@4ad13e1

```
If this is not what you were asking for you can reach me on your slack channel under the name :Joakim Forslund

**Comment by Syrou** [comment] 2019-02-12 10:08
@e5l Could the error be that everything gets stick because of me running everything like this:

```
        inline fun <reified T> build(): RestieResult<T> {
            val restieResult: RestieResult<T> = RestieResult()
            GlobalScope.launch(PLATFORM_DISPATCHER) {
                try {
                    val makeRequestAsync: Deferred<T?> = GlobalScope.async { return@async makeRequest<T?>() }
                    val requestResult: T? = makeRequestAsync.await()
                    requestResult?.let { resolvedResult ->
                        restieResult.broadcastSuccess(resolvedResult)
                    } ?: run {
                        restieResult.broadcastFailure(Exception("We were not able to resolve the request"))
                    }
                } catch (e: Exception) {
                    restieResult.broadcastFailure(e)
                }
            }
            return restieResult
        }
```

Where maybe the async coroutine is eating up the exception normally thrown?

**Comment by e5l** [comment] 2019-03-22 08:04
The issue is fixed in `develop`

**Closed by e5l** 2019-03-22 08:04 UTC
Labels: problem

**Comment by Syrou** [comment] 2019-03-22 08:30
@e5l Out of curiosity which commit fixed the issue?

**Comment by e5l** [comment] 2019-03-22 10:19
https://github.com/ktorio/ktor/commit/a02621f014f5293e57bf45d1b33a8e929a5699ca
