### ISSUE TITLE
client web-socket does not connect on graal native-image on Windows

### ISSUE THREAD

**Issue by ashishs** [ktorio/ktor#1987] opened 2020-07-01 08:43 UTC
**Ktor Version and Engine Used (client or server and name)**
1.32, client, CIO/okhttp, websockets, only affects graal native-image on Windows 10, does not affect graalvm JIT, hotspot, etc.

**Describe the bug**
Client web-socket session is not started on graalvm.
`io.ktor.util.random - NativePRNGNonBlocking is not found, fallback to SHA1PRNG` 

**To Reproduce**
```
val httpClient = HttpClient(CIO) {
            install(WebSockets)
        }

httpClient.webSocket(
{ url(server.toString()) }, 
{
  // this is never executed, client ws session never starts.
 // ws connected but session is not started, app hangs
 debug log: io.ktor.util.random - NativePRNGNonBlocking is not found, fallback to SHA1PRNG`
}
})
```

**Expected behavior**
The client ws session should start after ws is connected.

**Screenshots**
NA

**Comment by ashishs** [comment] 2020-07-01 15:24
Please find the wireshark capture below.

ktor ws-server (55443) responds with a HTTP Upgrade
ktor ws-client (65011) sends a tcp ack, then hangs

No.	Time	Source	Destination	Protocol	Length	Info
1	0.000000	127.0.0.1	127.0.0.1	TCP	108	65011 → 55443 [SYN] Seq=0 Win=65535 Len=0 MSS=65495 WS=256 SACK_PERM=1
2	0.000036	127.0.0.1	127.0.0.1	TCP	108	55443 → 65011 [SYN, ACK] Seq=0 Ack=1 Win=65535 Len=0 MSS=65495 WS=256 SACK_PERM=1
3	0.000066	127.0.0.1	127.0.0.1	TCP	84	65011 → 55443 [ACK] Seq=1 Ack=1 Win=2619648 Len=0
4	0.000587	127.0.0.1	127.0.0.1	HTTP	299	GET / HTTP/1.1 
5	0.000605	127.0.0.1	127.0.0.1	TCP	84	55443 → 65011 [ACK] Seq=1 Ack=216 Win=2619648 Len=0
6	0.001143	127.0.0.1	127.0.0.1	HTTP	213	HTTP/1.1 101 Switching Protocols 
7	0.001185	127.0.0.1	127.0.0.1	TCP	84	65011 → 55443 [ACK] Seq=216 Ack=130 Win=2619648 Len=0

**Comment by oleg-larshin** [comment] 2020-08-10 15:32
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-317">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment] 2022-02-08 13:45
Cannot reproduce this problem using Ktor 1.6.1

**Closed by Stexxe** 2022-02-08 13:45 UTC
Labels: bug
