### ISSUE TITLE
Websocket failures

### ISSUE THREAD

**Issue by coder82** [ktorio/ktor#752] opened 2018-11-22 15:45 UTC
### Ktor Version
0.9.3
### Ktor Engine Used(client or server and name)
Server Netty
### JVM Version, Operating System and Relevant Context
1.8.0_172
### Feedback

I found various issues with Websockets, often happening after they run for a long time (months)
They work properly but all of a sudden some exception happen and subsequent websocket clients are not able to connect again, websocket handlers are never called again.

Exception i observed throughout time are below:

This seems to be some sort of a protocol error or incomplete packet received.
After this happened, it went into an inconsistent state.
```
2018-11-19 14:39:46.485|nettyWorkerPool-3-2 @coroutine#82620|Routing.kt:121:doResume() - [ERROR] Application: Websocket handler failed
kotlinx.coroutines.experimental.JobCancellationException: Child job was cancelled because of parent failure
	at kotlinx.coroutines.experimental.JobSupport.cancelChildrenInternal(JobSupport.kt:587)
	at kotlinx.coroutines.experimental.JobSupport.makeCompletingInternal(JobSupport.kt:572)
	at kotlinx.coroutines.experimental.JobSupport.makeCompleting$kotlinx_coroutines_core(JobSupport.kt:525)
	at kotlinx.coroutines.experimental.JobSupport.makeCompletingOnCancel(JobSupport.kt:519)
	at kotlinx.coroutines.experimental.JobSupport.cancel(JobSupport.kt:463)
	at kotlinx.coroutines.experimental.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:45)
	at kotlinx.coroutines.experimental.StandaloneCoroutine.onFinishingInternal$kotlinx_coroutines_core(Builders.common.kt:174)
	at kotlinx.coroutines.experimental.JobSupport.makeCompletingInternal(JobSupport.kt:577)
	at kotlinx.coroutines.experimental.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:539)
	at kotlinx.coroutines.experimental.AbstractCoroutine.resumeWithException(AbstractCoroutine.kt:122)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resumeWithException(CoroutineImpl.kt:47)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:41)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:41)
	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:162)
	at kotlinx.coroutines.experimental.io.internal.MutableDelegateContinuation.run(MutableDelegateContinuation.kt:14)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Unsupported opcode b
	at io.ktor.http.cio.websocket.FrameParser.getFrameType(FrameParser.kt:26)
	at io.ktor.http.cio.websocket.FrameParser.parseHeader1(FrameParser.kt:69)
	at io.ktor.http.cio.websocket.FrameParser.handleStep(FrameParser.kt:56)
	at io.ktor.http.cio.websocket.FrameParser.frame(FrameParser.kt:52)
	at io.ktor.http.cio.websocket.WebSocketReader.parseLoop(WebSocketReader.kt:72)
	at io.ktor.http.cio.websocket.WebSocketReader.readLoop(WebSocketReader.kt:63)
	at io.ktor.http.cio.websocket.WebSocketReader$readLoop$1.doResume(WebSocketReader.kt)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
	... 9 common frames omitted
```

This one as well, how is possible to send the same response over a websocket?
It's not quite clear.

```
2018-11-21 07:59:43.079|nettyWorkerPool-3-2 @coroutine#182725|Routing.kt:121:doResume() - [ERROR] Application: Websocket handler failed
io.ktor.server.engine.BaseApplicationResponse$ResponseAlreadySentException: Response has already been sent
	at io.ktor.server.engine.BaseApplicationResponse$$special$$inlined$apply$lambda$1.doResume(BaseApplicationResponse.kt:32)
	at io.ktor.server.engine.BaseApplicationResponse$$special$$inlined$apply$lambda$1.invoke(BaseApplicationResponse.kt)
	at io.ktor.server.engine.BaseApplicationResponse$$special$$inlined$apply$lambda$1.invoke(BaseApplicationResponse.kt:16)
	at io.ktor.pipeline.PipelineContext.proceed(PipelineContext.kt:49)
	at io.ktor.pipeline.PipelineContext.proceedWith(PipelineContext.kt:35)
	at io.ktor.server.engine.DefaultTransformKt$installDefaultTransformations$1.doResume(DefaultTransform.kt:22)
	at io.ktor.server.engine.DefaultTransformKt$installDefaultTransformations$1.invoke(DefaultTransform.kt)
	at io.ktor.server.engine.DefaultTransformKt$installDefaultTransformations$1.invoke(DefaultTransform.kt)
	at io.ktor.pipeline.PipelineContext.proceed(PipelineContext.kt:49)
	at io.ktor.pipeline.Pipeline.execute(Pipeline.kt:22)
	at routes.AdapterKt$handleAfClients$1.doResume(Adapter.kt:143)
	at routes.AdapterKt$handleAfClients$1.invoke(Adapter.kt)
	at routes.AdapterKt$handleAfClients$1.invoke(Adapter.kt)
	at io.ktor.websocket.RoutingKt$proceedWebSocket$2.doResume(Routing.kt:119)
	at io.ktor.websocket.RoutingKt$proceedWebSocket$2.invoke(Routing.kt)
	at io.ktor.websocket.RoutingKt$proceedWebSocket$2.invoke(Routing.kt)
	at io.ktor.http.cio.websocket.DefaultWebSocketSessionImplKt.run(DefaultWebSocketSessionImpl.kt:165)
	at io.ktor.websocket.RoutingKt.proceedWebSocket(Routing.kt:117)
	at io.ktor.websocket.RoutingKt$webSocket$2.doResume(Routing.kt:92)
	at io.ktor.websocket.RoutingKt$webSocket$2.invoke(Routing.kt)
	at io.ktor.websocket.RoutingKt$webSocket$2.invoke(Routing.kt)
	at io.ktor.websocket.RoutingKt$webSocketRaw$2$1$1$1$1.doResume(Routing.kt:52)
	at io.ktor.websocket.RoutingKt$webSocketRaw$2$1$1$1$1.invoke(Routing.kt)
	at io.ktor.websocket.RoutingKt$webSocketRaw$2$1$1$1$1.invoke(Routing.kt)
	at io.ktor.http.cio.websocket.RawWebSocketKt.start(RawWebSocket.kt:49)
	at io.ktor.websocket.WebSocketUpgrade$upgrade$2.doResume(WebSocketUpgrade.kt:54)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:162)
	at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:26)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by cy6erGn0m** [comment] 2018-11-22 16:07
The first looks like there is some wrong parent-child relation that caused global parent job to crash after that there is no way to launch children anymore.

For the second looks misterious. According to the stacktrace call send pipeline has been executed from the websocket pipeline (usually `call.respond(T)` does it)

**Comment by cy6erGn0m** [comment] 2018-11-22 16:50
The reason why I suspect your handler in the second case is the following part of the stacktrace:

```stacktrace
at io.ktor.pipeline.Pipeline.execute(Pipeline.kt:22)
	at routes.AdapterKt$handleAfClients$1.doResume(Adapter.kt:143)
	at routes.AdapterKt$handleAfClients$1.invoke(Adapter.kt)
	at routes.AdapterKt$handleAfClients$1.invoke(Adapter.kt)
```

**Comment by cy6erGn0m** [comment] 2018-11-22 17:06
What kotlinx.coroutines do you use with ktor 0.9.4?

**Comment by coder82** [comment] 2018-11-22 17:48
Yes I have a call to respond in there, then I suspect I cannot use call.respond inside a websocket handler, wouldn't make sense. All I wanted to send is a closing message, then I'll rather do:

close(CloseReason(CloseReason.Codes.VIOLATED_POLICY, "go away"))

**Comment by cy6erGn0m** [comment] 2018-11-22 18:46
Yes, exactly. Perhaps we need to improve diagnostics here...

**Comment by cy6erGn0m** [comment] 2018-11-23 09:56
Do you see the first for every attempt to connect?

**Comment by coder82** [comment] 2018-11-23 10:08
No, the first exception happens rarely.

**Comment by e5l** [comment] 2020-03-24 09:24
Hi @coder82, could you check the problem with `1.3.2`?

**Comment by knrybarczyk** [comment] 2020-08-06 09:34
I'm seeing this occasionally when running e2e tests with ktor 1.3.2 using handleWebsocket. Sometimes the test fails with "Unsupported opcode b". Are there any plans on fixing this?

**Comment by oleg-larshin** [comment] 2020-08-10 15:29
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-719">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment] 2021-04-05 07:52
Can't reproduce in 1.4.1

**Closed by e5l** 2021-04-05 07:52 UTC
Labels: bug
