### ISSUE TITLE
Failed to get session from cache: `IllegalStateException: Daemon thread is already dead`

### ISSUE THREAD

**Issue by kobevaliant** [ktorio/ktor#1922] opened 2020-06-04 08:15 UTC
Hi
Recently I encountered  this exception several times, I thought it may be a bug about session.

![1](https://user-images.githubusercontent.com/5119651/83732329-778c6080-a67e-11ea-8ad7-e62e50f8b62d.png)

**Comment by e5l** [comment] 2020-06-04 11:29
Hi @kobevaliant, thanks for the report.
Could you share the snippet to help reproduce the problem?

**Comment by kobe2000** [comment] 2020-06-15 01:27
Hi
I used session like following, which is very simple
```
// session object
data class FfpSession(val userId: String)

//install session
install(Sessions) {
        cookie<FfpSession>(
            "SESSION_ID",
            directorySessionStorage(File(".sessions"), cached = true)
        ) {
            cookie.path = "/"
        }
}

//use
val session = sessions.get<FfpSession>()
```

**Comment by oleg-larshin** [comment] 2020-08-10 15:27
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-353">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment] 2021-04-05 15:48
Fixed since 1.5.0

**Closed by e5l** 2021-04-05 15:48 UTC
Labels: bug, triaged
