### ISSUE TITLE
"HTTP Exception 404" for POST from Location

### ISSUE THREAD

**Issue by BorzdeG** [ktorio/ktor#601] opened 2018-09-23 03:58 UTC
`Unhandled: POST - /sample00`

sample code: https://github.com/BorzdeG/sample-ktor-kodein-controllers/blob/master/sample-00/src/main/kotlin/sample/sample00/Sample00Controller.kt#L24

tests: https://github.com/BorzdeG/sample-ktor-kodein-controllers/blob/master/sample-00/src/test/kotlin/sample/sample00/Sample00ControllerTest.kt

**Comment by rinoguchi** [comment] 2019-05-20 10:31
I faced the same problem.

Ktor Version
1.2.0

- pattern1: 404 error occurs.
```kotlin
@Location("/hoge")
data class HogeParamater(val param1, val param2)
routing {
    post<HogeParamater> { param ->
        // do something with param
    }
}
```

- pattern2: 404 error does not occur. But `param` remains at the default value.
``` kotlin
@Location("/hoge")
data class HogeParamater(val param1: String = "default1", val param2: String = "default2")
routing {
    post<HogeParamater> { param ->
        // do something with param
    }
}
```

- pattern3: 404 error does not occur and works well. But URL must be changed.
```kotlin
@Location("/hoge/{param1}/{param2}")
data class HogeParamater(val param1, val param2)
routing {
    post<HogeParamater> { param ->
        // do something with param
    }
}
```

**Comment by mspmax** [comment] 2020-01-06 04:43
Any updates on this? maybe @cy6erGn0m could give some insights? :) I'm on `1.2.6`. Thanks in advance

**Comment by Globegitter** [comment] 2020-01-13 10:40
@cy6erGn0m I have been testing this on the latest `1.2.6` as well as `1.3.0-rc2` and it still does not seem to work - any idea if a fix for this will come by the time 1.3.0 gets released?

**Comment by mintu19** [comment] 2020-04-19 13:07
any update on this?

**Comment by oleg-larshin** [comment] 2020-08-10 15:23
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-740">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment] 2021-04-02 09:13
Can't reproduce since 1.4.0

**Closed by e5l** 2021-04-02 09:13 UTC
