### ISSUE TITLE
Basic Authentication fails with counter-intuitive exception

### ISSUE THREAD

**Issue by suushiemaniac** [ktorio/ktor#1051] opened 2019-04-01 13:52 UTC
### Ktor Version
1.1.3

### Ktor Engine Used(client or server and name)
Apache
client only

### JVM Version, Operating System and Relevant Context
JVM from OpenJDK 1.8.0_191
Ubuntu 18.04 operating system

operating with `io.ktor:ktor-client-core` and `io.ktor:ktor-client-apache` only.
Connecting to an external 3rd party service, so the server is not on ktor and is to be considered a black box.

`io.ktor:ktor-client-auth` plugin for Basic Authentication.

### Feedback
When (accidentally) using the wrong username/password for `BasicAuthProvider` in the `io.ktor:ktor-client-auth` plugin, the client ultimately throws a `SendCountExceedException` because the engine just tries sending again and again until the treshold is reached/surpassed.

I would expect and wish for a more meaningful exception to be thrown when authorization fails. The server does correctly yield response code `401`.

**Comment by fdc-maku** [comment] 2019-04-09 06:58
I have the same problem. A 3rd party service I was trying to connect to already blocked the user because I accidentally used the wrong password and the ktor client retries to connect to the service with these wrong credentials 20 times.

**Comment by e5l** [comment] 2019-04-09 07:22
Hi, @suushiemaniac, thanks for the report.
It's a bug and obviously should be fixed.

**Comment by suushiemaniac** [comment] 2019-05-21 15:33
Is there any progress on this? Just a kind ping, no stress :)

**Comment by e5l** [comment] 2019-05-21 15:36
Not yet. Btw PR's are always welcome :)

**Comment by Brunomachadob** [comment] 2019-06-28 11:27
I could try to help with this one, it seems to be a fairly straightforward issue to start with.
I managed to reproduce the problem here.

But just to have a better context, why do we have `ktor-client-auth` and `ktor-client-auth-basic`?

As far as I understood `ktor-client-auth-basic` just intercept the request and append the header, while the other use this complex retry mechanism which I'm still digging into.
Shouldn't we have just one of them with the possibility to retry or not?

Any considerations before I start working on this?

**Comment by e5l** [comment] 2019-06-28 12:29
Hi @Brunomachadob, awesome to hear :) 
`ktor-client-auth` was JVM-only and `ktor-client-auth-basic` multiplatform, now `ktor-client-auth` is multiplatform and `ktor-client-auth-basic` deprecated.

Probably we can add `simple` mode without retry as we had before. 

BTW. If you have more questions feel free to ask me here or in our slack: `kotlinlang.slack.com`  #ktor channel.

**Comment by jensbaitingerbosch** [comment] 2019-10-16 12:10
The bug also also occurs with the CIO and Jetty client engine

**Comment by jensbaitingerbosch** [comment] 2019-10-17 08:02
Unfortunately I am not allowed from my company to make PRs (at least the bureaucratic barriers are quite high. But we can make suggestions (without any warrenties)...
```kotlin
scope.feature(HttpSend)!!.intercept { origin ->
                var call = origin

                val unusedProviders = MutableSet(feature.providers)
                while (call.response.status == HttpStatusCode.Unauthorized && !unusedProviders.isEmpty()) {
                    val headerValue = call.response.headers[HttpHeaders.WWWAuthenticate] ?: return@intercept call
                    val authHeader = parseAuthorizationHeader(headerValue) ?: return@intercept call
                    val provider = unusedProviders.find { it.isApplicable(authHeader) } ?: return@intercept call
                    unusedProviders -= provider

                    val request = HttpRequestBuilder()
                    request.takeFrom(call.request)
                    provider.addRequestHeaders(request)

                    call.close()
                    call = execute(request)
                }

                return@intercept call
            }
``` 

This makes sure that every provider can be used only once and if no providers for the requested Authentication method(s) remain, the call fails.

As a workaround you can set `sendWithoutRequest` property in your authetication provider to `true`. then the authentication header is added to each call (use with care for security reasons) and the call fails after the first 401

```kotlin
install(Auth) {
                basic {
                    username = "admin"
                    password = "secret"
                    sendWithoutRequest = true
                }
            }
```

**Comment by thumannw** [comment] 2020-02-01 12:33
@e5l The fix has been merged. Could you please close this issue?

**Comment by e5l** [comment] 2020-02-01 13:05
Sure!

**Closed by e5l** 2020-02-01 13:05 UTC
Labels: bug, good first issue, help wanted
