### ISSUE TITLE
[Client] GET Request result in error with body changed

### ISSUE THREAD

**Issue by JMaroz** [ktorio/ktor#1665] opened 2020-02-21 10:15 UTC
**Ktor Version and Engine Used (client or server and name)**
Ktor Version: 1.3.1
Ktor Client: Android and iOS
Ktor Modules: serialization, logging

**Describe the bug**
When sending a GET request the body changes unexpected passing from NoContent to "{}". This is making the request to fail.

**To Reproduce**

```
protected val httpClient = HttpClient(Engine) {
        install(JsonFeature) {
            serializer = KotlinxSerializer(Json.nonstrict)
        }
        install(Logging) {
            loggingConfig = this
            logger = Logger.SIMPLE
            level = LogLevel.ALL
        }
        defaultRequest {
            header(HttpHeaders.CacheControl, "no-cache")
            header(HttpHeaders.ContentType, "application/json; charset=utf-8")
            header(HttpHeaders.Accept, "application/json")
            header(HttpHeaders.AcceptEncoding, "gzip")
            header(HEADER_MWAPPS_APPID, appId)
            header(HEADER_MWAPPS_CLIENT, client)
            header(HEADER_MWAPPS_CLIENT_VERSION, clientVersion)
        }
    }
  
fun testGet(callback: Callback<String>) = CoroutineScope(Background).launch {
        val response = httpClient.get<User>(urlString = "https://jsonplaceholder.typicode.com/todos/1")
        withContext(Main) {
            callback.invoke(ApiResponse.create(response))
        }
    }
```

iOS error
```
GET method must not have a body
finished with error [-1103] Error Domain=NSURLErrorDomain Code=-1103 "resource exceeds maximum size"
```

Android error
`Request of type GET couldn't send a body with the [Android] engine.`

**Expected behavior**
Ktor should passed a EmptyContent and not change the content.

**Comment by cy6erGn0m** [comment] 2020-02-21 21:31
Isn't it because of the header?

>             header(HttpHeaders.ContentType, "application/json; charset=utf-8")

**Comment by hamada147** [comment] 2020-02-21 23:05
I just faced the same error on both iOS and Android.

**Comment by hamada147** [comment] 2020-02-21 23:39
Hello @cy6erGn0m ,
You were correct this was what was causing the issue.

@JMaroz ,
After some testing around I had to make an if condition HttpMethod is GET or HEAD then I shouldn't set the Content-Type with any value but if it is POST then I should.

I believe this is a bug as it should be possible to send GET request with body content (This is not the standard. If we want to follow the RestFul API guidelines then GET and HEAD shouldn't contains any body content and only parameters "BEST PRACTICE" unfortunately this is not the case with some APIs we deal with in our development life)

**Comment by JMaroz** [comment] 2020-02-24 16:37
Is definitely a bug because i want to set the content type to `application/json` for all my request. 

I have tested and if i remove the contentType the get request is working but if i don't set it to the put request i'll get this error `Fail to send body. Content has type: class it.test.ContentsUriBody, but OutgoingContent expected.`

**Comment by hamada147** [comment] 2020-02-25 09:28
@e5l is there is any kind of workaround

**Comment by oleg-larshin** [comment] 2020-08-10 15:31
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-465">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment] 2021-07-13 10:26
Cannot reproduce with Ktor 1.6.1.

**Closed by Stexxe** 2021-07-13 10:26 UTC
Labels: bug
