### ISSUE TITLE
Ktor client raises "ClosedSelectorException" instead of proper error

### ISSUE THREAD

**Issue by imanushin** [ktorio/ktor#1696] opened 2020-03-02 10:35 UTC
**Ktor Version and Engine Used (client or server and name)**
Client 1.3.1, JVM 11

**Describe the bug**
Sometimes Ktor Http client raises ```ClosedSelectorException``` for tcp connectivity issues. Looks like (I'm not sure) this error is the result of overloaded server, which opens tcp channels for too long time.

**To Reproduce**
Unfortunately, there aren't exact steps, which lead to error.

0. Prepare overloaded slow server on nginx (limit tcp connections also).
1. Construct Ktor Client.
2. Execute the following:
```
val response = client.request<HttpResponse>(url)

if (status.isSuccess()) {
    return ClientResponse.Success(response.readText())
}
return null
```

**Expected behavior**
```String``` with response is returned OR error with clear text/type is raised (IOException, TimeoutCancellationException, etc.)

**Actual behavior**
The following error is raised sometimes:
```
java.nio.channels.ClosedSelectorException
	at io.ktor.network.selector.ActorSelectorManager.publishInterest(ActorSelectorManager.kt:145)
	at io.ktor.network.selector.SelectorManagerSupport.select(SelectorManagerSupport.kt:47)
	at io.ktor.network.sockets.SocketImpl.connect$ktor_network(SocketImpl.kt:33)
	at io.ktor.network.sockets.TcpSocketBuilder.connect(Builders.kt:107)
	at io.ktor.client.engine.cio.ConnectionFactory.connect(ConnectionFactory.kt:26)
	at io.ktor.client.engine.cio.Endpoint$connect$$inlined$repeat$lambda$1.invokeSuspend(Endpoint.kt:159)
	at io.ktor.client.engine.cio.Endpoint$connect$$inlined$repeat$lambda$1.invoke(Endpoint.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:102)
	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:78)
	at kotlinx.coroutines.TimeoutKt.withTimeoutOrNull(Timeout.kt:57)
	at io.ktor.client.engine.cio.Endpoint.connect(Endpoint.kt:167)
	at io.ktor.client.engine.cio.Endpoint$makeDedicatedRequest$1.invokeSuspend(Endpoint.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
```

So from API user it is unable to proper understand, what was happened. Moreover, this error shows some integrity fails (not sure), however only official wrappers were used (see ```readText``` function)

**Comment by oleg-larshin** [comment] 2020-08-10 15:31
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-452">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment] 2021-07-26 14:00
Cannot reproduce using Ktor 1.6.1.

**Closed by Stexxe** 2021-07-26 14:00 UTC
Labels: bug
