### ISSUE TITLE
Code autoreload not working for me

### ISSUE THREAD

**Issue by realmhamdy** [ktorio/ktor#975] opened 2019-02-25 09:12 UTC
### Ktor Version
1.1.3
### Ktor Engine Used(client or server and name)
`EngineMain` I guess?
### JVM Version, Operating System and Relevant Context
JDK 1.8. Windows 10
### Feedback
Okay I have a new project generated using the Ktor IDEA plugin. I'm just trying to make autoreload work (which should by default?). I have only one Kotlin file in `src/Application.kt`. My `application.conf` looks like this:
```
ktor {
    deployment {
        port = 8080
        port = ${?PORT}
        autoreload = true
        watch = [ MyProjectFolder ]
    }
    application {
        modules = [ com.company.ApplicationKt.module ]
    }
}
```
The issue is, when I change `Application.kt` the project doesn't reload and the changes are not reflected in the browser.
I see this in the run output:
```
2019-02-25 11:01:46.894 [main] DEBUG Application - Watching F:\Projects\MyProjectFolder\out\production\classes for changes.
2019-02-25 11:01:46.895 [main] DEBUG Application - Watching F:\Projects\MyProjectFolder\out\production\classes\com for changes.
...
```
I also tried `com.company` instead of `MyProjectFolder` in the watch list but that one is even worse. The run output shows autoreload is disabled.

**Comment by github-account-because-they-want-it** [comment] 2019-02-26 00:16
I also think that having to use the project folder name as an autoreload setting is not reliable because it can differ from a developer to the next as it's not checked out in source control.

**Comment by absentmindedguy** [comment] 2019-04-28 17:00
Same here, I'd also say the documentation on this is just very not clear unfortunately, so it's very hard to know where to go with it... _especially on maven_ - I had to swap to gradle to get it working at all but now it seems to have just stopped working altogether

**Comment by Ykid** [comment] 2019-06-02 10:50
I believe I found the cause of this issue.

if I simply run with Intellij, compiled classes go to `<ProjectFolder>/out/production/`. [reference](https://www.jetbrains.com/help/idea/specifying-compilation-settings.html).

if you watch source changes by running `gradle -t watch`, the classes are compiled to `ProjectFolder>/build/classes/`. These two paths are *different* and ktor application is not watching the `<ProjectFolder>/out/production/`.

To solve this issue, one should avoid using intellij to run the ktor application. Use `gradle -t watch` to watch file changes and use `gradle run` to start the application. 

Hope this helps

**Comment by Reizinixc** [comment] 2019-07-10 11:17
Thank you very much @Ykid for the suggestion.

In case you chose Gradle and build the application from IntelliJ, this is what I did to make `autoreload` work.

![IntelliJ Gradle settings screen accessed from File, Settings, choose 'Build, Execution, Deployment', 'Build Tools' and Gradle](https://user-images.githubusercontent.com/1935919/60963361-89209780-a34b-11e9-8f70-3b0966524a4e.png)

Not sure about the others, but my default value is 'IntelliJ IDEA', so it didn't work before changing the configuration.

**Comment by lindenquan** [comment] 2019-08-09 21:23
I set the Gradle JVM from JDK 11 to JDK 8, then it works fine for me now.

![image](https://user-images.githubusercontent.com/14223499/62809936-c1460200-bad2-11e9-8dfc-294d7afef134.png)

**Comment by AdityaAnand1** [comment] 2020-02-02 17:59
How to use `gradle run`? The default project gives me no gradle executable (though there is a gradle.bat but I'm on MacOS)

Using gradlew does not work

@Ykid how did you get this to work?

**Comment by AdityaAnand1** [comment] 2020-02-02 18:00
@cy6erGn0m @orangy @e5l This should be super high priority. Since autoreload never works, it really worsens the development experience 😿

**Comment by skergetd** [comment] 2020-02-02 22:05
@AdityaAnand1 from intelliJ simply create new run configuration and select gradle. For task put `build `and for arguments put `-t.` After that, run this task and while running it, also run your Ktor project.

**Comment by Terkwood** [comment] 2020-06-26 16:58
This is a tough one!  I used a combination of the advice posted above in order to get mine working.  Thanks to the various contributors who helped in this thread.

Configured IntelliJ with a Run/Debug config for this project.  Note that for whatever reason, I had to specifically use `installDist` task:

![intellij_run_debug_config](https://user-images.githubusercontent.com/38859656/85881513-bad47d80-b7ab-11ea-8c3f-7a47a7348675.png)

I started that task in IntelliJ. _Then_ in the command line did the following:

```sh
gradle run
```

I am using JDK 8, which seems important based on the advice given above, and the [docs provided by Jetbrains](https://ktor.io/servers/autoreload.html):

![postbill_sdk](https://user-images.githubusercontent.com/38859656/85881844-49e19580-b7ac-11ea-8e97-134d85f8e628.png)


Incidentally I have the gradle watch config in my `gradle.properties`.  Might not be related, but at this point I'm afraid to change it :wink: 

```text
org.gradle.unsafe.watch-fs=true
```

I'm using Gradle 6.5.

**Comment by oleg-larshin** [comment] 2020-08-10 15:24
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-664">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by red-avtovo** [comment] 2020-11-04 11:07
To the person, who will go through this thread and wouldn't understand how to fix the subj, official documentation describes it clearly now: https://ktor.io/docs/autoreload.html?topic=open-source#recompiling-automatically-on-source-changes

**Closed** 2020-12-30 10:33 UTC

**Comment by joaoeudes7** [comment] 2021-02-19 01:40
It needs a lot of settings to allow this auto reload, because? (And after all it still didn't work here :/)

Vert.x for example does not need to run with a parameter to hot reload, and is defined in initial start, this implementation would take a long time?

**Comment by e5l** [comment] 2021-02-19 11:04
Hey @joaoeudes7, could you check https://ktor.io/docs/development-mode.html?

**Comment by baughmann** [comment] 2022-12-05 00:39
Those of us running the Flatpack version do not have access to the `JAVA_HOME` and thus cannot run the terminal commands through the integrated terminal.

The (mildly annoying) way around this is two have two different run configurations. One is the standard Ktor run/debug config, the other is one that watches the directory. Here's what I did:

![Screenshot from 2022-11-06 15-36-38](https://user-images.githubusercontent.com/6177411/205525981-3b34204e-dd6a-405f-801c-525a17f96e2b.png)

I will say, I love Intellij and I am loving Ktor so far, but it is kinda odd that auto reload doesn't just work "automagically" when the language, IDE, and framework are are "controlled" by the same company (at least to some extent). I'm sure it'll get there with time, I know Jetbrains has a lot of projects in the oven.

**Comment by alexoooo** [comment] 2023-01-11 01:41
example of auto-reload on backend/frontend with Ktor+React with Kotlin 1.8.0 and new IR: https://github.com/alexoooo/sample-ktor-react
