### ISSUE TITLE
ktor-client doesn't send body sometimes

### ISSUE THREAD

**Issue by jeiea** [ktorio/ktor#569] opened 2018-09-07 10:14 UTC
I uploaded [sample project](https://github.com/jeiea/ktor-issue1).

With netty ktor-server and apache ktor-client, it posts form-data a lot in short time and any moment a request with missing body occurs. This appears as `java.io.IOException: Broken delimiter occurred`.

Is this bug?

**Comment by oleg-larshin** [comment] 2020-08-10 15:23
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-747">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment] 2021-04-05 07:28
Cannot reproduce since ktor 1.4.0

**Closed by e5l** 2021-04-05 07:28 UTC
